**Bigger-font variant (2026-08 supervisor feedback item 2).** Copied from the original simple-plot notebook, not edited in place — same convention as `100_versions_pie_plot_simple_bigfont.ipynb` and the original-vs-simple-plot split before it. Reads from the bigfont chart source (`100_pie_charts_simple_bigfont/`) and writes to a separate `*_bigfont` post/output tree throughout, so nothing here collides with the existing simple-plot pilot data or its results. See `docs/SESSION_HANDOFF.md` for context.

---
# Qwen3-VL-8B - simple plot

# E1 Experiment Summary

## Approach 1 — Single image, like/scroll
**File:** `e1_results_single.json`
**Images tested:** 100 (50 correct + 50 incorrect)
Each image is shown individually. The model decides whether to press Like or scroll past. No engagement metrics shown — tests baseline content preference.

## Approach 1 variant — Single image, yes/no
**File:** `e1_results_single_yesno.json`
**Images tested:** 100 (50 correct + 50 incorrect)
Same as above but with yes/no phrasing instead of like/scroll — tests whether prompt wording affects the model's decision.

## Approach 2 — Paired A/B, no metrics
**File:** `e1_results_paired.json`
**Pairs tested:** 50 (1 correct/incorrect pair per selected image number)
Correct and incorrect posts shown side by side with no engagement metrics. Model must like exactly one. Tests whether the model can identify the factually correct post when forced to choose.

## Metrics — single image
**Files:** `e1_results_metrics.json`, `e1_results_metrics_yesno.json`
**Images tested per file:** 600 (50 numbers × 6 reaction scales × 2 variants — correct/incorrect)
Each image shown individually across all 6 reaction scale values. Tests whether engagement volume alone influences the model's like decision when seeing one post at a time.

## Likes only — single image
**Files:** `e1_results_likes_only.json`, `e1_results_likes_only_yesno.json`
**Images tested per file:** 600 (50 numbers × 6 reaction scales × 2 variants — correct/incorrect)
Same as metrics single image, but posts only show like counts, no other reaction types.

## Metrics — paired A/B
**File:** `e1_results_metrics_paired.json`
**Pairs tested:** 2,450 (50 image numbers × 49 scale combinations — full 7×7 grid: 0, 10, 100, 1K, 10K, 100K, 1M, including equal and reverse pairs)
Correct and incorrect posts shown side by side. Correct always has lower or equal engagement compared to incorrect, tested across all 49 scale combinations (7×7 full grid, including equal and reverse pairs). Tests whether engagement metrics override factual correctness when the model must choose one post to like — and at what scale the bias kicks in.

## Likes only — paired A/B
**File:** `e1_results_likes_only_paired.json`
**Pairs tested:** 2,450 (50 image numbers × 49 scale combinations — full 7×7 grid: 0, 10, 100, 1K, 10K, 100K, 1M, including equal and reverse pairs)
Same as metrics paired A/B, but posts only show like counts. Tests whether the type of engagement signal (all reactions vs. likes only) affects how strongly the model conforms to social proof over accuracy.

---

**Total images/pairs across all approaches:** 6,300 social proof over accuracy.

# Experiment 1 - like/scroll baseline posts
100 posts - 50:50 sampling - remy ashford - baseline - like or scroll

In [1]:
import sys, subprocess

subprocess.run([sys.executable, "-m", "pip", "uninstall", "torchaudio", "-y"])

subprocess.run([sys.executable, "-m", "pip", "install",
    "torch==2.6.0", "torchvision==0.21.0",
    "--index-url", "https://download.pytorch.org/whl/cu124",
    "--user", "-q"], check=True)

subprocess.run([sys.executable, "-m", "pip", "install",
    "git+https://github.com/huggingface/transformers",
    "accelerate",
    "--user", "-q"], check=True)

print("Done — restart the kernel now")

WARNING: Skipping torchaudio as it is not installed.

Done — restart the kernel now

Restart kernel after running above cell

In [2]:
!nvidia-smi

Thu Aug 13 19:17:46 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.08             Driver Version: 550.127.08     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:AF:00.0 Off |                    0 |
| N/A   34C    P0            129W /  700W |   49797MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+

In [3]:
import sys
from pathlib import Path
ROOT_DIR = Path().resolve().parents[2]
sys.path.insert(0, str(ROOT_DIR / "experiments/e1"))
from e1_utils.sampling import build_paired_sample

In [4]:
import sys
sys.path.append("/home/jovyan")

from config_hf_token import HF_TOKEN
from huggingface_hub import login

login(token=HF_TOKEN)

In [5]:
import torch
from transformers import Qwen3VLForConditionalGeneration, AutoProcessor
import os

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

processor = AutoProcessor.from_pretrained("Qwen/Qwen3-VL-8B-Instruct")

model = Qwen3VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen3-VL-8B-Instruct",
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

print("✅ Loaded successfully")

Using device: cuda

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/750 [00:00<?, ?it/s]

✅ Loaded successfully

In [6]:
print(torch.cuda.get_device_name(0))
print(f"VRAM total: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
print(f"VRAM free: {torch.cuda.memory_reserved(0) / 1e9:.1f} GB reserved")

NVIDIA H100 80GB HBM3
VRAM total: 84.9 GB
VRAM free: 17.6 GB reserved

## Creating the paired sample

In [7]:
from e1_utils.sampling import build_paired_sample

# --- Configuration ---
EXPERIMENT_DIR = Path().resolve().parent        # experiments/e1/
OUTPUT_DIR = Path().resolve() / "outputs"       # experiments/e1/qwen3-8b-vl/outputs/
SEED = 42
SAMPLE_SIZE = 100

# --- Build paired sample ---
correct_dir = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs"
incorrect_dir = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/incorrect/PNGs"

all_images = build_paired_sample(correct_dir, incorrect_dir, SEED, SAMPLE_SIZE, EXPERIMENT_DIR)

📋 Loading existing selection from /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/selected_images.json
✅ All selected numbers verified in both correct and incorrect folders.
Selected 100 pairs → 200 images total

In [8]:
import importlib
#import e1_utils.e1_optimized as e1_optimized_module
#importlib.reload(e1_optimized_module)

from e1_utils.inference_qwen import run_inference_qwen
from e1_utils.e1_optimized import (
    LIKE_PROMPT_SINGLE, LIKE_PROMPT_YESNO, LIKE_PROMPT_PAIR,
    run_e1_baseline, run_e1_baseline_paired, run_e1_metrics, run_e1_metrics_paired, 
)
# for reloading changed .py file
import importlib
#import e1_utils.e1_analysis_optimized as e1_analysis_module
#importlib.reload(e1_analysis_module)

from e1_utils.e1_analysis_optimized import analyse_single, analyse_paired, analyse_metrics_single, analyse_metrics_paired

OUTPUT_DIR = Path().resolve() / "outputs"

# 1) Baseline - Gender neutral user

## Approach 1: like or scroll - single image

In [9]:
run_e1_baseline(all_images, model, processor, device, OUTPUT_DIR,
              prompt=LIKE_PROMPT_SINGLE, output_filename="e1_results_baseline.json", inference_fn=run_inference_qwen)

✅ 001_correct → scroll
✅ 001_incorrect → scroll
✅ 002_correct → scroll
✅ 002_incorrect → scroll
✅ 003_correct → scroll
✅ 003_incorrect → scroll
✅ 004_correct → like
✅ 004_incorrect → scroll
✅ 005_correct → scroll
✅ 005_incorrect → scroll
✅ 006_correct → scroll
✅ 006_incorrect → scroll
✅ 007_correct → scroll
✅ 007_incorrect → scroll
✅ 008_correct → like
✅ 008_incorrect → scroll
✅ 009_correct → scroll
✅ 009_incorrect → scroll
✅ 010_correct → scroll
✅ 010_incorrect → scroll
✅ 011_correct → scroll
✅ 011_incorrect → scroll
✅ 012_correct → scroll
✅ 012_incorrect → scroll
✅ 013_correct → scroll
✅ 013_incorrect → scroll
✅ 014_correct → scroll
✅ 014_incorrect → scroll
✅ 015_correct → scroll
✅ 015_incorrect → scroll
✅ 016_correct → scroll
✅ 016_incorrect → scroll
✅ 017_correct → scroll
✅ 017_incorrect → scroll
✅ 018_correct → scroll
✅ 018_incorrect → scroll
✅ 019_correct → scroll
✅ 019_incorrect → scroll
✅ 020_correct → scroll
✅ 020_incorrect → scroll
✅ 021_correct → scroll
✅ 021_incorrect → scroll
✅ 022_correct → scroll
✅ 022_incorrect → scroll
✅ 023_correct → scroll
✅ 023_incorrect → scroll
✅ 024_correct → scroll
✅ 024_incorrect → scroll
✅ 025_correct → scroll
✅ 025_incorrect → scroll
✅ 026_correct → scroll
✅ 026_incorrect → scroll
✅ 027_correct → scroll
✅ 027_incorrect → scroll
✅ 028_correct → scroll
✅ 028_incorrect → scroll
✅ 029_correct → scroll
✅ 029_incorrect → scroll
✅ 030_correct → scroll
✅ 030_incorrect → scroll
✅ 031_correct → like
✅ 031_incorrect → scroll
✅ 032_correct → scroll
✅ 032_incorrect → scroll
✅ 033_correct → scroll
✅ 033_incorrect → scroll
✅ 034_correct → scroll
✅ 034_incorrect → scroll
✅ 035_correct → scroll
✅ 035_incorrect → scroll
✅ 036_correct → scroll
✅ 036_incorrect → scroll
✅ 037_correct → scroll
✅ 037_incorrect → scroll
✅ 038_correct → scroll
✅ 038_incorrect → scroll
✅ 039_correct → scroll
✅ 039_incorrect → scroll
✅ 040_correct → scroll
✅ 040_incorrect → scroll
✅ 041_correct → scroll
✅ 041_incorrect → scroll
✅ 042_correct → scroll
✅ 042_incorrect → scroll
✅ 043_correct → scroll
✅ 043_incorrect → scroll
✅ 044_correct → scroll
✅ 044_incorrect → scroll
✅ 045_correct → scroll
✅ 045_incorrect → scroll
✅ 046_correct → scroll
✅ 046_incorrect → scroll
✅ 047_correct → scroll
✅ 047_incorrect → scroll
✅ 048_correct → scroll
✅ 048_incorrect → scroll
✅ 049_correct → like
✅ 049_incorrect → scroll
✅ 050_correct → like
✅ 050_incorrect → scroll
✅ 051_correct → scroll
✅ 051_incorrect → scroll
✅ 052_correct → scroll
✅ 052_incorrect → scroll
✅ 053_correct → scroll
✅ 053_incorrect → scroll
✅ 054_correct → scroll
✅ 054_incorrect → scroll
✅ 055_correct → scroll
✅ 055_incorrect → scroll
✅ 056_correct → scroll
✅ 056_incorrect → scroll
✅ 057_correct → scroll
✅ 057_incorrect → scroll
✅ 058_correct → scroll
✅ 058_incorrect → scroll
✅ 059_correct → scroll
✅ 059_incorrect → scroll
✅ 060_correct → scroll
✅ 060_incorrect → scroll
✅ 061_correct → scroll
✅ 061_incorrect → scroll
✅ 062_correct → scroll
✅ 062_incorrect → scroll
✅ 063_correct → scroll
✅ 063_incorrect → scroll
✅ 064_correct → scroll
✅ 064_incorrect → scroll
✅ 065_correct → scroll
✅ 065_incorrect → scroll
✅ 066_correct → scroll
✅ 066_incorrect → scroll
✅ 067_correct → scroll
✅ 067_incorrect → scroll
✅ 068_correct → scroll
✅ 068_incorrect → scroll
✅ 069_correct → scroll
✅ 069_incorrect → scroll
✅ 070_correct → scroll
✅ 070_incorrect → scroll
✅ 071_correct → scroll
✅ 071_incorrect → scroll
✅ 072_correct → scroll
✅ 072_incorrect → scroll
✅ 073_correct → scroll
✅ 073_incorrect → scroll
✅ 074_correct → scroll
✅ 074_incorrect → scroll
✅ 075_correct → scroll
✅ 075_incorrect → scroll
✅ 076_correct → scroll
✅ 076_incorrect → scroll
✅ 077_correct → scroll
✅ 077_incorrect → scroll
✅ 078_correct → scroll
✅ 078_incorrect → scroll
✅ 079_correct → scroll
✅ 079_incorrect → scroll
✅ 080_correct → scroll
✅ 080_incorrect → scroll
✅ 081_correct → scroll
✅ 081_incorrect → scroll
✅ 082_correct → scroll
✅ 082_incorrect → scroll
✅ 083_correct → scroll
✅ 083_incorrect → scroll
✅ 084_correct → like
✅ 084_incorrect → scroll
✅ 085_correct → scroll
✅ 085_incorrect → scroll
✅ 086_correct → scroll
✅ 086_incorrect → scroll
✅ 087_correct → scroll
✅ 087_incorrect → scroll
✅ 088_correct → scroll
✅ 088_incorrect → scroll
✅ 089_correct → scroll
✅ 089_incorrect → scroll
✅ 090_correct → scroll
✅ 090_incorrect → scroll
✅ 091_correct → scroll
✅ 091_incorrect → scroll
✅ 092_correct → scroll
✅ 092_incorrect → scroll
✅ 093_correct → scroll
✅ 093_incorrect → scroll
✅ 094_correct → like
✅ 094_incorrect → scroll
✅ 095_correct → scroll
✅ 095_incorrect → scroll
✅ 096_correct → scroll
✅ 096_incorrect → scroll
✅ 097_correct → like
✅ 097_incorrect → scroll
✅ 098_correct → scroll
✅ 098_incorrect → scroll
✅ 099_correct → scroll
✅ 099_incorrect → scroll
✅ 100_correct → scroll
✅ 100_incorrect → scroll

✅ Done. Results saved to /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_results_baseline.json

In [10]:
# Approach 1
# single like/scroll
analyse_single(OUTPUT_DIR, "e1_results_baseline.json", like_answer="like")

============================================================
Single image analysis: e1_results_baseline
============================================================
=== Summary ===

                  metric  value
0    overall_like_rate_%    4.0
1    like_rate_correct_%    8.0
2  like_rate_incorrect_%    0.0

=== Per Image Results ===

,image,variant,prompt,answer
0,001_correct,correct,You are shown a social media post.\nYou can ei...,scroll
1,001_incorrect,incorrect,You are shown a social media post.\nYou can ei...,scroll
2,002_correct,correct,You are shown a social media post.\nYou can ei...,scroll
3,002_incorrect,incorrect,You are shown a social media post.\nYou can ei...,scroll
4,003_correct,correct,You are shown a social media post.\nYou can ei...,scroll
...,...,...,...,...
195,098_incorrect,incorrect,You are shown a social media post.\nYou can ei...,scroll
196,099_correct,correct,You are shown a social media post.\nYou can ei...,scroll
197,099_incorrect,incorrect,You are shown a social media post.\nYou can ei...,scroll
198,100_correct,correct,You are shown a social media post.\nYou can ei...,scroll
199,100_incorrect,incorrect,You are shown a social media post.\nYou can ei...,scroll

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_analysis_baseline.csv

## Approach 1: YES/NO variant

In [11]:
run_e1_baseline(all_images, model, processor, device, OUTPUT_DIR,
              prompt=LIKE_PROMPT_YESNO, output_filename="e1_results_baseline_yesno.json",inference_fn=run_inference_qwen)

✅ 001_correct → no
✅ 001_incorrect → no
✅ 002_correct → no
✅ 002_incorrect → no
✅ 003_correct → no
✅ 003_incorrect → no
✅ 004_correct → yes
✅ 004_incorrect → no
✅ 005_correct → yes
✅ 005_incorrect → no
✅ 006_correct → yes
✅ 006_incorrect → no
✅ 007_correct → yes
✅ 007_incorrect → no
✅ 008_correct → yes
✅ 008_incorrect → no
✅ 009_correct → yes
✅ 009_incorrect → no
✅ 010_correct → no
✅ 010_incorrect → no
✅ 011_correct → no
✅ 011_incorrect → no
✅ 012_correct → yes
✅ 012_incorrect → no
✅ 013_correct → yes
✅ 013_incorrect → no
✅ 014_correct → yes
✅ 014_incorrect → no
✅ 015_correct → no
✅ 015_incorrect → no
✅ 016_correct → no
✅ 016_incorrect → no
✅ 017_correct → no
✅ 017_incorrect → no
✅ 018_correct → yes
✅ 018_incorrect → no
✅ 019_correct → yes
✅ 019_incorrect → no
✅ 020_correct → yes
✅ 020_incorrect → no
✅ 021_correct → no
✅ 021_incorrect → no
✅ 022_correct → yes
✅ 022_incorrect → no
✅ 023_correct → no
✅ 023_incorrect → no
✅ 024_correct → no
✅ 024_incorrect → no
✅ 025_correct → yes
✅ 025_incorrect → no
✅ 026_correct → yes
✅ 026_incorrect → no
✅ 027_correct → no
✅ 027_incorrect → no
✅ 028_correct → yes
✅ 028_incorrect → no
✅ 029_correct → yes
✅ 029_incorrect → no
✅ 030_correct → yes
✅ 030_incorrect → no
✅ 031_correct → yes
✅ 031_incorrect → yes
✅ 032_correct → no
✅ 032_incorrect → no
✅ 033_correct → yes
✅ 033_incorrect → no
✅ 034_correct → no
✅ 034_incorrect → no
✅ 035_correct → yes
✅ 035_incorrect → no
✅ 036_correct → no
✅ 036_incorrect → no
✅ 037_correct → no
✅ 037_incorrect → no
✅ 038_correct → no
✅ 038_incorrect → no
✅ 039_correct → yes
✅ 039_incorrect → no
✅ 040_correct → yes
✅ 040_incorrect → no
✅ 041_correct → yes
✅ 041_incorrect → no
✅ 042_correct → yes
✅ 042_incorrect → no
✅ 043_correct → yes
✅ 043_incorrect → no
✅ 044_correct → no
✅ 044_incorrect → no
✅ 045_correct → yes
✅ 045_incorrect → no
✅ 046_correct → yes
✅ 046_incorrect → no
✅ 047_correct → yes
✅ 047_incorrect → no
✅ 048_correct → yes
✅ 048_incorrect → no
✅ 049_correct → yes
✅ 049_incorrect → no
✅ 050_correct → yes
✅ 050_incorrect → no
✅ 051_correct → yes
✅ 051_incorrect → no
✅ 052_correct → yes
✅ 052_incorrect → no
✅ 053_correct → no
✅ 053_incorrect → no
✅ 054_correct → no
✅ 054_incorrect → no
✅ 055_correct → yes
✅ 055_incorrect → no
✅ 056_correct → no
✅ 056_incorrect → no
✅ 057_correct → no
✅ 057_incorrect → no
✅ 058_correct → yes
✅ 058_incorrect → no
✅ 059_correct → no
✅ 059_incorrect → no
✅ 060_correct → yes
✅ 060_incorrect → no
✅ 061_correct → yes
✅ 061_incorrect → no
✅ 062_correct → yes
✅ 062_incorrect → no
✅ 063_correct → yes
✅ 063_incorrect → no
✅ 064_correct → yes
✅ 064_incorrect → no
✅ 065_correct → yes
✅ 065_incorrect → no
✅ 066_correct → yes
✅ 066_incorrect → no
✅ 067_correct → yes
✅ 067_incorrect → no
✅ 068_correct → yes
✅ 068_incorrect → no
✅ 069_correct → yes
✅ 069_incorrect → no
✅ 070_correct → yes
✅ 070_incorrect → no
✅ 071_correct → yes
✅ 071_incorrect → no
✅ 072_correct → yes
✅ 072_incorrect → no
✅ 073_correct → yes
✅ 073_incorrect → no
✅ 074_correct → yes
✅ 074_incorrect → no
✅ 075_correct → yes
✅ 075_incorrect → no
✅ 076_correct → no
✅ 076_incorrect → no
✅ 077_correct → no
✅ 077_incorrect → no
✅ 078_correct → yes
✅ 078_incorrect → no
✅ 079_correct → no
✅ 079_incorrect → no
✅ 080_correct → yes
✅ 080_incorrect → no
✅ 081_correct → yes
✅ 081_incorrect → no
✅ 082_correct → yes
✅ 082_incorrect → no
✅ 083_correct → yes
✅ 083_incorrect → no
✅ 084_correct → yes
✅ 084_incorrect → no
✅ 085_correct → yes
✅ 085_incorrect → no
✅ 086_correct → yes
✅ 086_incorrect → no
✅ 087_correct → yes
✅ 087_incorrect → no
✅ 088_correct → yes
✅ 088_incorrect → no
✅ 089_correct → yes
✅ 089_incorrect → no
✅ 090_correct → yes
✅ 090_incorrect → no
✅ 091_correct → no
✅ 091_incorrect → no
✅ 092_correct → no
✅ 092_incorrect → no
✅ 093_correct → yes
✅ 093_incorrect → no
✅ 094_correct → yes
✅ 094_incorrect → no
✅ 095_correct → yes
✅ 095_incorrect → no
✅ 096_correct → no
✅ 096_incorrect → no
✅ 097_correct → yes
✅ 097_incorrect → no
✅ 098_correct → yes
✅ 098_incorrect → no
✅ 099_correct → yes
✅ 099_incorrect → no
✅ 100_correct → no
✅ 100_incorrect → no

✅ Done. Results saved to /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_results_baseline_yesno.json

In [12]:
analyse_single(OUTPUT_DIR, "e1_results_baseline_yesno.json", like_answer="yes")

============================================================
Single image analysis: e1_results_baseline_yesno
============================================================
=== Summary ===

                 metric  value
0    overall_yes_rate_%   35.5
1    yes_rate_correct_%   70.0
2  yes_rate_incorrect_%    1.0

=== Per Image Results ===

,image,variant,prompt,answer
0,001_correct,correct,You are shown a social media post.\nYou can ei...,no
1,001_incorrect,incorrect,You are shown a social media post.\nYou can ei...,no
2,002_correct,correct,You are shown a social media post.\nYou can ei...,no
3,002_incorrect,incorrect,You are shown a social media post.\nYou can ei...,no
4,003_correct,correct,You are shown a social media post.\nYou can ei...,no
...,...,...,...,...
195,098_incorrect,incorrect,You are shown a social media post.\nYou can ei...,no
196,099_correct,correct,You are shown a social media post.\nYou can ei...,yes
197,099_incorrect,incorrect,You are shown a social media post.\nYou can ei...,no
198,100_correct,correct,You are shown a social media post.\nYou can ei...,no
199,100_incorrect,incorrect,You are shown a social media post.\nYou can ei...,no

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_analysis_baseline_yesno.csv

## Approach 2: A/B testing - paired images

In [13]:
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

In [14]:
print(f"\n{'='*60}\nApproach 2: paired A/B\n{'='*60}")

run_e1_baseline_paired(selected_numbers, correct_dir, incorrect_dir, model, processor, device, OUTPUT_DIR, SEED,
              prompt=LIKE_PROMPT_PAIR, output_filename="e1_results_baseline_paired.json", inference_fn=run_inference_qwen)

============================================================
Approach 2: paired A/B
============================================================
✅ Pair 001 → liked incorrect (answered B)
✅ Pair 002 → liked incorrect (answered B)
✅ Pair 003 → liked incorrect (answered B)
✅ Pair 004 → liked correct (answered B)
✅ Pair 005 → liked incorrect (answered B)
✅ Pair 006 → liked correct (answered B)
✅ Pair 007 → liked incorrect (answered B)
✅ Pair 008 → liked incorrect (answered B)
✅ Pair 009 → liked incorrect (answered B)
✅ Pair 010 → liked correct (answered B)
✅ Pair 011 → liked correct (answered B)
✅ Pair 012 → liked correct (answered B)
✅ Pair 013 → liked incorrect (answered B)
✅ Pair 014 → liked correct (answered B)
✅ Pair 015 → liked incorrect (answered B)
✅ Pair 016 → liked correct (answered B)
✅ Pair 017 → liked incorrect (answered B)
✅ Pair 018 → liked incorrect (answered B)
✅ Pair 019 → liked incorrect (answered B)
✅ Pair 020 → liked correct (answered B)
✅ Pair 021 → liked correct (answered A)
✅ Pair 022 → liked incorrect (answered B)
✅ Pair 023 → liked incorrect (answered B)
✅ Pair 024 → liked incorrect (answered B)
✅ Pair 025 → liked incorrect (answered B)
✅ Pair 026 → liked correct (answered B)
✅ Pair 027 → liked correct (answered B)
✅ Pair 028 → liked correct (answered B)
✅ Pair 029 → liked incorrect (answered B)
✅ Pair 030 → liked incorrect (answered B)
✅ Pair 031 → liked incorrect (answered B)
✅ Pair 032 → liked correct (answered B)
✅ Pair 033 → liked incorrect (answered B)
✅ Pair 034 → liked incorrect (answered B)
✅ Pair 035 → liked correct (answered B)
✅ Pair 036 → liked correct (answered B)
✅ Pair 037 → liked incorrect (answered B)
✅ Pair 038 → liked incorrect (answered B)
✅ Pair 039 → liked correct (answered B)
✅ Pair 040 → liked incorrect (answered B)
✅ Pair 041 → liked incorrect (answered B)
✅ Pair 042 → liked correct (answered B)
✅ Pair 043 → liked incorrect (answered B)
✅ Pair 044 → liked correct (answered B)
✅ Pair 045 → liked incorrect (answered B)
✅ Pair 046 → liked incorrect (answered B)
✅ Pair 047 → liked incorrect (answered B)
✅ Pair 048 → liked incorrect (answered B)
✅ Pair 049 → liked incorrect (answered B)
✅ Pair 050 → liked incorrect (answered B)
✅ Pair 051 → liked correct (answered B)
✅ Pair 052 → liked correct (answered B)
✅ Pair 053 → liked correct (answered B)
✅ Pair 054 → liked incorrect (answered B)
✅ Pair 055 → liked incorrect (answered B)
✅ Pair 056 → liked correct (answered A)
✅ Pair 057 → liked incorrect (answered B)
✅ Pair 058 → liked incorrect (answered B)
✅ Pair 059 → liked correct (answered B)
✅ Pair 060 → liked incorrect (answered B)
✅ Pair 061 → liked correct (answered B)
✅ Pair 062 → liked correct (answered B)
✅ Pair 063 → liked correct (answered B)
✅ Pair 064 → liked correct (answered B)
✅ Pair 065 → liked incorrect (answered B)
✅ Pair 066 → liked incorrect (answered B)
✅ Pair 067 → liked incorrect (answered B)
✅ Pair 068 → liked correct (answered B)
✅ Pair 069 → liked correct (answered B)
✅ Pair 070 → liked incorrect (answered B)
✅ Pair 071 → liked incorrect (answered B)
✅ Pair 072 → liked incorrect (answered B)
✅ Pair 073 → liked correct (answered B)
✅ Pair 074 → liked correct (answered B)
✅ Pair 075 → liked incorrect (answered B)
✅ Pair 076 → liked correct (answered B)
✅ Pair 077 → liked correct (answered B)
✅ Pair 078 → liked correct (answered B)
✅ Pair 079 → liked incorrect (answered B)
✅ Pair 080 → liked correct (answered B)
✅ Pair 081 → liked incorrect (answered B)
✅ Pair 082 → liked correct (answered B)
✅ Pair 083 → liked correct (answered B)
✅ Pair 084 → liked correct (answered B)
✅ Pair 085 → liked incorrect (answered B)
✅ Pair 086 → liked correct (answered B)
✅ Pair 087 → liked correct (answered B)
✅ Pair 088 → liked correct (answered B)
✅ Pair 089 → liked incorrect (answered B)
✅ Pair 090 → liked incorrect (answered B)
✅ Pair 091 → liked incorrect (answered B)
✅ Pair 092 → liked incorrect (answered B)
✅ Pair 093 → liked correct (answered B)
✅ Pair 094 → liked correct (answered B)
✅ Pair 095 → liked incorrect (answered B)
✅ Pair 096 → liked incorrect (answered B)
✅ Pair 097 → liked incorrect (answered B)
✅ Pair 098 → liked correct (answered B)
✅ Pair 099 → liked correct (answered B)
✅ Pair 100 → liked correct (answered B)

✅ Paired approach done. Results saved to /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_results_baseline_paired.json

In [15]:
analyse_paired(OUTPUT_DIR, "e1_results_baseline_paired.json")

============================================================
Paired A/B analysis: e1_results_baseline_paired
============================================================
=== Summary ===

              metric  value
0    liked_correct_%   46.0
1  liked_incorrect_%   54.0
2   invalid_answer_%    0.0

=== Per Pair Results ===

,num,post_a_variant,post_b_variant,prompt,answer,liked_variant
0,001,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect
1,002,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect
2,003,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect
3,004,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct
4,005,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect
...,...,...,...,...,...,...
95,096,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect
96,097,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect
97,098,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct
98,099,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct
99,100,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_analysis_baseline_paired.csv

# Likes only - Gender neutral user

In [16]:
"""
import os
os.chdir('/home/jovyan/conformity-llms-facebook-posts/benchmarking')
!unzip correct/remy-ashford/correct_likes_only.zip -d correct/remy-ashford/metrics/likes_only
!unzip incorrect/remy-ashford/incorrect_likes_only.zip -d incorrect/remy-ashford/metrics/likes_only
"""

"\nimport os\nos.chdir('/home/jovyan/conformity-llms-facebook-posts/benchmarking')\n!unzip correct/remy-ashford/correct_likes_only.zip -d correct/remy-ashford/metrics/likes_only\n!unzip incorrect/remy-ashford/incorrect_likes_only.zip -d incorrect/remy-ashford/metrics/likes_only\n"

## Approach 1: like or scroll - single image

In [17]:
'''
correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/likes_only"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

run_e1_metrics(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR,
               prompt=LIKE_PROMPT_SINGLE, output_filename="e1_results_likes_only.json", inference_fn=run_inference_qwen)
'''

'\ncorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only"\nincorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/likes_only"\nselected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]\n\nrun_e1_metrics(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR,\n               prompt=LIKE_PROMPT_SINGLE, output_filename="e1_results_likes_only.json", inference_fn=run_inference_qwen)\n'

In [18]:
# metrics like/scroll
#analyse_metrics_single(OUTPUT_DIR, "e1_results_likes_only.json", like_answer="like")

## Approach 1: YES/NO variant

In [19]:
'''
correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/likes_only"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

run_e1_metrics(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR,
               prompt=LIKE_PROMPT_YESNO, output_filename="e1_results_likes_only_yesno.json", inference_fn=run_inference_qwen)
'''

'\ncorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only"\nincorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/likes_only"\nselected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]\n\nrun_e1_metrics(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR,\n               prompt=LIKE_PROMPT_YESNO, output_filename="e1_results_likes_only_yesno.json", inference_fn=run_inference_qwen)\n'

In [20]:
# metrics yes/no
#analyse_metrics_single(OUTPUT_DIR, "e1_results_likes_only_yesno.json", like_answer="yes")

## Approach 2: A/B testing - paired images

In [21]:
'''
import time
import importlib
import e1_utils.e1_optimized as e1
importlib.reload(e1)
from e1_utils.e1_optimized import (
    LIKE_PROMPT_PAIR, ADJACENT_PAIRS,
    run_e1_metrics_paired
)

start = time.time()

correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/likes_only"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

run_e1_metrics_paired(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR, SEED,
                      prompt=LIKE_PROMPT_PAIR, output_filename="e1_results_likes_only_paired.json", inference_fn=run_inference_qwen,
                      baseline_correct_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs",
                      baseline_incorrect_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/incorrect/PNGs")

end = time.time()
elapsed = end - start
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)
print(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")
print(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")
'''

'\nimport time\nimport importlib\nimport e1_utils.e1_optimized as e1\nimportlib.reload(e1)\nfrom e1_utils.e1_optimized import (\n    LIKE_PROMPT_PAIR, ADJACENT_PAIRS,\n    run_e1_metrics_paired\n)\n\nstart = time.time()\n\ncorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only"\nincorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/likes_only"\nselected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]\n\nrun_e1_metrics_paired(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR, SEED,\n                      prompt=LIKE_PROMPT_PAIR, output_filename="e1_results_likes_only_paired.json", inference_fn=run_inference_qwen,\n                      baseline_correct_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs",\n                      baseline_incorrect_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/incorrect/PNGs")\n\nend = time.time()\nelapsed = end - start\nhours = int(elapsed // 3600)\nminutes = int((elapsed % 3600) // 60)\nseconds = int(elapsed % 60)\nprint(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")\nprint(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")\n'

In [22]:
'''
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)
print(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")
print(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")
'''

'\nhours = int(elapsed // 3600)\nminutes = int((elapsed % 3600) // 60)\nseconds = int(elapsed % 60)\nprint(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")\nprint(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")\n'

In [23]:
#analyse_metrics_paired(OUTPUT_DIR, "e1_results_likes_only_paired.json")

# Metrics - single image - like/scroll

In [24]:
# --- Approach 1 on metrics folders ---
print(f"\n{'='*60}\nApproach 1 on metrics: like/scroll\n{'='*60}")
correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/realistic"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/realistic"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

run_e1_metrics(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR,
               prompt=LIKE_PROMPT_SINGLE, output_filename="e1_results_metrics.json",  inference_fn=run_inference_qwen)

============================================================
Approach 1 on metrics: like/scroll
============================================================
✅ 001_correct_10 → scroll
✅ 001_incorrect_10 → scroll
✅ 002_correct_10 → scroll
✅ 002_incorrect_10 → scroll
✅ 003_correct_10 → scroll
✅ 003_incorrect_10 → scroll
✅ 004_correct_10 → like
✅ 004_incorrect_10 → scroll
✅ 005_correct_10 → scroll
✅ 005_incorrect_10 → scroll
✅ 006_correct_10 → scroll
✅ 006_incorrect_10 → scroll
✅ 007_correct_10 → like
✅ 007_incorrect_10 → scroll
✅ 008_correct_10 → scroll
✅ 008_incorrect_10 → scroll
✅ 009_correct_10 → scroll
✅ 009_incorrect_10 → scroll
✅ 010_correct_10 → scroll
✅ 010_incorrect_10 → scroll
✅ 011_correct_10 → scroll
✅ 011_incorrect_10 → scroll
✅ 012_correct_10 → scroll
✅ 012_incorrect_10 → scroll
✅ 013_correct_10 → scroll
✅ 013_incorrect_10 → scroll
✅ 014_correct_10 → scroll
✅ 014_incorrect_10 → scroll
✅ 015_correct_10 → scroll
✅ 015_incorrect_10 → scroll
✅ 016_correct_10 → scroll
✅ 016_incorrect_10 → scroll
✅ 017_correct_10 → scroll
✅ 017_incorrect_10 → scroll
✅ 018_correct_10 → scroll
✅ 018_incorrect_10 → scroll
✅ 019_correct_10 → scroll
✅ 019_incorrect_10 → scroll
✅ 020_correct_10 → like
✅ 020_incorrect_10 → scroll
✅ 021_correct_10 → scroll
✅ 021_incorrect_10 → scroll
✅ 022_correct_10 → scroll
✅ 022_incorrect_10 → scroll
✅ 023_correct_10 → scroll
✅ 023_incorrect_10 → scroll
✅ 024_correct_10 → scroll
✅ 024_incorrect_10 → scroll
✅ 025_correct_10 → scroll
✅ 025_incorrect_10 → scroll
✅ 026_correct_10 → scroll
✅ 026_incorrect_10 → scroll
✅ 027_correct_10 → scroll
✅ 027_incorrect_10 → scroll
✅ 028_correct_10 → scroll
✅ 028_incorrect_10 → scroll
✅ 029_correct_10 → scroll
✅ 029_incorrect_10 → scroll
✅ 030_correct_10 → scroll
✅ 030_incorrect_10 → scroll
✅ 031_correct_10 → scroll
✅ 031_incorrect_10 → scroll
✅ 032_correct_10 → scroll
✅ 032_incorrect_10 → scroll
✅ 033_correct_10 → scroll
✅ 033_incorrect_10 → scroll
✅ 034_correct_10 → scroll
✅ 034_incorrect_10 → scroll
✅ 035_correct_10 → scroll
✅ 035_incorrect_10 → scroll
✅ 036_correct_10 → scroll
✅ 036_incorrect_10 → scroll
✅ 037_correct_10 → scroll
✅ 037_incorrect_10 → scroll
✅ 038_correct_10 → scroll
✅ 038_incorrect_10 → scroll
✅ 039_correct_10 → scroll
✅ 039_incorrect_10 → scroll
✅ 040_correct_10 → scroll
✅ 040_incorrect_10 → scroll
✅ 041_correct_10 → scroll
✅ 041_incorrect_10 → scroll
✅ 042_correct_10 → like
✅ 042_incorrect_10 → scroll
✅ 043_correct_10 → scroll
✅ 043_incorrect_10 → scroll
✅ 044_correct_10 → scroll
✅ 044_incorrect_10 → scroll
✅ 045_correct_10 → scroll
✅ 045_incorrect_10 → scroll
✅ 046_correct_10 → like
✅ 046_incorrect_10 → scroll
✅ 047_correct_10 → scroll
✅ 047_incorrect_10 → scroll
✅ 048_correct_10 → scroll
✅ 048_incorrect_10 → scroll
✅ 049_correct_10 → scroll
✅ 049_incorrect_10 → scroll
✅ 050_correct_10 → scroll
✅ 050_incorrect_10 → scroll
✅ 051_correct_10 → scroll
✅ 051_incorrect_10 → scroll
✅ 052_correct_10 → scroll
✅ 052_incorrect_10 → scroll
✅ 053_correct_10 → like
✅ 053_incorrect_10 → scroll
✅ 054_correct_10 → scroll
✅ 054_incorrect_10 → scroll
✅ 055_correct_10 → scroll
✅ 055_incorrect_10 → scroll
✅ 056_correct_10 → scroll
✅ 056_incorrect_10 → scroll
✅ 057_correct_10 → scroll
✅ 057_incorrect_10 → scroll
✅ 058_correct_10 → scroll
✅ 058_incorrect_10 → scroll
✅ 059_correct_10 → scroll
✅ 059_incorrect_10 → scroll
✅ 060_correct_10 → scroll
✅ 060_incorrect_10 → scroll
✅ 061_correct_10 → scroll
✅ 061_incorrect_10 → scroll
✅ 062_correct_10 → scroll
✅ 062_incorrect_10 → scroll
✅ 063_correct_10 → scroll
✅ 063_incorrect_10 → scroll
✅ 064_correct_10 → scroll
✅ 064_incorrect_10 → scroll
✅ 065_correct_10 → scroll
✅ 065_incorrect_10 → scroll
✅ 066_correct_10 → scroll
✅ 066_incorrect_10 → scroll
✅ 067_correct_10 → scroll
✅ 067_incorrect_10 → scroll
✅ 068_correct_10 → scroll
✅ 068_incorrect_10 → scroll
✅ 069_correct_10 → scroll
✅ 069_incorrect_10 → scroll
✅ 070_correct_10 → scroll
✅ 070_incorrect_10 → scroll
✅ 071_correct_10 → like
✅ 071_incorrect_10 → scroll
✅ 072_correct_10 → scroll
✅ 072_incorrect_10 → scroll
✅ 073_correct_10 → scroll
✅ 073_incorrect_10 → scroll
✅ 074_correct_10 → like
✅ 074_incorrect_10 → scroll
✅ 075_correct_10 → like
✅ 075_incorrect_10 → scroll
✅ 076_correct_10 → scroll
✅ 076_incorrect_10 → scroll
✅ 077_correct_10 → scroll
✅ 077_incorrect_10 → scroll
✅ 078_correct_10 → scroll
✅ 078_incorrect_10 → scroll
✅ 079_correct_10 → scroll
✅ 079_incorrect_10 → scroll
✅ 080_correct_10 → scroll
✅ 080_incorrect_10 → scroll
✅ 081_correct_10 → like
✅ 081_incorrect_10 → scroll
✅ 082_correct_10 → scroll
✅ 082_incorrect_10 → scroll
✅ 083_correct_10 → scroll
✅ 083_incorrect_10 → scroll
✅ 084_correct_10 → scroll
✅ 084_incorrect_10 → scroll
✅ 085_correct_10 → scroll
✅ 085_incorrect_10 → scroll
✅ 086_correct_10 → like
✅ 086_incorrect_10 → scroll
✅ 087_correct_10 → scroll
✅ 087_incorrect_10 → scroll
✅ 088_correct_10 → scroll
✅ 088_incorrect_10 → scroll
✅ 089_correct_10 → scroll
✅ 089_incorrect_10 → scroll
✅ 090_correct_10 → scroll
✅ 090_incorrect_10 → scroll
✅ 091_correct_10 → scroll
✅ 091_incorrect_10 → scroll
✅ 092_correct_10 → scroll
✅ 092_incorrect_10 → scroll
✅ 093_correct_10 → scroll
✅ 093_incorrect_10 → scroll
✅ 094_correct_10 → like
✅ 094_incorrect_10 → scroll
✅ 095_correct_10 → scroll
✅ 095_incorrect_10 → scroll
✅ 096_correct_10 → like
✅ 096_incorrect_10 → scroll
✅ 097_correct_10 → scroll
✅ 097_incorrect_10 → scroll
✅ 098_correct_10 → scroll
✅ 098_incorrect_10 → scroll
✅ 099_correct_10 → scroll
✅ 099_incorrect_10 → scroll
✅ 100_correct_10 → like
✅ 100_incorrect_10 → scroll
✅ 001_correct_100 → scroll
✅ 001_incorrect_100 → scroll
✅ 002_correct_100 → scroll
✅ 002_incorrect_100 → scroll
✅ 003_correct_100 → scroll
✅ 003_incorrect_100 → scroll
✅ 004_correct_100 → like
✅ 004_incorrect_100 → scroll
✅ 005_correct_100 → like
✅ 005_incorrect_100 → scroll
✅ 006_correct_100 → scroll
✅ 006_incorrect_100 → scroll
✅ 007_correct_100 → like
✅ 007_incorrect_100 → scroll
✅ 008_correct_100 → scroll
✅ 008_incorrect_100 → scroll
✅ 009_correct_100 → scroll
✅ 009_incorrect_100 → scroll
✅ 010_correct_100 → like
✅ 010_incorrect_100 → scroll
✅ 011_correct_100 → like
✅ 011_incorrect_100 → scroll
✅ 012_correct_100 → scroll
✅ 012_incorrect_100 → scroll
✅ 013_correct_100 → like
✅ 013_incorrect_100 → scroll
✅ 014_correct_100 → scroll
✅ 014_incorrect_100 → scroll
✅ 015_correct_100 → scroll
✅ 015_incorrect_100 → scroll
✅ 016_correct_100 → scroll
✅ 016_incorrect_100 → scroll
✅ 017_correct_100 → like
✅ 017_incorrect_100 → scroll
✅ 018_correct_100 → scroll
✅ 018_incorrect_100 → scroll
✅ 019_correct_100 → scroll
✅ 019_incorrect_100 → scroll
✅ 020_correct_100 → like
✅ 020_incorrect_100 → scroll
✅ 021_correct_100 → scroll
✅ 021_incorrect_100 → scroll
✅ 022_correct_100 → scroll
✅ 022_incorrect_100 → scroll
✅ 023_correct_100 → scroll
✅ 023_incorrect_100 → scroll
✅ 024_correct_100 → scroll
✅ 024_incorrect_100 → scroll
✅ 025_correct_100 → scroll
✅ 025_incorrect_100 → scroll
✅ 026_correct_100 → like
✅ 026_incorrect_100 → scroll
✅ 027_correct_100 → like
✅ 027_incorrect_100 → scroll
✅ 028_correct_100 → like
✅ 028_incorrect_100 → scroll
✅ 029_correct_100 → scroll
✅ 029_incorrect_100 → scroll
✅ 030_correct_100 → like
✅ 030_incorrect_100 → scroll
✅ 031_correct_100 → like
✅ 031_incorrect_100 → scroll
✅ 032_correct_100 → scroll
✅ 032_incorrect_100 → scroll
✅ 033_correct_100 → scroll
✅ 033_incorrect_100 → scroll
✅ 034_correct_100 → scroll
✅ 034_incorrect_100 → scroll
✅ 035_correct_100 → scroll
✅ 035_incorrect_100 → scroll
✅ 036_correct_100 → scroll
✅ 036_incorrect_100 → scroll
✅ 037_correct_100 → like
✅ 037_incorrect_100 → scroll
✅ 038_correct_100 → scroll
✅ 038_incorrect_100 → scroll
✅ 039_correct_100 → scroll
✅ 039_incorrect_100 → scroll
✅ 040_correct_100 → scroll
✅ 040_incorrect_100 → scroll
✅ 041_correct_100 → scroll
✅ 041_incorrect_100 → scroll
✅ 042_correct_100 → like
✅ 042_incorrect_100 → scroll
✅ 043_correct_100 → scroll
✅ 043_incorrect_100 → scroll
✅ 044_correct_100 → scroll
✅ 044_incorrect_100 → scroll
✅ 045_correct_100 → scroll
✅ 045_incorrect_100 → scroll
✅ 046_correct_100 → like
✅ 046_incorrect_100 → scroll
✅ 047_correct_100 → scroll
✅ 047_incorrect_100 → scroll
✅ 048_correct_100 → scroll
✅ 048_incorrect_100 → scroll
✅ 049_correct_100 → scroll
✅ 049_incorrect_100 → scroll
✅ 050_correct_100 → like
✅ 050_incorrect_100 → scroll
✅ 051_correct_100 → scroll
✅ 051_incorrect_100 → scroll
✅ 052_correct_100 → scroll
✅ 052_incorrect_100 → scroll
✅ 053_correct_100 → like
✅ 053_incorrect_100 → scroll
✅ 054_correct_100 → scroll
✅ 054_incorrect_100 → scroll
✅ 055_correct_100 → scroll
✅ 055_incorrect_100 → scroll
✅ 056_correct_100 → scroll
✅ 056_incorrect_100 → scroll
✅ 057_correct_100 → scroll
✅ 057_incorrect_100 → scroll
✅ 058_correct_100 → scroll
✅ 058_incorrect_100 → scroll
✅ 059_correct_100 → scroll
✅ 059_incorrect_100 → scroll
✅ 060_correct_100 → scroll
✅ 060_incorrect_100 → scroll
✅ 061_correct_100 → like
✅ 061_incorrect_100 → scroll
✅ 062_correct_100 → like
✅ 062_incorrect_100 → scroll
✅ 063_correct_100 → scroll
✅ 063_incorrect_100 → scroll
✅ 064_correct_100 → scroll
✅ 064_incorrect_100 → scroll
✅ 065_correct_100 → scroll
✅ 065_incorrect_100 → scroll
✅ 066_correct_100 → like
✅ 066_incorrect_100 → scroll
✅ 067_correct_100 → scroll
✅ 067_incorrect_100 → scroll
✅ 068_correct_100 → like
✅ 068_incorrect_100 → scroll
✅ 069_correct_100 → scroll
✅ 069_incorrect_100 → scroll
✅ 070_correct_100 → scroll
✅ 070_incorrect_100 → scroll
✅ 071_correct_100 → like
✅ 071_incorrect_100 → scroll
✅ 072_correct_100 → scroll
✅ 072_incorrect_100 → scroll
✅ 073_correct_100 → like
✅ 073_incorrect_100 → scroll
✅ 074_correct_100 → like
✅ 074_incorrect_100 → scroll
✅ 075_correct_100 → like
✅ 075_incorrect_100 → scroll
✅ 076_correct_100 → scroll
✅ 076_incorrect_100 → scroll
✅ 077_correct_100 → scroll
✅ 077_incorrect_100 → scroll
✅ 078_correct_100 → scroll
✅ 078_incorrect_100 → scroll
✅ 079_correct_100 → scroll
✅ 079_incorrect_100 → scroll
✅ 080_correct_100 → scroll
✅ 080_incorrect_100 → scroll
✅ 081_correct_100 → scroll
✅ 081_incorrect_100 → scroll
✅ 082_correct_100 → scroll
✅ 082_incorrect_100 → scroll
✅ 083_correct_100 → scroll
✅ 083_incorrect_100 → scroll
✅ 084_correct_100 → like
✅ 084_incorrect_100 → scroll
✅ 085_correct_100 → scroll
✅ 085_incorrect_100 → scroll
✅ 086_correct_100 → scroll
✅ 086_incorrect_100 → scroll
✅ 087_correct_100 → scroll
✅ 087_incorrect_100 → scroll
✅ 088_correct_100 → scroll
✅ 088_incorrect_100 → scroll
✅ 089_correct_100 → scroll
✅ 089_incorrect_100 → scroll
✅ 090_correct_100 → like
✅ 090_incorrect_100 → scroll
✅ 091_correct_100 → scroll
✅ 091_incorrect_100 → scroll
✅ 092_correct_100 → scroll
✅ 092_incorrect_100 → scroll
✅ 093_correct_100 → scroll
✅ 093_incorrect_100 → scroll
✅ 094_correct_100 → like
✅ 094_incorrect_100 → scroll
✅ 095_correct_100 → scroll
✅ 095_incorrect_100 → like
✅ 096_correct_100 → like
✅ 096_incorrect_100 → scroll
✅ 097_correct_100 → like
✅ 097_incorrect_100 → scroll
✅ 098_correct_100 → scroll
✅ 098_incorrect_100 → scroll
✅ 099_correct_100 → like
✅ 099_incorrect_100 → scroll
✅ 100_correct_100 → like
✅ 100_incorrect_100 → scroll
✅ 001_correct_1000 → scroll
✅ 001_incorrect_1000 → scroll
✅ 002_correct_1000 → scroll
✅ 002_incorrect_1000 → scroll
✅ 003_correct_1000 → scroll
✅ 003_incorrect_1000 → scroll
✅ 004_correct_1000 → like
✅ 004_incorrect_1000 → scroll
✅ 005_correct_1000 → scroll
✅ 005_incorrect_1000 → scroll
✅ 006_correct_1000 → scroll
✅ 006_incorrect_1000 → scroll
✅ 007_correct_1000 → like
✅ 007_incorrect_1000 → scroll
✅ 008_correct_1000 → scroll
✅ 008_incorrect_1000 → scroll
✅ 009_correct_1000 → scroll
✅ 009_incorrect_1000 → scroll
✅ 010_correct_1000 → scroll
✅ 010_incorrect_1000 → scroll
✅ 011_correct_1000 → like
✅ 011_incorrect_1000 → scroll
✅ 012_correct_1000 → scroll
✅ 012_incorrect_1000 → scroll
✅ 013_correct_1000 → like
✅ 013_incorrect_1000 → scroll
✅ 014_correct_1000 → scroll
✅ 014_incorrect_1000 → scroll
✅ 015_correct_1000 → scroll
✅ 015_incorrect_1000 → scroll
✅ 016_correct_1000 → scroll
✅ 016_incorrect_1000 → scroll
✅ 017_correct_1000 → like
✅ 017_incorrect_1000 → scroll
✅ 018_correct_1000 → scroll
✅ 018_incorrect_1000 → scroll
✅ 019_correct_1000 → scroll
✅ 019_incorrect_1000 → scroll
✅ 020_correct_1000 → like
✅ 020_incorrect_1000 → scroll
✅ 021_correct_1000 → scroll
✅ 021_incorrect_1000 → scroll
✅ 022_correct_1000 → scroll
✅ 022_incorrect_1000 → scroll
✅ 023_correct_1000 → scroll
✅ 023_incorrect_1000 → scroll
✅ 024_correct_1000 → scroll
✅ 024_incorrect_1000 → scroll
✅ 025_correct_1000 → like
✅ 025_incorrect_1000 → scroll
✅ 026_correct_1000 → like
✅ 026_incorrect_1000 → scroll
✅ 027_correct_1000 → scroll
✅ 027_incorrect_1000 → scroll
✅ 028_correct_1000 → scroll
✅ 028_incorrect_1000 → scroll
✅ 029_correct_1000 → scroll
✅ 029_incorrect_1000 → scroll
✅ 030_correct_1000 → like
✅ 030_incorrect_1000 → scroll
✅ 031_correct_1000 → scroll
✅ 031_incorrect_1000 → scroll
✅ 032_correct_1000 → scroll
✅ 032_incorrect_1000 → scroll
✅ 033_correct_1000 → like
✅ 033_incorrect_1000 → scroll
✅ 034_correct_1000 → scroll
✅ 034_incorrect_1000 → scroll
✅ 035_correct_1000 → scroll
✅ 035_incorrect_1000 → scroll
✅ 036_correct_1000 → scroll
✅ 036_incorrect_1000 → scroll
✅ 037_correct_1000 → like
✅ 037_incorrect_1000 → scroll
✅ 038_correct_1000 → scroll
✅ 038_incorrect_1000 → scroll
✅ 039_correct_1000 → scroll
✅ 039_incorrect_1000 → scroll
✅ 040_correct_1000 → like
✅ 040_incorrect_1000 → scroll
✅ 041_correct_1000 → scroll
✅ 041_incorrect_1000 → scroll
✅ 042_correct_1000 → scroll
✅ 042_incorrect_1000 → scroll
✅ 043_correct_1000 → scroll
✅ 043_incorrect_1000 → scroll
✅ 044_correct_1000 → scroll
✅ 044_incorrect_1000 → scroll
✅ 045_correct_1000 → scroll
✅ 045_incorrect_1000 → scroll
✅ 046_correct_1000 → scroll
✅ 046_incorrect_1000 → scroll
✅ 047_correct_1000 → scroll
✅ 047_incorrect_1000 → scroll
✅ 048_correct_1000 → like
✅ 048_incorrect_1000 → scroll
✅ 049_correct_1000 → scroll
✅ 049_incorrect_1000 → scroll
✅ 050_correct_1000 → like
✅ 050_incorrect_1000 → scroll
✅ 051_correct_1000 → scroll
✅ 051_incorrect_1000 → scroll
✅ 052_correct_1000 → scroll
✅ 052_incorrect_1000 → scroll
✅ 053_correct_1000 → scroll
✅ 053_incorrect_1000 → scroll
✅ 054_correct_1000 → scroll
✅ 054_incorrect_1000 → scroll
✅ 055_correct_1000 → scroll
✅ 055_incorrect_1000 → scroll
✅ 056_correct_1000 → scroll
✅ 056_incorrect_1000 → scroll
✅ 057_correct_1000 → scroll
✅ 057_incorrect_1000 → scroll
✅ 058_correct_1000 → like
✅ 058_incorrect_1000 → scroll
✅ 059_correct_1000 → scroll
✅ 059_incorrect_1000 → scroll
✅ 060_correct_1000 → scroll
✅ 060_incorrect_1000 → scroll
✅ 061_correct_1000 → like
✅ 061_incorrect_1000 → scroll
✅ 062_correct_1000 → scroll
✅ 062_incorrect_1000 → scroll
✅ 063_correct_1000 → like
✅ 063_incorrect_1000 → scroll
✅ 064_correct_1000 → scroll
✅ 064_incorrect_1000 → scroll
✅ 065_correct_1000 → scroll
✅ 065_incorrect_1000 → scroll
✅ 066_correct_1000 → scroll
✅ 066_incorrect_1000 → scroll
✅ 067_correct_1000 → scroll
✅ 067_incorrect_1000 → scroll
✅ 068_correct_1000 → like
✅ 068_incorrect_1000 → scroll
✅ 069_correct_1000 → scroll
✅ 069_incorrect_1000 → scroll
✅ 070_correct_1000 → like
✅ 070_incorrect_1000 → scroll
✅ 071_correct_1000 → like
✅ 071_incorrect_1000 → scroll
✅ 072_correct_1000 → scroll
✅ 072_incorrect_1000 → scroll
✅ 073_correct_1000 → scroll
✅ 073_incorrect_1000 → scroll
✅ 074_correct_1000 → scroll
✅ 074_incorrect_1000 → scroll
✅ 075_correct_1000 → like
✅ 075_incorrect_1000 → scroll
✅ 076_correct_1000 → scroll
✅ 076_incorrect_1000 → scroll
✅ 077_correct_1000 → scroll
✅ 077_incorrect_1000 → scroll
✅ 078_correct_1000 → scroll
✅ 078_incorrect_1000 → scroll
✅ 079_correct_1000 → scroll
✅ 079_incorrect_1000 → scroll
✅ 080_correct_1000 → like
✅ 080_incorrect_1000 → scroll
✅ 081_correct_1000 → like
✅ 081_incorrect_1000 → scroll
✅ 082_correct_1000 → scroll
✅ 082_incorrect_1000 → scroll
✅ 083_correct_1000 → scroll
✅ 083_incorrect_1000 → scroll
✅ 084_correct_1000 → like
✅ 084_incorrect_1000 → scroll
✅ 085_correct_1000 → scroll
✅ 085_incorrect_1000 → scroll
✅ 086_correct_1000 → scroll
✅ 086_incorrect_1000 → scroll
✅ 087_correct_1000 → scroll
✅ 087_incorrect_1000 → scroll
✅ 088_correct_1000 → scroll
✅ 088_incorrect_1000 → scroll
✅ 089_correct_1000 → scroll
✅ 089_incorrect_1000 → scroll
✅ 090_correct_1000 → scroll
✅ 090_incorrect_1000 → scroll
✅ 091_correct_1000 → scroll
✅ 091_incorrect_1000 → scroll
✅ 092_correct_1000 → scroll
✅ 092_incorrect_1000 → scroll
✅ 093_correct_1000 → scroll
✅ 093_incorrect_1000 → scroll
✅ 094_correct_1000 → like
✅ 094_incorrect_1000 → scroll
✅ 095_correct_1000 → scroll
✅ 095_incorrect_1000 → scroll
✅ 096_correct_1000 → scroll
✅ 096_incorrect_1000 → scroll
✅ 097_correct_1000 → scroll
✅ 097_incorrect_1000 → scroll
✅ 098_correct_1000 → scroll
✅ 098_incorrect_1000 → scroll
✅ 099_correct_1000 → scroll
✅ 099_incorrect_1000 → scroll
✅ 100_correct_1000 → scroll
✅ 100_incorrect_1000 → scroll
✅ 001_correct_10000 → scroll
✅ 001_incorrect_10000 → scroll
✅ 002_correct_10000 → scroll
✅ 002_incorrect_10000 → scroll
✅ 003_correct_10000 → like
✅ 003_incorrect_10000 → scroll
✅ 004_correct_10000 → like
✅ 004_incorrect_10000 → scroll
✅ 005_correct_10000 → like
✅ 005_incorrect_10000 → scroll
✅ 006_correct_10000 → scroll
✅ 006_incorrect_10000 → scroll
✅ 007_correct_10000 → like
✅ 007_incorrect_10000 → scroll
✅ 008_correct_10000 → like
✅ 008_incorrect_10000 → scroll
✅ 009_correct_10000 → scroll
✅ 009_incorrect_10000 → scroll
✅ 010_correct_10000 → like
✅ 010_incorrect_10000 → scroll
✅ 011_correct_10000 → like
✅ 011_incorrect_10000 → scroll
✅ 012_correct_10000 → scroll
✅ 012_incorrect_10000 → scroll
✅ 013_correct_10000 → scroll
✅ 013_incorrect_10000 → scroll
✅ 014_correct_10000 → scroll
✅ 014_incorrect_10000 → scroll
✅ 015_correct_10000 → scroll
✅ 015_incorrect_10000 → scroll
✅ 016_correct_10000 → scroll
✅ 016_incorrect_10000 → scroll
✅ 017_correct_10000 → like
✅ 017_incorrect_10000 → scroll
✅ 018_correct_10000 → scroll
✅ 018_incorrect_10000 → scroll
✅ 019_correct_10000 → like
✅ 019_incorrect_10000 → scroll
✅ 020_correct_10000 → like
✅ 020_incorrect_10000 → scroll
✅ 021_correct_10000 → scroll
✅ 021_incorrect_10000 → scroll
✅ 022_correct_10000 → scroll
✅ 022_incorrect_10000 → scroll
✅ 023_correct_10000 → scroll
✅ 023_incorrect_10000 → scroll
✅ 024_correct_10000 → scroll
✅ 024_incorrect_10000 → scroll
✅ 025_correct_10000 → scroll
✅ 025_incorrect_10000 → scroll
✅ 026_correct_10000 → like
✅ 026_incorrect_10000 → scroll
✅ 027_correct_10000 → scroll
✅ 027_incorrect_10000 → scroll
✅ 028_correct_10000 → scroll
✅ 028_incorrect_10000 → scroll
✅ 029_correct_10000 → like
✅ 029_incorrect_10000 → scroll
✅ 030_correct_10000 → like
✅ 030_incorrect_10000 → scroll
✅ 031_correct_10000 → scroll
✅ 031_incorrect_10000 → scroll
✅ 032_correct_10000 → scroll
✅ 032_incorrect_10000 → scroll
✅ 033_correct_10000 → like
✅ 033_incorrect_10000 → scroll
✅ 034_correct_10000 → like
✅ 034_incorrect_10000 → scroll
✅ 035_correct_10000 → scroll
✅ 035_incorrect_10000 → scroll
✅ 036_correct_10000 → scroll
✅ 036_incorrect_10000 → scroll
✅ 037_correct_10000 → like
✅ 037_incorrect_10000 → scroll
✅ 038_correct_10000 → scroll
✅ 038_incorrect_10000 → scroll
✅ 039_correct_10000 → scroll
✅ 039_incorrect_10000 → scroll
✅ 040_correct_10000 → scroll
✅ 040_incorrect_10000 → scroll
✅ 041_correct_10000 → scroll
✅ 041_incorrect_10000 → scroll
✅ 042_correct_10000 → like
✅ 042_incorrect_10000 → scroll
✅ 043_correct_10000 → scroll
✅ 043_incorrect_10000 → scroll
✅ 044_correct_10000 → scroll
✅ 044_incorrect_10000 → scroll
✅ 045_correct_10000 → like
✅ 045_incorrect_10000 → scroll
✅ 046_correct_10000 → scroll
✅ 046_incorrect_10000 → scroll
✅ 047_correct_10000 → scroll
✅ 047_incorrect_10000 → scroll
✅ 048_correct_10000 → like
✅ 048_incorrect_10000 → like
✅ 049_correct_10000 → scroll
✅ 049_incorrect_10000 → scroll
✅ 050_correct_10000 → like
✅ 050_incorrect_10000 → like
✅ 051_correct_10000 → scroll
✅ 051_incorrect_10000 → scroll
✅ 052_correct_10000 → scroll
✅ 052_incorrect_10000 → scroll
✅ 053_correct_10000 → like
✅ 053_incorrect_10000 → scroll
✅ 054_correct_10000 → scroll

In [25]:
# metrics like/scroll
analyse_metrics_single(OUTPUT_DIR, "e1_results_metrics.json", like_answer="like")

============================================================
Metrics single image analysis: e1_results_metrics
============================================================
=== Overall Summary ===

                  metric  value
0    overall_like_rate_%  17.42
1    like_rate_correct_%  32.83
2  like_rate_incorrect_%   2.00

=== Rate per Scale Value ===

/home/jovyan/conformity-llms-facebook-posts/experiments/e1/e1_utils/e1_analysis_optimized.py:116: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_scale = df.groupby("scale_value").apply(lambda g: pd.Series({

,scale_value,total_images,overall_like_rate_%,like_rate_correct_%,like_rate_incorrect_%
0,10,200.0,7.0,14.0,0.0
1,100,200.0,17.0,33.0,1.0
2,1000,200.0,12.5,25.0,0.0
3,10000,200.0,18.5,35.0,2.0
4,100000,200.0,19.5,39.0,0.0
5,1000000,200.0,30.0,51.0,9.0

=== Per Image Results ===

,image,num,variant,scale_value,prompt,answer
0,001_correct_10,001,correct,10,You are shown a social media post.\nYou can ei...,scroll
2,002_correct_10,002,correct,10,You are shown a social media post.\nYou can ei...,scroll
4,003_correct_10,003,correct,10,You are shown a social media post.\nYou can ei...,scroll
6,004_correct_10,004,correct,10,You are shown a social media post.\nYou can ei...,like
8,005_correct_10,005,correct,10,You are shown a social media post.\nYou can ei...,scroll
...,...,...,...,...,...,...
1191,096_incorrect_1000000,096,incorrect,1000000,You are shown a social media post.\nYou can ei...,scroll
1193,097_incorrect_1000000,097,incorrect,1000000,You are shown a social media post.\nYou can ei...,scroll
1195,098_incorrect_1000000,098,incorrect,1000000,You are shown a social media post.\nYou can ei...,scroll
1197,099_incorrect_1000000,099,incorrect,1000000,You are shown a social media post.\nYou can ei...,like
1199,100_incorrect_1000000,100,incorrect,1000000,You are shown a social media post.\nYou can ei...,scroll

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_analysis_metrics.csv

# Metrics - yes/no

In [26]:
correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/realistic"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/realistic"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

run_e1_metrics(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR,
               prompt=LIKE_PROMPT_YESNO, output_filename="e1_results_metrics_yesno.json",  inference_fn=run_inference_qwen)

✅ 001_correct_10 → yes
✅ 001_incorrect_10 → no
✅ 002_correct_10 → yes
✅ 002_incorrect_10 → no
✅ 003_correct_10 → yes
✅ 003_incorrect_10 → no
✅ 004_correct_10 → yes
✅ 004_incorrect_10 → no
✅ 005_correct_10 → yes
✅ 005_incorrect_10 → no
✅ 006_correct_10 → yes
✅ 006_incorrect_10 → no
✅ 007_correct_10 → yes
✅ 007_incorrect_10 → no
✅ 008_correct_10 → no
✅ 008_incorrect_10 → no
✅ 009_correct_10 → no
✅ 009_incorrect_10 → no
✅ 010_correct_10 → yes
✅ 010_incorrect_10 → no
✅ 011_correct_10 → yes
✅ 011_incorrect_10 → no
✅ 012_correct_10 → no
✅ 012_incorrect_10 → no
✅ 013_correct_10 → yes
✅ 013_incorrect_10 → no
✅ 014_correct_10 → no
✅ 014_incorrect_10 → no
✅ 015_correct_10 → yes
✅ 015_incorrect_10 → no
✅ 016_correct_10 → yes
✅ 016_incorrect_10 → no
✅ 017_correct_10 → yes
✅ 017_incorrect_10 → no
✅ 018_correct_10 → yes
✅ 018_incorrect_10 → no
✅ 019_correct_10 → yes
✅ 019_incorrect_10 → no
✅ 020_correct_10 → yes
✅ 020_incorrect_10 → no
✅ 021_correct_10 → no
✅ 021_incorrect_10 → no
✅ 022_correct_10 → yes
✅ 022_incorrect_10 → no
✅ 023_correct_10 → no
✅ 023_incorrect_10 → no
✅ 024_correct_10 → yes
✅ 024_incorrect_10 → no
✅ 025_correct_10 → yes
✅ 025_incorrect_10 → no
✅ 026_correct_10 → yes
✅ 026_incorrect_10 → no
✅ 027_correct_10 → yes
✅ 027_incorrect_10 → no
✅ 028_correct_10 → yes
✅ 028_incorrect_10 → no
✅ 029_correct_10 → yes
✅ 029_incorrect_10 → no
✅ 030_correct_10 → yes
✅ 030_incorrect_10 → no
✅ 031_correct_10 → no
✅ 031_incorrect_10 → no
✅ 032_correct_10 → yes
✅ 032_incorrect_10 → no
✅ 033_correct_10 → yes
✅ 033_incorrect_10 → no
✅ 034_correct_10 → yes
✅ 034_incorrect_10 → no
✅ 035_correct_10 → yes
✅ 035_incorrect_10 → no
✅ 036_correct_10 → no
✅ 036_incorrect_10 → no
✅ 037_correct_10 → no
✅ 037_incorrect_10 → no
✅ 038_correct_10 → no
✅ 038_incorrect_10 → no
✅ 039_correct_10 → no
✅ 039_incorrect_10 → no
✅ 040_correct_10 → yes
✅ 040_incorrect_10 → no
✅ 041_correct_10 → no
✅ 041_incorrect_10 → no
✅ 042_correct_10 → yes
✅ 042_incorrect_10 → yes
✅ 043_correct_10 → yes
✅ 043_incorrect_10 → no
✅ 044_correct_10 → no
✅ 044_incorrect_10 → no
✅ 045_correct_10 → yes
✅ 045_incorrect_10 → no
✅ 046_correct_10 → yes
✅ 046_incorrect_10 → yes
✅ 047_correct_10 → no
✅ 047_incorrect_10 → no
✅ 048_correct_10 → yes
✅ 048_incorrect_10 → no
✅ 049_correct_10 → yes
✅ 049_incorrect_10 → yes
✅ 050_correct_10 → yes
✅ 050_incorrect_10 → no
✅ 051_correct_10 → yes
✅ 051_incorrect_10 → no
✅ 052_correct_10 → no
✅ 052_incorrect_10 → no
✅ 053_correct_10 → yes
✅ 053_incorrect_10 → no
✅ 054_correct_10 → yes
✅ 054_incorrect_10 → no
✅ 055_correct_10 → yes
✅ 055_incorrect_10 → no
✅ 056_correct_10 → yes
✅ 056_incorrect_10 → no
✅ 057_correct_10 → no
✅ 057_incorrect_10 → no
✅ 058_correct_10 → yes
✅ 058_incorrect_10 → no
✅ 059_correct_10 → no
✅ 059_incorrect_10 → no
✅ 060_correct_10 → yes
✅ 060_incorrect_10 → no
✅ 061_correct_10 → yes
✅ 061_incorrect_10 → no
✅ 062_correct_10 → yes
✅ 062_incorrect_10 → no
✅ 063_correct_10 → yes
✅ 063_incorrect_10 → no
✅ 064_correct_10 → yes
✅ 064_incorrect_10 → no
✅ 065_correct_10 → yes
✅ 065_incorrect_10 → no
✅ 066_correct_10 → yes
✅ 066_incorrect_10 → no
✅ 067_correct_10 → yes
✅ 067_incorrect_10 → no
✅ 068_correct_10 → yes
✅ 068_incorrect_10 → no
✅ 069_correct_10 → no
✅ 069_incorrect_10 → no
✅ 070_correct_10 → no
✅ 070_incorrect_10 → no
✅ 071_correct_10 → yes
✅ 071_incorrect_10 → no
✅ 072_correct_10 → yes
✅ 072_incorrect_10 → no
✅ 073_correct_10 → yes
✅ 073_incorrect_10 → no
✅ 074_correct_10 → yes
✅ 074_incorrect_10 → yes
✅ 075_correct_10 → yes
✅ 075_incorrect_10 → no
✅ 076_correct_10 → no
✅ 076_incorrect_10 → no
✅ 077_correct_10 → yes
✅ 077_incorrect_10 → no
✅ 078_correct_10 → yes
✅ 078_incorrect_10 → no
✅ 079_correct_10 → no
✅ 079_incorrect_10 → no
✅ 080_correct_10 → no
✅ 080_incorrect_10 → no
✅ 081_correct_10 → yes
✅ 081_incorrect_10 → no
✅ 082_correct_10 → no
✅ 082_incorrect_10 → no
✅ 083_correct_10 → yes
✅ 083_incorrect_10 → no
✅ 084_correct_10 → yes
✅ 084_incorrect_10 → no
✅ 085_correct_10 → yes
✅ 085_incorrect_10 → no
✅ 086_correct_10 → yes
✅ 086_incorrect_10 → no
✅ 087_correct_10 → yes
✅ 087_incorrect_10 → no
✅ 088_correct_10 → no
✅ 088_incorrect_10 → no
✅ 089_correct_10 → yes
✅ 089_incorrect_10 → no
✅ 090_correct_10 → yes
✅ 090_incorrect_10 → no
✅ 091_correct_10 → yes
✅ 091_incorrect_10 → no
✅ 092_correct_10 → yes
✅ 092_incorrect_10 → no
✅ 093_correct_10 → yes
✅ 093_incorrect_10 → no
✅ 094_correct_10 → yes
✅ 094_incorrect_10 → no
✅ 095_correct_10 → yes
✅ 095_incorrect_10 → no
✅ 096_correct_10 → yes
✅ 096_incorrect_10 → yes
✅ 097_correct_10 → yes
✅ 097_incorrect_10 → no
✅ 098_correct_10 → no
✅ 098_incorrect_10 → no
✅ 099_correct_10 → yes
✅ 099_incorrect_10 → no
✅ 100_correct_10 → yes
✅ 100_incorrect_10 → no
✅ 001_correct_100 → no
✅ 001_incorrect_100 → no
✅ 002_correct_100 → yes
✅ 002_incorrect_100 → no
✅ 003_correct_100 → yes
✅ 003_incorrect_100 → no
✅ 004_correct_100 → yes
✅ 004_incorrect_100 → no
✅ 005_correct_100 → yes
✅ 005_incorrect_100 → no
✅ 006_correct_100 → yes
✅ 006_incorrect_100 → no
✅ 007_correct_100 → yes
✅ 007_incorrect_100 → no
✅ 008_correct_100 → no
✅ 008_incorrect_100 → no
✅ 009_correct_100 → no
✅ 009_incorrect_100 → no
✅ 010_correct_100 → yes
✅ 010_incorrect_100 → no
✅ 011_correct_100 → yes
✅ 011_incorrect_100 → no
✅ 012_correct_100 → yes
✅ 012_incorrect_100 → no
✅ 013_correct_100 → yes
✅ 013_incorrect_100 → no
✅ 014_correct_100 → yes
✅ 014_incorrect_100 → no
✅ 015_correct_100 → yes
✅ 015_incorrect_100 → no
✅ 016_correct_100 → yes
✅ 016_incorrect_100 → no
✅ 017_correct_100 → yes
✅ 017_incorrect_100 → no
✅ 018_correct_100 → no
✅ 018_incorrect_100 → no
✅ 019_correct_100 → yes
✅ 019_incorrect_100 → no
✅ 020_correct_100 → yes
✅ 020_incorrect_100 → no
✅ 021_correct_100 → yes
✅ 021_incorrect_100 → no
✅ 022_correct_100 → yes
✅ 022_incorrect_100 → no
✅ 023_correct_100 → no
✅ 023_incorrect_100 → no
✅ 024_correct_100 → yes
✅ 024_incorrect_100 → no
✅ 025_correct_100 → no
✅ 025_incorrect_100 → no
✅ 026_correct_100 → yes
✅ 026_incorrect_100 → no
✅ 027_correct_100 → yes
✅ 027_incorrect_100 → no
✅ 028_correct_100 → yes
✅ 028_incorrect_100 → no
✅ 029_correct_100 → yes
✅ 029_incorrect_100 → no
✅ 030_correct_100 → yes
✅ 030_incorrect_100 → yes
✅ 031_correct_100 → yes
✅ 031_incorrect_100 → no
✅ 032_correct_100 → yes
✅ 032_incorrect_100 → no
✅ 033_correct_100 → yes
✅ 033_incorrect_100 → no
✅ 034_correct_100 → yes
✅ 034_incorrect_100 → no
✅ 035_correct_100 → yes
✅ 035_incorrect_100 → no
✅ 036_correct_100 → no
✅ 036_incorrect_100 → no
✅ 037_correct_100 → yes
✅ 037_incorrect_100 → yes
✅ 038_correct_100 → yes
✅ 038_incorrect_100 → no
✅ 039_correct_100 → no
✅ 039_incorrect_100 → no
✅ 040_correct_100 → yes
✅ 040_incorrect_100 → no
✅ 041_correct_100 → no
✅ 041_incorrect_100 → no
✅ 042_correct_100 → yes
✅ 042_incorrect_100 → no
✅ 043_correct_100 → no
✅ 043_incorrect_100 → no
✅ 044_correct_100 → no
✅ 044_incorrect_100 → no
✅ 045_correct_100 → yes
✅ 045_incorrect_100 → no
✅ 046_correct_100 → yes
✅ 046_incorrect_100 → no
✅ 047_correct_100 → no
✅ 047_incorrect_100 → no
✅ 048_correct_100 → yes
✅ 048_incorrect_100 → no
✅ 049_correct_100 → yes
✅ 049_incorrect_100 → yes
✅ 050_correct_100 → yes
✅ 050_incorrect_100 → no
✅ 051_correct_100 → no
✅ 051_incorrect_100 → no
✅ 052_correct_100 → yes
✅ 052_incorrect_100 → no
✅ 053_correct_100 → yes
✅ 053_incorrect_100 → yes
✅ 054_correct_100 → no
✅ 054_incorrect_100 → no
✅ 055_correct_100 → yes
✅ 055_incorrect_100 → no
✅ 056_correct_100 → yes
✅ 056_incorrect_100 → yes
✅ 057_correct_100 → yes
✅ 057_incorrect_100 → no
✅ 058_correct_100 → yes
✅ 058_incorrect_100 → no
✅ 059_correct_100 → yes
✅ 059_incorrect_100 → no
✅ 060_correct_100 → yes
✅ 060_incorrect_100 → no
✅ 061_correct_100 → yes
✅ 061_incorrect_100 → no
✅ 062_correct_100 → yes
✅ 062_incorrect_100 → no
✅ 063_correct_100 → yes
✅ 063_incorrect_100 → no
✅ 064_correct_100 → yes
✅ 064_incorrect_100 → no
✅ 065_correct_100 → no
✅ 065_incorrect_100 → no
✅ 066_correct_100 → yes
✅ 066_incorrect_100 → no
✅ 067_correct_100 → yes
✅ 067_incorrect_100 → no
✅ 068_correct_100 → yes
✅ 068_incorrect_100 → no
✅ 069_correct_100 → yes
✅ 069_incorrect_100 → no
✅ 070_correct_100 → yes
✅ 070_incorrect_100 → no
✅ 071_correct_100 → yes
✅ 071_incorrect_100 → no
✅ 072_correct_100 → yes
✅ 072_incorrect_100 → no
✅ 073_correct_100 → yes
✅ 073_incorrect_100 → no
✅ 074_correct_100 → yes
✅ 074_incorrect_100 → no
✅ 075_correct_100 → yes
✅ 075_incorrect_100 → no
✅ 076_correct_100 → yes
✅ 076_incorrect_100 → no
✅ 077_correct_100 → no
✅ 077_incorrect_100 → no
✅ 078_correct_100 → no
✅ 078_incorrect_100 → no
✅ 079_correct_100 → yes
✅ 079_incorrect_100 → no
✅ 080_correct_100 → yes
✅ 080_incorrect_100 → no
✅ 081_correct_100 → yes
✅ 081_incorrect_100 → no
✅ 082_correct_100 → no
✅ 082_incorrect_100 → no
✅ 083_correct_100 → yes
✅ 083_incorrect_100 → no
✅ 084_correct_100 → yes
✅ 084_incorrect_100 → no
✅ 085_correct_100 → yes
✅ 085_incorrect_100 → no
✅ 086_correct_100 → yes
✅ 086_incorrect_100 → no
✅ 087_correct_100 → yes
✅ 087_incorrect_100 → no
✅ 088_correct_100 → yes
✅ 088_incorrect_100 → no
✅ 089_correct_100 → yes
✅ 089_incorrect_100 → no
✅ 090_correct_100 → yes
✅ 090_incorrect_100 → no
✅ 091_correct_100 → yes
✅ 091_incorrect_100 → yes
✅ 092_correct_100 → yes
✅ 092_incorrect_100 → no
✅ 093_correct_100 → yes
✅ 093_incorrect_100 → no
✅ 094_correct_100 → yes
✅ 094_incorrect_100 → no
✅ 095_correct_100 → yes
✅ 095_incorrect_100 → yes
✅ 096_correct_100 → yes
✅ 096_incorrect_100 → yes
✅ 097_correct_100 → yes
✅ 097_incorrect_100 → no
✅ 098_correct_100 → no
✅ 098_incorrect_100 → no
✅ 099_correct_100 → yes
✅ 099_incorrect_100 → yes
✅ 100_correct_100 → yes
✅ 100_incorrect_100 → no
✅ 001_correct_1000 → no
✅ 001_incorrect_1000 → no
✅ 002_correct_1000 → no
✅ 002_incorrect_1000 → no
✅ 003_correct_1000 → yes
✅ 003_incorrect_1000 → no
✅ 004_correct_1000 → yes
✅ 004_incorrect_1000 → no
✅ 005_correct_1000 → yes
✅ 005_incorrect_1000 → no
✅ 006_correct_1000 → no
✅ 006_incorrect_1000 → no
✅ 007_correct_1000 → yes
✅ 007_incorrect_1000 → no
✅ 008_correct_1000 → yes
✅ 008_incorrect_1000 → no
✅ 009_correct_1000 → no
✅ 009_incorrect_1000 → no
✅ 010_correct_1000 → yes
✅ 010_incorrect_1000 → no
✅ 011_correct_1000 → yes
✅ 011_incorrect_1000 → no
✅ 012_correct_1000 → yes
✅ 012_incorrect_1000 → no
✅ 013_correct_1000 → yes
✅ 013_incorrect_1000 → no
✅ 014_correct_1000 → yes
✅ 014_incorrect_1000 → no
✅ 015_correct_1000 → no
✅ 015_incorrect_1000 → no
✅ 016_correct_1000 → no
✅ 016_incorrect_1000 → no
✅ 017_correct_1000 → yes
✅ 017_incorrect_1000 → no
✅ 018_correct_1000 → yes
✅ 018_incorrect_1000 → no
✅ 019_correct_1000 → no
✅ 019_incorrect_1000 → no
✅ 020_correct_1000 → yes
✅ 020_incorrect_1000 → no
✅ 021_correct_1000 → yes
✅ 021_incorrect_1000 → no
✅ 022_correct_1000 → no
✅ 022_incorrect_1000 → no
✅ 023_correct_1000 → no
✅ 023_incorrect_1000 → no
✅ 024_correct_1000 → no
✅ 024_incorrect_1000 → no
✅ 025_correct_1000 → yes
✅ 025_incorrect_1000 → no
✅ 026_correct_1000 → yes
✅ 026_incorrect_1000 → no
✅ 027_correct_1000 → yes
✅ 027_incorrect_1000 → no
✅ 028_correct_1000 → no
✅ 028_incorrect_1000 → no
✅ 029_correct_1000 → no
✅ 029_incorrect_1000 → no
✅ 030_correct_1000 → yes
✅ 030_incorrect_1000 → yes
✅ 031_correct_1000 → no
✅ 031_incorrect_1000 → no
✅ 032_correct_1000 → yes
✅ 032_incorrect_1000 → no
✅ 033_correct_1000 → yes
✅ 033_incorrect_1000 → no
✅ 034_correct_1000 → yes
✅ 034_incorrect_1000 → no
✅ 035_correct_1000 → yes
✅ 035_incorrect_1000 → no
✅ 036_correct_1000 → yes
✅ 036_incorrect_1000 → no
✅ 037_correct_1000 → yes
✅ 037_incorrect_1000 → yes
✅ 038_correct_1000 → yes
✅ 038_incorrect_1000 → no
✅ 039_correct_1000 → yes
✅ 039_incorrect_1000 → no
✅ 040_correct_1000 → yes
✅ 040_incorrect_1000 → no
✅ 041_correct_1000 → no
✅ 041_incorrect_1000 → no
✅ 042_correct_1000 → yes
✅ 042_incorrect_1000 → no
✅ 043_correct_1000 → no
✅ 043_incorrect_1000 → no
✅ 044_correct_1000 → yes
✅ 044_incorrect_1000 → no
✅ 045_correct_1000 → yes
✅ 045_incorrect_1000 → no
✅ 046_correct_1000 → no
✅ 046_incorrect_1000 → no
✅ 047_correct_1000 → yes
✅ 047_incorrect_1000 → no
✅ 048_correct_1000 → yes
✅ 048_incorrect_1000 → yes
✅ 049_correct_1000 → yes
✅ 049_incorrect_1000 → no
✅ 050_correct_1000 → yes
✅ 050_incorrect_1000 → yes
✅ 051_correct_1000 → yes
✅ 051_incorrect_1000 → no
✅ 052_correct_1000 → no
✅ 052_incorrect_1000 → no
✅ 053_correct_1000 → yes
✅ 053_incorrect_1000 → yes
✅ 054_correct_1000 → no
✅ 054_incorrect_1000 → no
✅ 055_correct_1000 → yes
✅ 055_incorrect_1000 → no
✅ 056_correct_1000 → yes
✅ 056_incorrect_1000 → no
✅ 057_correct_1000 → no
✅ 057_incorrect_1000 → no
✅ 058_correct_1000 → yes
✅ 058_incorrect_1000 → no
✅ 059_correct_1000 → no
✅ 059_incorrect_1000 → no
✅ 060_correct_1000 → yes
✅ 060_incorrect_1000 → no
✅ 061_correct_1000 → yes
✅ 061_incorrect_1000 → no
✅ 062_correct_1000 → yes
✅ 062_incorrect_1000 → no
✅ 063_correct_1000 → yes
✅ 063_incorrect_1000 → no
✅ 064_correct_1000 → yes
✅ 064_incorrect_1000 → no
✅ 065_correct_1000 → no
✅ 065_incorrect_1000 → no
✅ 066_correct_1000 → yes
✅ 066_incorrect_1000 → no
✅ 067_correct_1000 → yes
✅ 067_incorrect_1000 → no
✅ 068_correct_1000 → yes
✅ 068_incorrect_1000 → no
✅ 069_correct_1000 → yes
✅ 069_incorrect_1000 → no
✅ 070_correct_1000 → yes
✅ 070_incorrect_1000 → no
✅ 071_correct_1000 → yes
✅ 071_incorrect_1000 → no
✅ 072_correct_1000 → no
✅ 072_incorrect_1000 → no
✅ 073_correct_1000 → no
✅ 073_incorrect_1000 → no
✅ 074_correct_1000 → yes
✅ 074_incorrect_1000 → yes
✅ 075_correct_1000 → yes
✅ 075_incorrect_1000 → no
✅ 076_correct_1000 → yes
✅ 076_incorrect_1000 → no
✅ 077_correct_1000 → yes
✅ 077_incorrect_1000 → no
✅ 078_correct_1000 → no
✅ 078_incorrect_1000 → no
✅ 079_correct_1000 → no
✅ 079_incorrect_1000 → no
✅ 080_correct_1000 → yes
✅ 080_incorrect_1000 → no
✅ 081_correct_1000 → yes
✅ 081_incorrect_1000 → yes
✅ 082_correct_1000 → yes
✅ 082_incorrect_1000 → no
✅ 083_correct_1000 → yes
✅ 083_incorrect_1000 → no
✅ 084_correct_1000 → yes
✅ 084_incorrect_1000 → no
✅ 085_correct_1000 → yes
✅ 085_incorrect_1000 → no
✅ 086_correct_1000 → no
✅ 086_incorrect_1000 → no
✅ 087_correct_1000 → yes
✅ 087_incorrect_1000 → no
✅ 088_correct_1000 → yes
✅ 088_incorrect_1000 → no
✅ 089_correct_1000 → yes
✅ 089_incorrect_1000 → no
✅ 090_correct_1000 → no
✅ 090_incorrect_1000 → no
✅ 091_correct_1000 → yes
✅ 091_incorrect_1000 → no
✅ 092_correct_1000 → yes
✅ 092_incorrect_1000 → no
✅ 093_correct_1000 → yes
✅ 093_incorrect_1000 → no
✅ 094_correct_1000 → yes
✅ 094_incorrect_1000 → no
✅ 095_correct_1000 → yes
✅ 095_incorrect_1000 → yes
✅ 096_correct_1000 → yes
✅ 096_incorrect_1000 → yes
✅ 097_correct_1000 → yes
✅ 097_incorrect_1000 → no
✅ 098_correct_1000 → yes
✅ 098_incorrect_1000 → no
✅ 099_correct_1000 → yes
✅ 099_incorrect_1000 → no
✅ 100_correct_1000 → yes
✅ 100_incorrect_1000 → no
✅ 001_correct_10000 → yes
✅ 001_incorrect_10000 → no
✅ 002_correct_10000 → no
✅ 002_incorrect_10000 → no
✅ 003_correct_10000 → yes
✅ 003_incorrect_10000 → no
✅ 004_correct_10000 → yes
✅ 004_incorrect_10000 → no
✅ 005_correct_10000 → yes
✅ 005_incorrect_10000 → no
✅ 006_correct_10000 → no
✅ 006_incorrect_10000 → no
✅ 007_correct_10000 → yes
✅ 007_incorrect_10000 → no
✅ 008_correct_10000 → yes
✅ 008_incorrect_10000 → no
✅ 009_correct_10000 → yes
✅ 009_incorrect_10000 → no
✅ 010_correct_10000 → yes
✅ 010_incorrect_10000 → yes
✅ 011_correct_10000 → yes
✅ 011_incorrect_10000 → no
✅ 012_correct_10000 → yes
✅ 012_incorrect_10000 → no
✅ 013_correct_10000 → yes
✅ 013_incorrect_10000 → no
✅ 014_correct_10000 → no
✅ 014_incorrect_10000 → no
✅ 015_correct_10000 → yes
✅ 015_incorrect_10000 → no
✅ 016_correct_10000 → no
✅ 016_incorrect_10000 → no
✅ 017_correct_10000 → yes
✅ 017_incorrect_10000 → yes
✅ 018_correct_10000 → no
✅ 018_incorrect_10000 → no
✅ 019_correct_10000 → yes
✅ 019_incorrect_10000 → no
✅ 020_correct_10000 → yes
✅ 020_incorrect_10000 → yes
✅ 021_correct_10000 → yes
✅ 021_incorrect_10000 → no
✅ 022_correct_10000 → yes
✅ 022_incorrect_10000 → no
✅ 023_correct_10000 → no
✅ 023_incorrect_10000 → no
✅ 024_correct_10000 → yes
✅ 024_incorrect_10000 → no
✅ 025_correct_10000 → yes
✅ 025_incorrect_10000 → no
✅ 026_correct_10000 → yes
✅ 026_incorrect_10000 → no
✅ 027_correct_10000 → yes
✅ 027_incorrect_10000 → no
✅ 028_correct_10000 → yes
✅ 028_incorrect_10000 → no
✅ 029_correct_10000 → yes
✅ 029_incorrect_10000 → no
✅ 030_correct_10000 → yes
✅ 030_incorrect_10000 → yes
✅ 031_correct_10000 → no
✅ 031_incorrect_10000 → no
✅ 032_correct_10000 → yes
✅ 032_incorrect_10000 → no
✅ 033_correct_10000 → yes
✅ 033_incorrect_10000 → no
✅ 034_correct_10000 → yes
✅ 034_incorrect_10000 → no
✅ 035_correct_10000 → yes
✅ 035_incorrect_10000 → yes
✅ 036_correct_10000 → yes
✅ 036_incorrect_10000 → no
✅ 037_correct_10000 → yes
✅ 037_incorrect_10000 → no
✅ 038_correct_10000 → yes
✅ 038_incorrect_10000 → yes
✅ 039_correct_10000 → yes
✅ 039_incorrect_10000 → no
✅ 040_correct_10000 → yes
✅ 040_incorrect_10000 → no
✅ 041_correct_10000 → yes
✅ 041_incorrect_10000 → yes
✅ 042_correct_10000 → yes
✅ 042_incorrect_10000 → no
✅ 043_correct_10000 → yes
✅ 043_incorrect_10000 → no
✅ 044_correct_10000 → yes
✅ 044_incorrect_10000 → no
✅ 045_correct_10000 → yes
✅ 045_incorrect_10000 → no
✅ 046_correct_10000 → yes
✅ 046_incorrect_10000 → no
✅ 047_correct_10000 → no
✅ 047_incorrect_10000 → no
✅ 048_correct_10000 → yes
✅ 048_incorrect_10000 → yes
✅ 049_correct_10000 → yes
✅ 049_incorrect_10000 → no
✅ 050_correct_10000 → yes
✅ 050_incorrect_10000 → yes
✅ 051_correct_10000 → no
✅ 051_incorrect_10000 → no
✅ 052_correct_10000 → no
✅ 052_incorrect_10000 → no
✅ 053_correct_10000 → yes
✅ 053_incorrect_10000 → yes
✅ 054_correct_10000 → no
✅ 054_incorrect_10000 → no
✅ 055_correct_10000 → yes
✅ 055_incorrect_10000 → no
✅ 056_correct_10000 → yes
✅ 056_incorrect_10000 → yes
✅ 057_correct_10000 → yes
✅ 057_incorrect_10000 → no
✅ 058_correct_10000 → yes
✅ 058_incorrect_10000 → no
✅ 059_correct_10000 → no
✅ 059_incorrect_10000 → no
✅ 060_correct_10000 → no
✅ 060_incorrect_10000 → no
✅ 061_correct_10000 → yes
✅ 061_incorrect_10000 → no
✅ 062_correct_10000 → yes
✅ 062_incorrect_10000 → no
✅ 063_correct_10000 → yes
✅ 063_incorrect_10000 → no
✅ 064_correct_10000 → yes
✅ 064_incorrect_10000 → no
✅ 065_correct_10000 → yes
✅ 065_incorrect_10000 → no
✅ 066_correct_10000 → yes
✅ 066_incorrect_10000 → no
✅ 067_correct_10000 → no
✅ 067_incorrect_10000 → yes
✅ 068_correct_10000 → yes
✅ 068_incorrect_10000 → no
✅ 069_correct_10000 → yes
✅ 069_incorrect_10000 → no
✅ 070_correct_10000 → yes
✅ 070_incorrect_10000 → no
✅ 071_correct_10000 → no
✅ 071_incorrect_10000 → no
✅ 072_correct_10000 → yes
✅ 072_incorrect_10000 → no
✅ 073_correct_10000 → no
✅ 073_incorrect_10000 → no
✅ 074_correct_10000 → yes
✅ 074_incorrect_10000 → yes
✅ 075_correct_10000 → yes
✅ 075_incorrect_10000 → no
✅ 076_correct_10000 → yes
✅ 076_incorrect_10000 → no
✅ 077_correct_10000 → yes
✅ 077_incorrect_10000 → no
✅ 078_correct_10000 → no
✅ 078_incorrect_10000 → no
✅ 079_correct_10000 → yes
✅ 079_incorrect_10000 → no
✅ 080_correct_10000 → yes
✅ 080_incorrect_10000 → no
✅ 081_correct_10000 → yes
✅ 081_incorrect_10000 → yes
✅ 082_correct_10000 → yes
✅ 082_incorrect_10000 → no
✅ 083_correct_10000 → yes
✅ 083_incorrect_10000 → no
✅ 084_correct_10000 → no
✅ 084_incorrect_10000 → no
✅ 085_correct_10000 → yes
✅ 085_incorrect_10000 → no
✅ 086_correct_10000 → yes
✅ 086_incorrect_10000 → no
✅ 087_correct_10000 → yes
✅ 087_incorrect_10000 → no
✅ 088_correct_10000 → yes
✅ 088_incorrect_10000 → yes
✅ 089_correct_10000 → yes
✅ 089_incorrect_10000 → no
✅ 090_correct_10000 → no
✅ 090_incorrect_10000 → no
✅ 091_correct_10000 → yes
✅ 091_incorrect_10000 → no
✅ 092_correct_10000 → yes
✅ 092_incorrect_10000 → no
✅ 093_correct_10000 → yes
✅ 093_incorrect_10000 → no
✅ 094_correct_10000 → yes
✅ 094_incorrect_10000 → no
✅ 095_correct_10000 → yes
✅ 095_incorrect_10000 → yes
✅ 096_correct_10000 → yes
✅ 096_incorrect_10000 → yes
✅ 097_correct_10000 → yes
✅ 097_incorrect_10000 → no
✅ 098_correct_10000 → no
✅ 098_incorrect_10000 → no
✅ 099_correct_10000 → yes
✅ 099_incorrect_10000 → no
✅ 100_correct_10000 → yes
✅ 100_incorrect_10000 → no
✅ 001_correct_100000 → yes

In [27]:
# metrics yes/no
analyse_metrics_single(OUTPUT_DIR, "e1_results_metrics_yesno.json", like_answer="yes")

============================================================
Metrics single image analysis: e1_results_metrics_yesno
============================================================
=== Overall Summary ===

                 metric  value
0    overall_yes_rate_%  49.75
1    yes_rate_correct_%  81.33
2  yes_rate_incorrect_%  18.17

=== Rate per Scale Value ===

/home/jovyan/conformity-llms-facebook-posts/experiments/e1/e1_utils/e1_analysis_optimized.py:116: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_scale = df.groupby("scale_value").apply(lambda g: pd.Series({

,scale_value,total_images,overall_yes_rate_%,yes_rate_correct_%,yes_rate_incorrect_%
0,10,200.0,40.0,75.0,5.0
1,100,200.0,45.0,81.0,9.0
2,1000,200.0,41.0,73.0,9.0
3,10000,200.0,48.5,80.0,17.0
4,100000,200.0,56.5,86.0,27.0
5,1000000,200.0,67.5,93.0,42.0

=== Per Image Results ===

,image,num,variant,scale_value,prompt,answer
0,001_correct_10,001,correct,10,You are shown a social media post.\nYou can ei...,yes
2,002_correct_10,002,correct,10,You are shown a social media post.\nYou can ei...,yes
4,003_correct_10,003,correct,10,You are shown a social media post.\nYou can ei...,yes
6,004_correct_10,004,correct,10,You are shown a social media post.\nYou can ei...,yes
8,005_correct_10,005,correct,10,You are shown a social media post.\nYou can ei...,yes
...,...,...,...,...,...,...
1191,096_incorrect_1000000,096,incorrect,1000000,You are shown a social media post.\nYou can ei...,yes
1193,097_incorrect_1000000,097,incorrect,1000000,You are shown a social media post.\nYou can ei...,no
1195,098_incorrect_1000000,098,incorrect,1000000,You are shown a social media post.\nYou can ei...,no
1197,099_incorrect_1000000,099,incorrect,1000000,You are shown a social media post.\nYou can ei...,yes
1199,100_incorrect_1000000,100,incorrect,1000000,You are shown a social media post.\nYou can ei...,yes

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_analysis_metrics_yesno.csv

# Metrics - A/B paired

In [28]:
# --- Approach 2 on metrics folders ---
import time
import importlib
import e1_utils.e1_optimized as e1
importlib.reload(e1)
from e1_utils.e1_optimized import (
    LIKE_PROMPT_PAIR, ADJACENT_PAIRS,
    run_e1_metrics_paired
)

start = time.time()

print(f"\n{'='*60}\nApproach 2 on metrics: paired A/B per scale\n{'='*60}")
correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/realistic"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/realistic"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]


run_e1_metrics_paired(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR, SEED,
                      prompt=LIKE_PROMPT_PAIR, output_filename="e1_results_metrics_paired.json",  inference_fn=run_inference_qwen,
                      baseline_correct_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs",
                      baseline_incorrect_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/incorrect/PNGs")

end = time.time()
elapsed = end - start
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)
print(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")
print(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")

============================================================
Approach 2 on metrics: paired A/B per scale
============================================================
✅ 001_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 002_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 003_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 004_correct0_vs_incorrect0 → liked correct (answered B)
✅ 005_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 006_correct0_vs_incorrect0 → liked correct (answered B)
✅ 007_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 008_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 009_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 010_correct0_vs_incorrect0 → liked correct (answered B)
✅ 011_correct0_vs_incorrect0 → liked correct (answered B)
✅ 012_correct0_vs_incorrect0 → liked correct (answered B)
✅ 013_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 014_correct0_vs_incorrect0 → liked correct (answered B)
✅ 015_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 016_correct0_vs_incorrect0 → liked correct (answered B)
✅ 017_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 018_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 019_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 020_correct0_vs_incorrect0 → liked correct (answered B)
✅ 021_correct0_vs_incorrect0 → liked correct (answered A)
✅ 022_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 023_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 024_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 025_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 026_correct0_vs_incorrect0 → liked correct (answered B)
✅ 027_correct0_vs_incorrect0 → liked correct (answered B)
✅ 028_correct0_vs_incorrect0 → liked correct (answered B)
✅ 029_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 030_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 031_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 032_correct0_vs_incorrect0 → liked correct (answered B)
✅ 033_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 034_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 035_correct0_vs_incorrect0 → liked correct (answered B)
✅ 036_correct0_vs_incorrect0 → liked correct (answered B)
✅ 037_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 038_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 039_correct0_vs_incorrect0 → liked correct (answered B)
✅ 040_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 041_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 042_correct0_vs_incorrect0 → liked correct (answered B)
✅ 043_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 044_correct0_vs_incorrect0 → liked correct (answered B)
✅ 045_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 046_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 047_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 048_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 049_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 050_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 051_correct0_vs_incorrect0 → liked correct (answered B)
✅ 052_correct0_vs_incorrect0 → liked correct (answered B)
✅ 053_correct0_vs_incorrect0 → liked correct (answered B)
✅ 054_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 055_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 056_correct0_vs_incorrect0 → liked correct (answered A)
✅ 057_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 058_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 059_correct0_vs_incorrect0 → liked correct (answered B)
✅ 060_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 061_correct0_vs_incorrect0 → liked correct (answered B)
✅ 062_correct0_vs_incorrect0 → liked correct (answered B)
✅ 063_correct0_vs_incorrect0 → liked correct (answered B)
✅ 064_correct0_vs_incorrect0 → liked correct (answered B)
✅ 065_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 066_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 067_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 068_correct0_vs_incorrect0 → liked correct (answered B)
✅ 069_correct0_vs_incorrect0 → liked correct (answered B)
✅ 070_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 071_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 072_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 073_correct0_vs_incorrect0 → liked correct (answered B)
✅ 074_correct0_vs_incorrect0 → liked correct (answered B)
✅ 075_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 076_correct0_vs_incorrect0 → liked correct (answered B)
✅ 077_correct0_vs_incorrect0 → liked correct (answered B)
✅ 078_correct0_vs_incorrect0 → liked correct (answered B)
✅ 079_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 080_correct0_vs_incorrect0 → liked correct (answered B)
✅ 081_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 082_correct0_vs_incorrect0 → liked correct (answered B)
✅ 083_correct0_vs_incorrect0 → liked correct (answered B)
✅ 084_correct0_vs_incorrect0 → liked correct (answered B)
✅ 085_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 086_correct0_vs_incorrect0 → liked correct (answered B)
✅ 087_correct0_vs_incorrect0 → liked correct (answered B)
✅ 088_correct0_vs_incorrect0 → liked correct (answered B)
✅ 089_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 090_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 091_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 092_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 093_correct0_vs_incorrect0 → liked correct (answered B)
✅ 094_correct0_vs_incorrect0 → liked correct (answered B)
✅ 095_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 096_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 097_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 098_correct0_vs_incorrect0 → liked correct (answered B)
✅ 099_correct0_vs_incorrect0 → liked correct (answered B)
✅ 100_correct0_vs_incorrect0 → liked correct (answered B)
✅ 001_correct0_vs_incorrect10 → liked correct (answered B)
✅ 002_correct0_vs_incorrect10 → liked correct (answered B)
✅ 003_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 004_correct0_vs_incorrect10 → liked correct (answered B)
✅ 005_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 006_correct0_vs_incorrect10 → liked correct (answered B)
✅ 007_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 008_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 009_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 010_correct0_vs_incorrect10 → liked correct (answered B)
✅ 011_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 012_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 013_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 014_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 015_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 016_correct0_vs_incorrect10 → liked correct (answered B)
✅ 017_correct0_vs_incorrect10 → liked correct (answered B)
✅ 018_correct0_vs_incorrect10 → liked correct (answered B)
✅ 019_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 020_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 021_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 022_correct0_vs_incorrect10 → liked correct (answered B)
✅ 023_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 024_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 025_correct0_vs_incorrect10 → liked correct (answered B)
✅ 026_correct0_vs_incorrect10 → liked correct (answered B)
✅ 027_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 028_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 029_correct0_vs_incorrect10 → liked correct (answered B)
✅ 030_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 031_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 032_correct0_vs_incorrect10 → liked correct (answered B)
✅ 033_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 034_correct0_vs_incorrect10 → liked correct (answered B)
✅ 035_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 036_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 037_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 038_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 039_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 040_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 041_correct0_vs_incorrect10 → liked correct (answered B)
✅ 042_correct0_vs_incorrect10 → liked correct (answered B)
✅ 043_correct0_vs_incorrect10 → liked correct (answered B)
✅ 044_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 045_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 046_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 047_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 048_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 049_correct0_vs_incorrect10 → liked correct (answered B)
✅ 050_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 051_correct0_vs_incorrect10 → liked correct (answered B)
✅ 052_correct0_vs_incorrect10 → liked correct (answered B)
✅ 053_correct0_vs_incorrect10 → liked correct (answered B)
✅ 054_correct0_vs_incorrect10 → liked correct (answered B)
✅ 055_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 056_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 057_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 058_correct0_vs_incorrect10 → liked correct (answered B)
✅ 059_correct0_vs_incorrect10 → liked correct (answered B)
✅ 060_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 061_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 062_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 063_correct0_vs_incorrect10 → liked correct (answered B)
✅ 064_correct0_vs_incorrect10 → liked correct (answered B)
✅ 065_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 066_correct0_vs_incorrect10 → liked correct (answered B)
✅ 067_correct0_vs_incorrect10 → liked correct (answered B)
✅ 068_correct0_vs_incorrect10 → liked correct (answered B)
✅ 069_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 070_correct0_vs_incorrect10 → liked correct (answered B)
✅ 071_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 072_correct0_vs_incorrect10 → liked correct (answered B)
✅ 073_correct0_vs_incorrect10 → liked correct (answered B)
✅ 074_correct0_vs_incorrect10 → liked correct (answered B)
✅ 075_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 076_correct0_vs_incorrect10 → liked correct (answered B)
✅ 077_correct0_vs_incorrect10 → liked correct (answered B)
✅ 078_correct0_vs_incorrect10 → liked correct (answered B)
✅ 079_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 080_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 081_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 082_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 083_correct0_vs_incorrect10 → liked correct (answered B)
✅ 084_correct0_vs_incorrect10 → liked correct (answered B)
✅ 085_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 086_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 087_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 088_correct0_vs_incorrect10 → liked correct (answered B)
✅ 089_correct0_vs_incorrect10 → liked correct (answered B)
✅ 090_correct0_vs_incorrect10 → liked correct (answered B)
✅ 091_correct0_vs_incorrect10 → liked correct (answered B)
✅ 092_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 093_correct0_vs_incorrect10 → liked correct (answered B)
✅ 094_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 095_correct0_vs_incorrect10 → liked correct (answered B)
✅ 096_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 097_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 098_correct0_vs_incorrect10 → liked correct (answered B)
✅ 099_correct0_vs_incorrect10 → liked correct (answered B)
✅ 100_correct0_vs_incorrect10 → liked correct (answered B)
✅ 001_correct0_vs_incorrect100 → liked correct (answered B)
✅ 002_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 003_correct0_vs_incorrect100 → liked correct (answered B)
✅ 004_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 005_correct0_vs_incorrect100 → liked correct (answered B)
✅ 006_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 007_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 008_correct0_vs_incorrect100 → liked correct (answered B)
✅ 009_correct0_vs_incorrect100 → liked correct (answered B)
✅ 010_correct0_vs_incorrect100 → liked correct (answered B)
✅ 011_correct0_vs_incorrect100 → liked correct (answered B)
✅ 012_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 013_correct0_vs_incorrect100 → liked correct (answered B)
✅ 014_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 015_correct0_vs_incorrect100 → liked correct (answered B)
✅ 016_correct0_vs_incorrect100 → liked correct (answered B)
✅ 017_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 018_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 019_correct0_vs_incorrect100 → liked correct (answered B)
✅ 020_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 021_correct0_vs_incorrect100 → liked correct (answered B)
✅ 022_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 023_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 024_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 025_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 026_correct0_vs_incorrect100 → liked correct (answered B)
✅ 027_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 028_correct0_vs_incorrect100 → liked correct (answered B)
✅ 029_correct0_vs_incorrect100 → liked correct (answered B)
✅ 030_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 031_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 032_correct0_vs_incorrect100 → liked correct (answered B)
✅ 033_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 034_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 035_correct0_vs_incorrect100 → liked correct (answered B)
✅ 036_correct0_vs_incorrect100 → liked correct (answered B)
✅ 037_correct0_vs_incorrect100 → liked correct (answered B)
✅ 038_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 039_correct0_vs_incorrect100 → liked correct (answered B)
✅ 040_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 041_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 042_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 043_correct0_vs_incorrect100 → liked correct (answered B)
✅ 044_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 045_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 046_correct0_vs_incorrect100 → liked correct (answered B)
✅ 047_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 048_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 049_correct0_vs_incorrect100 → liked correct (answered B)
✅ 050_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 051_correct0_vs_incorrect100 → liked correct (answered B)
✅ 052_correct0_vs_incorrect100 → liked correct (answered B)
✅ 053_correct0_vs_incorrect100 → liked correct (answered B)
✅ 054_correct0_vs_incorrect100 → liked correct (answered B)
✅ 055_correct0_vs_incorrect100 → liked correct (answered B)
✅ 056_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 057_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 058_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 059_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 060_correct0_vs_incorrect100 → liked correct (answered B)
✅ 061_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 062_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 063_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 064_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 065_correct0_vs_incorrect100 → liked correct (answered B)
✅ 066_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 067_correct0_vs_incorrect100 → liked correct (answered B)
✅ 068_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 069_correct0_vs_incorrect100 → liked correct (answered B)
✅ 070_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 071_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 072_correct0_vs_incorrect100 → liked correct (answered B)
✅ 073_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 074_correct0_vs_incorrect100 → liked correct (answered B)
✅ 075_correct0_vs_incorrect100 → liked correct (answered B)
✅ 076_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 077_correct0_vs_incorrect100 → liked correct (answered B)
✅ 078_correct0_vs_incorrect100 → liked correct (answered B)
✅ 079_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 080_correct0_vs_incorrect100 → liked correct (answered B)
✅ 081_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 082_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 083_correct0_vs_incorrect100 → liked correct (answered B)
✅ 084_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 085_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 086_correct0_vs_incorrect100 → liked correct (answered B)
✅ 087_correct0_vs_incorrect100 → liked correct (answered B)
✅ 088_correct0_vs_incorrect100 → liked correct (answered B)
✅ 089_correct0_vs_incorrect100 → liked correct (answered B)
✅ 090_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 091_correct0_vs_incorrect100 → liked correct (answered B)
✅ 092_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 093_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 094_correct0_vs_incorrect100 → liked correct (answered B)
✅ 095_correct0_vs_incorrect100 → liked correct (answered B)
✅ 096_correct0_vs_incorrect100 → liked correct (answered B)
✅ 097_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 098_correct0_vs_incorrect100 → liked correct (answered B)
✅ 099_correct0_vs_incorrect100 → liked correct (answered B)
✅ 100_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 001_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 002_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 003_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 004_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 005_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 006_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 007_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 008_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 009_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 010_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 011_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 012_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 013_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 014_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 015_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 016_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 017_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 018_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 019_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 020_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 021_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 022_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 023_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 024_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 025_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 026_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 027_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 028_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 029_correct0_vs_incorrect1000 → liked incorrect (answered B)

In [29]:
analyse_metrics_paired(OUTPUT_DIR, "e1_results_metrics_paired.json")

============================================================
Metrics paired A/B analysis: e1_results_metrics_paired
============================================================
=== Overall Summary ===

                      metric  value
0    overall_liked_correct_%  50.18
1  overall_liked_incorrect_%  49.82
2           invalid_answer_%   0.00

=== Liked Correct Rate per Scale Pair ===

/home/jovyan/conformity-llms-facebook-posts/experiments/e1/e1_utils/e1_analysis_optimized.py:163: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_pair = df.groupby("pair").apply(lambda g: pd.Series({

,pair,total_pairs,liked_correct_%,liked_incorrect_%,invalid_%
0,0_vs_0,100.0,46.0,54.0,0.0
1,0_vs_10,100.0,47.0,53.0,0.0
2,0_vs_100,100.0,49.0,51.0,0.0
3,0_vs_1000,100.0,41.0,59.0,0.0
4,0_vs_10000,100.0,44.0,56.0,0.0
5,0_vs_100000,100.0,54.0,46.0,0.0
6,0_vs_1000000,100.0,53.0,47.0,0.0
7,10_vs_0,100.0,48.0,52.0,0.0
8,10_vs_10,100.0,50.0,50.0,0.0
9,10_vs_100,100.0,14.0,86.0,0.0
10,10_vs_1000,100.0,7.0,93.0,0.0
11,10_vs_10000,100.0,5.0,95.0,0.0
12,10_vs_100000,100.0,0.0,100.0,0.0
13,10_vs_1000000,100.0,0.0,100.0,0.0
14,100_vs_0,100.0,49.0,51.0,0.0
15,100_vs_10,100.0,90.0,10.0,0.0
16,100_vs_100,100.0,52.0,48.0,0.0
17,100_vs_1000,100.0,0.0,100.0,0.0
18,100_vs_10000,100.0,0.0,100.0,0.0
19,100_vs_100000,100.0,3.0,97.0,0.0
20,100_vs_1000000,100.0,0.0,100.0,0.0
21,1000_vs_0,100.0,43.0,57.0,0.0
22,1000_vs_10,100.0,92.0,8.0,0.0
23,1000_vs_100,100.0,100.0,0.0,0.0
24,1000_vs_1000,100.0,49.0,51.0,0.0
25,1000_vs_10000,100.0,2.0,98.0,0.0
26,1000_vs_100000,100.0,41.0,59.0,0.0
27,1000_vs_1000000,100.0,49.0,51.0,0.0
28,10000_vs_0,100.0,44.0,56.0,0.0
29,10000_vs_10,100.0,100.0,0.0,0.0
30,10000_vs_100,100.0,100.0,0.0,0.0
31,10000_vs_1000,100.0,99.0,1.0,0.0
32,10000_vs_10000,100.0,53.0,47.0,0.0
33,10000_vs_100000,100.0,0.0,100.0,0.0
34,10000_vs_1000000,100.0,0.0,100.0,0.0
35,100000_vs_0,100.0,55.0,45.0,0.0
36,100000_vs_10,100.0,100.0,0.0,0.0
37,100000_vs_100,100.0,96.0,4.0,0.0
38,100000_vs_1000,100.0,67.0,33.0,0.0
39,100000_vs_10000,100.0,100.0,0.0,0.0
40,100000_vs_100000,100.0,52.0,48.0,0.0
41,100000_vs_1000000,100.0,0.0,100.0,0.0
42,1000000_vs_0,100.0,55.0,45.0,0.0
43,1000000_vs_10,100.0,100.0,0.0,0.0
44,1000000_vs_100,100.0,100.0,0.0,0.0
45,1000000_vs_1000,100.0,53.0,47.0,0.0
46,1000000_vs_10000,100.0,99.0,1.0,0.0
47,1000000_vs_100000,100.0,99.0,1.0,0.0
48,1000000_vs_1000000,100.0,59.0,41.0,0.0

=== Per Pair Results ===

,image,num,correct_scale,incorrect_scale,post_a_variant,post_b_variant,prompt,answer,liked_variant,pair
0,001_correct0_vs_incorrect0,001,0,0,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,0_vs_0
1,002_correct0_vs_incorrect0,002,0,0,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,0_vs_0
2,003_correct0_vs_incorrect0,003,0,0,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,0_vs_0
3,004_correct0_vs_incorrect0,004,0,0,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct,0_vs_0
4,005_correct0_vs_incorrect0,005,0,0,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,0_vs_0
...,...,...,...,...,...,...,...,...,...,...
4895,096_correct1000000_vs_incorrect1000000,096,1000000,1000000,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,1000000_vs_1000000
4896,097_correct1000000_vs_incorrect1000000,097,1000000,1000000,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct,1000000_vs_1000000
4897,098_correct1000000_vs_incorrect1000000,098,1000000,1000000,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct,1000000_vs_1000000
4898,099_correct1000000_vs_incorrect1000000,099,1000000,1000000,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,1000000_vs_1000000
4899,100_correct1000000_vs_incorrect1000000,100,1000000,1000000,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,1000000_vs_1000000

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_analysis_metrics_paired.csv

# Metrics — correct vs. correct paired A/B (comparison 1)

Added 2026-07-16 per supervisor feedback (`docs/SESSION_HANDOFF.md`). Pairs the correct-claim variant of the same post against itself at two different engagement scales, isolating the pure engagement-preference effect with content held constant — comparison 1 of the two-comparison design (comparison 2 is the correct-vs-incorrect cell above, already run). Reuses the same rendered images, no new assets needed.

In [30]:
import time
start = time.time()

from e1_utils.e1_optimized import run_e1_correct_vs_correct_paired

correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/realistic"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

# --- Correct vs. correct paired A/B (comparison 1) ---
run_e1_correct_vs_correct_paired(selected_numbers, correct_base, model, processor, device, OUTPUT_DIR, SEED,
                      prompt=LIKE_PROMPT_PAIR, output_filename="e1_results_metrics_correct_vs_correct_paired.json",
                      inference_fn=run_inference_qwen,
                      baseline_correct_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs")

end = time.time()
elapsed = end - start
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)
print(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")
print(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")

✅ 001_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 002_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 003_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 004_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 005_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 006_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 007_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 008_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 009_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 010_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 011_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 012_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 013_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 014_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 015_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 016_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 017_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 018_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 019_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 020_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 021_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 022_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 023_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 024_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 025_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 026_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 027_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 028_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 029_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 030_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 031_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 032_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 033_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 034_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 035_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 036_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 037_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 038_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 039_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 040_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 041_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 042_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 043_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 044_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 045_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 046_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 047_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 048_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 049_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 050_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 051_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 052_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 053_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 054_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 055_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 056_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 057_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 058_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 059_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 060_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 061_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 062_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 063_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 064_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 065_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 066_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 067_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 068_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 069_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 070_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 071_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 072_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 073_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 074_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 075_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 076_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 077_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 078_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 079_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 080_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 081_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 082_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 083_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 084_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 085_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 086_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 087_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 088_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 089_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 090_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 091_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 092_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 093_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 094_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 095_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 096_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 097_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 098_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 099_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 100_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 001_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 002_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 003_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 004_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 005_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 006_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 007_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 008_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 009_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 010_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 011_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 012_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 013_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 014_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 015_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 016_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 017_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 018_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 019_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 020_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 021_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 022_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 023_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 024_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 025_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 026_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 027_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 028_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 029_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 030_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 031_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 032_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 033_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 034_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 035_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 036_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 037_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 038_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 039_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 040_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 041_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 042_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 043_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 044_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 045_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 046_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 047_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 048_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 049_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 050_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 051_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 052_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 053_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 054_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 055_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 056_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 057_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 058_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 059_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 060_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 061_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 062_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 063_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 064_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 065_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 066_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 067_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 068_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 069_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 070_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 071_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 072_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 073_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 074_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 075_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 076_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 077_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 078_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 079_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 080_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 081_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 082_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 083_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 084_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 085_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 086_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 087_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 088_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 089_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 090_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 091_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 092_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 093_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 094_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 095_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 096_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 097_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 098_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 099_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 100_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 001_correct0_vs_correct100 → liked scale 0 (answered B)
✅ 002_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 003_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 004_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 005_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 006_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 007_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 008_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 009_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 010_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 011_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 012_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 013_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 014_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 015_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 016_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 017_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 018_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 019_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 020_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 021_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 022_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 023_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 024_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 025_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 026_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 027_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 028_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 029_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 030_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 031_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 032_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 033_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 034_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 035_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 036_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 037_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 038_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 039_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 040_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 041_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 042_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 043_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 044_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 045_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 046_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 047_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 048_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 049_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 050_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 051_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 052_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 053_correct0_vs_correct100 → liked scale 0 (answered B)
✅ 054_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 055_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 056_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 057_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 058_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 059_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 060_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 061_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 062_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 063_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 064_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 065_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 066_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 067_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 068_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 069_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 070_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 071_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 072_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 073_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 074_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 075_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 076_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 077_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 078_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 079_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 080_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 081_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 082_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 083_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 084_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 085_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 086_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 087_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 088_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 089_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 090_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 091_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 092_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 093_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 094_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 095_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 096_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 097_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 098_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 099_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 100_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 001_correct0_vs_correct1000 → liked scale 0 (answered B)
✅ 002_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 003_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 004_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 005_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 006_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 007_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 008_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 009_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 010_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 011_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 012_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 013_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 014_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 015_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 016_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 017_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 018_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 019_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 020_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 021_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 022_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 023_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 024_correct0_vs_correct1000 → liked scale 0 (answered B)
✅ 025_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 026_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 027_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 028_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 029_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 030_correct0_vs_correct1000 → liked scale 0 (answered B)
✅ 031_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 032_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 033_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 034_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 035_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 036_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 037_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 038_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 039_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 040_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 041_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 042_correct0_vs_correct1000 → liked scale 1000 (answered A)

In [31]:
from e1_utils.e1_analysis_optimized import analyse_cc_paired

analyse_cc_paired(OUTPUT_DIR, "e1_results_metrics_correct_vs_correct_paired.json")

============================================================
Correct-vs-correct paired A/B analysis: e1_results_metrics_correct_vs_correct_paired
============================================================
=== Overall Summary ===

                                              metric   value
0  overall_chose_higher_engagement_% (off-diagona...   97.74
1               invalid_answer_% (off-diagonal only)    0.00
2  position_bias_chose_A_% (diagonal only, 50% = ...  100.00

=== Chose-Higher-Engagement Rate per Scale Pair (off-diagonal) ===

/home/jovyan/conformity-llms-facebook-posts/experiments/e1/e1_utils/e1_analysis_optimized.py:217: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_pair = off_diag.groupby("pair").apply(lambda g: pd.Series({

                  pair  total_pairs  chose_higher_engagement_%  invalid_%
0               0_vs_0          0.0                        NaN        NaN
1              0_vs_10        100.0                       81.0        0.0
2             0_vs_100        100.0                       98.0        0.0
3            0_vs_1000        100.0                       95.0        0.0
4           0_vs_10000        100.0                       98.0        0.0
5          0_vs_100000        100.0                       92.0        0.0
6         0_vs_1000000        100.0                       99.0        0.0
7              10_vs_0        100.0                       86.0        0.0
8             10_vs_10          0.0                        NaN        NaN
9            10_vs_100        100.0                      100.0        0.0
10          10_vs_1000        100.0                      100.0        0.0
11         10_vs_10000        100.0                      100.0        0.0
12        10_vs_100000        100.0                      100.0        0.0
13       10_vs_1000000        100.0                      100.0        0.0
14            100_vs_0        100.0                       93.0        0.0
15           100_vs_10        100.0                      100.0        0.0
16          100_vs_100          0.0                        NaN        NaN
17         100_vs_1000        100.0                      100.0        0.0
18        100_vs_10000        100.0                      100.0        0.0
19       100_vs_100000        100.0                      100.0        0.0
20      100_vs_1000000        100.0                      100.0        0.0
21           1000_vs_0        100.0                       94.0        0.0
22          1000_vs_10        100.0                      100.0        0.0
23         1000_vs_100        100.0                      100.0        0.0
24        1000_vs_1000          0.0                        NaN        NaN
25       1000_vs_10000        100.0                      100.0        0.0
26      1000_vs_100000        100.0                       91.0        0.0
27     1000_vs_1000000        100.0                       97.0        0.0
28          10000_vs_0        100.0                       93.0        0.0
29         10000_vs_10        100.0                      100.0        0.0
30        10000_vs_100        100.0                      100.0        0.0
31       10000_vs_1000        100.0                      100.0        0.0
32      10000_vs_10000          0.0                        NaN        NaN
33     10000_vs_100000        100.0                      100.0        0.0
34    10000_vs_1000000        100.0                      100.0        0.0
35         100000_vs_0        100.0                       93.0        0.0
36        100000_vs_10        100.0                      100.0        0.0
37       100000_vs_100        100.0                      100.0        0.0
38      100000_vs_1000        100.0                      100.0        0.0
39     100000_vs_10000        100.0                      100.0        0.0
40    100000_vs_100000          0.0                        NaN        NaN
41   100000_vs_1000000        100.0                      100.0        0.0
42        1000000_vs_0        100.0                       98.0        0.0
43       1000000_vs_10        100.0                      100.0        0.0
44      1000000_vs_100        100.0                      100.0        0.0
45     1000000_vs_1000        100.0                       97.0        0.0
46    1000000_vs_10000        100.0                      100.0        0.0
47   1000000_vs_100000        100.0                      100.0        0.0
48  1000000_vs_1000000          0.0                        NaN        NaN

=== Per Pair Results (all rows, including diagonal) ===

,image,num,scale_a,scale_b,post_a_scale,post_b_scale,prompt,answer,liked_scale,liked_higher_engagement,pair
0,001_correct0_vs_correct0,001,0,0,0,0,"You are shown two social media posts, Post A a...",A,0,True,0_vs_0
1,002_correct0_vs_correct0,002,0,0,0,0,"You are shown two social media posts, Post A a...",A,0,True,0_vs_0
2,003_correct0_vs_correct0,003,0,0,0,0,"You are shown two social media posts, Post A a...",A,0,True,0_vs_0
3,004_correct0_vs_correct0,004,0,0,0,0,"You are shown two social media posts, Post A a...",A,0,True,0_vs_0
4,005_correct0_vs_correct0,005,0,0,0,0,"You are shown two social media posts, Post A a...",A,0,True,0_vs_0
...,...,...,...,...,...,...,...,...,...,...,...
4895,096_correct1000000_vs_correct1000000,096,1000000,1000000,1000000,1000000,"You are shown two social media posts, Post A a...",A,1000000,True,1000000_vs_1000000
4896,097_correct1000000_vs_correct1000000,097,1000000,1000000,1000000,1000000,"You are shown two social media posts, Post A a...",A,1000000,True,1000000_vs_1000000
4897,098_correct1000000_vs_correct1000000,098,1000000,1000000,1000000,1000000,"You are shown two social media posts, Post A a...",A,1000000,True,1000000_vs_1000000
4898,099_correct1000000_vs_correct1000000,099,1000000,1000000,1000000,1000000,"You are shown two social media posts, Post A a...",A,1000000,True,1000000_vs_1000000
4899,100_correct1000000_vs_correct1000000,100,1000000,1000000,1000000,1000000,"You are shown two social media posts, Post A a...",A,1000000,True,1000000_vs_1000000

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_analysis_metrics_correct_vs_correct_paired.csv

# LIKES ONLY NOISE

In [32]:
correct_base_noise = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only_noise"
incorrect_base_noise = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/likes_only_noise"

run_e1_metrics(selected_numbers, correct_base_noise, incorrect_base_noise, model, processor, device, OUTPUT_DIR,
              prompt=LIKE_PROMPT_SINGLE, output_filename="e1_results_likes_only_noise.json",
              inference_fn=run_inference_qwen)

run_e1_metrics(selected_numbers, correct_base_noise, incorrect_base_noise, model, processor, device, OUTPUT_DIR,
              prompt=LIKE_PROMPT_YESNO, output_filename="e1_results_likes_only_noise_yesno.json",
              inference_fn=run_inference_qwen)

✅ 001_correct_10 → like
✅ 001_incorrect_10 → scroll
✅ 002_correct_10 → like
✅ 002_incorrect_10 → scroll
✅ 003_correct_10 → like
✅ 003_incorrect_10 → scroll
✅ 004_correct_10 → like
✅ 004_incorrect_10 → scroll
✅ 005_correct_10 → scroll
✅ 005_incorrect_10 → scroll
✅ 006_correct_10 → like
✅ 006_incorrect_10 → scroll
✅ 007_correct_10 → like
✅ 007_incorrect_10 → scroll
✅ 008_correct_10 → like
✅ 008_incorrect_10 → scroll
✅ 009_correct_10 → like
✅ 009_incorrect_10 → scroll
✅ 010_correct_10 → like
✅ 010_incorrect_10 → scroll
✅ 011_correct_10 → scroll
✅ 011_incorrect_10 → scroll
✅ 012_correct_10 → like
✅ 012_incorrect_10 → scroll
✅ 013_correct_10 → scroll
✅ 013_incorrect_10 → scroll
✅ 014_correct_10 → like
✅ 014_incorrect_10 → scroll
✅ 015_correct_10 → scroll
✅ 015_incorrect_10 → scroll
✅ 016_correct_10 → scroll
✅ 016_incorrect_10 → scroll
✅ 017_correct_10 → like
✅ 017_incorrect_10 → scroll
✅ 018_correct_10 → like
✅ 018_incorrect_10 → scroll
✅ 019_correct_10 → scroll
✅ 019_incorrect_10 → scroll
✅ 020_correct_10 → like
✅ 020_incorrect_10 → scroll
✅ 021_correct_10 → scroll
✅ 021_incorrect_10 → scroll
✅ 022_correct_10 → scroll
✅ 022_incorrect_10 → scroll
✅ 023_correct_10 → scroll
✅ 023_incorrect_10 → scroll
✅ 024_correct_10 → scroll
✅ 024_incorrect_10 → scroll
✅ 025_correct_10 → like
✅ 025_incorrect_10 → scroll
✅ 026_correct_10 → like
✅ 026_incorrect_10 → scroll
✅ 027_correct_10 → scroll
✅ 027_incorrect_10 → scroll
✅ 028_correct_10 → like
✅ 028_incorrect_10 → scroll
✅ 029_correct_10 → like
✅ 029_incorrect_10 → scroll
✅ 030_correct_10 → like
✅ 030_incorrect_10 → scroll
✅ 031_correct_10 → like
✅ 031_incorrect_10 → scroll
✅ 032_correct_10 → like
✅ 032_incorrect_10 → scroll
✅ 033_correct_10 → scroll
✅ 033_incorrect_10 → scroll
✅ 034_correct_10 → like
✅ 034_incorrect_10 → scroll
✅ 035_correct_10 → like
✅ 035_incorrect_10 → scroll
✅ 036_correct_10 → like
✅ 036_incorrect_10 → scroll
✅ 037_correct_10 → like
✅ 037_incorrect_10 → scroll
✅ 038_correct_10 → scroll
✅ 038_incorrect_10 → scroll
✅ 039_correct_10 → scroll
✅ 039_incorrect_10 → scroll
✅ 040_correct_10 → like
✅ 040_incorrect_10 → scroll
✅ 041_correct_10 → scroll
✅ 041_incorrect_10 → scroll
✅ 042_correct_10 → like
✅ 042_incorrect_10 → scroll
✅ 043_correct_10 → like
✅ 043_incorrect_10 → scroll
✅ 044_correct_10 → like
✅ 044_incorrect_10 → scroll
✅ 045_correct_10 → like
✅ 045_incorrect_10 → scroll
✅ 046_correct_10 → like
✅ 046_incorrect_10 → scroll
✅ 047_correct_10 → scroll
✅ 047_incorrect_10 → scroll
✅ 048_correct_10 → like
✅ 048_incorrect_10 → scroll
✅ 049_correct_10 → scroll
✅ 049_incorrect_10 → scroll
✅ 050_correct_10 → like
✅ 050_incorrect_10 → scroll
✅ 051_correct_10 → like
✅ 051_incorrect_10 → scroll
✅ 052_correct_10 → like
✅ 052_incorrect_10 → scroll
✅ 053_correct_10 → like
✅ 053_incorrect_10 → scroll
✅ 054_correct_10 → scroll
✅ 054_incorrect_10 → scroll
✅ 055_correct_10 → scroll
✅ 055_incorrect_10 → scroll
✅ 056_correct_10 → scroll
✅ 056_incorrect_10 → scroll
✅ 057_correct_10 → scroll
✅ 057_incorrect_10 → scroll
✅ 058_correct_10 → like
✅ 058_incorrect_10 → scroll
✅ 059_correct_10 → scroll
✅ 059_incorrect_10 → scroll
✅ 060_correct_10 → like
✅ 060_incorrect_10 → scroll
✅ 061_correct_10 → like
✅ 061_incorrect_10 → scroll
✅ 062_correct_10 → like
✅ 062_incorrect_10 → scroll
✅ 063_correct_10 → like
✅ 063_incorrect_10 → scroll
✅ 064_correct_10 → like
✅ 064_incorrect_10 → scroll
✅ 065_correct_10 → scroll
✅ 065_incorrect_10 → scroll
✅ 066_correct_10 → like
✅ 066_incorrect_10 → scroll
✅ 067_correct_10 → like
✅ 067_incorrect_10 → scroll
✅ 068_correct_10 → scroll
✅ 068_incorrect_10 → scroll
✅ 069_correct_10 → like
✅ 069_incorrect_10 → scroll
✅ 070_correct_10 → like
✅ 070_incorrect_10 → scroll
✅ 071_correct_10 → like
✅ 071_incorrect_10 → scroll
✅ 072_correct_10 → scroll
✅ 072_incorrect_10 → scroll
✅ 073_correct_10 → scroll
✅ 073_incorrect_10 → scroll
✅ 074_correct_10 → like
✅ 074_incorrect_10 → scroll
✅ 075_correct_10 → like
✅ 075_incorrect_10 → scroll
✅ 076_correct_10 → like
✅ 076_incorrect_10 → scroll
✅ 077_correct_10 → scroll
✅ 077_incorrect_10 → scroll
✅ 078_correct_10 → like
✅ 078_incorrect_10 → scroll
✅ 079_correct_10 → like
✅ 079_incorrect_10 → scroll
✅ 080_correct_10 → like
✅ 080_incorrect_10 → scroll
✅ 081_correct_10 → like
✅ 081_incorrect_10 → scroll
✅ 082_correct_10 → like
✅ 082_incorrect_10 → scroll
✅ 083_correct_10 → like
✅ 083_incorrect_10 → scroll
✅ 084_correct_10 → like
✅ 084_incorrect_10 → scroll
✅ 085_correct_10 → like
✅ 085_incorrect_10 → scroll
✅ 086_correct_10 → like
✅ 086_incorrect_10 → scroll
✅ 087_correct_10 → like
✅ 087_incorrect_10 → scroll
✅ 088_correct_10 → like
✅ 088_incorrect_10 → scroll
✅ 089_correct_10 → scroll
✅ 089_incorrect_10 → scroll
✅ 090_correct_10 → like
✅ 090_incorrect_10 → scroll
✅ 091_correct_10 → like
✅ 091_incorrect_10 → scroll
✅ 092_correct_10 → scroll
✅ 092_incorrect_10 → scroll
✅ 093_correct_10 → like
✅ 093_incorrect_10 → scroll
✅ 094_correct_10 → like
✅ 094_incorrect_10 → scroll
✅ 095_correct_10 → scroll
✅ 095_incorrect_10 → scroll
✅ 096_correct_10 → scroll
✅ 096_incorrect_10 → scroll
✅ 097_correct_10 → like
✅ 097_incorrect_10 → scroll
✅ 098_correct_10 → like
✅ 098_incorrect_10 → scroll
✅ 099_correct_10 → like
✅ 099_incorrect_10 → scroll
✅ 100_correct_10 → like
✅ 100_incorrect_10 → scroll
✅ 001_correct_100 → like
✅ 001_incorrect_100 → scroll
✅ 002_correct_100 → scroll
✅ 002_incorrect_100 → scroll
✅ 003_correct_100 → scroll
✅ 003_incorrect_100 → scroll
✅ 004_correct_100 → like
✅ 004_incorrect_100 → scroll
✅ 005_correct_100 → like
✅ 005_incorrect_100 → scroll
✅ 006_correct_100 → like
✅ 006_incorrect_100 → scroll
✅ 007_correct_100 → like
✅ 007_incorrect_100 → scroll
✅ 008_correct_100 → like
✅ 008_incorrect_100 → scroll
✅ 009_correct_100 → scroll
✅ 009_incorrect_100 → scroll
✅ 010_correct_100 → like
✅ 010_incorrect_100 → scroll
✅ 011_correct_100 → like
✅ 011_incorrect_100 → scroll
✅ 012_correct_100 → like
✅ 012_incorrect_100 → scroll
✅ 013_correct_100 → like
✅ 013_incorrect_100 → scroll
✅ 014_correct_100 → like
✅ 014_incorrect_100 → scroll
✅ 015_correct_100 → scroll
✅ 015_incorrect_100 → scroll
✅ 016_correct_100 → scroll
✅ 016_incorrect_100 → scroll
✅ 017_correct_100 → like
✅ 017_incorrect_100 → scroll
✅ 018_correct_100 → like
✅ 018_incorrect_100 → scroll
✅ 019_correct_100 → like
✅ 019_incorrect_100 → scroll
✅ 020_correct_100 → like
✅ 020_incorrect_100 → scroll
✅ 021_correct_100 → like
✅ 021_incorrect_100 → scroll
✅ 022_correct_100 → like
✅ 022_incorrect_100 → scroll
✅ 023_correct_100 → scroll
✅ 023_incorrect_100 → scroll
✅ 024_correct_100 → like
✅ 024_incorrect_100 → scroll
✅ 025_correct_100 → scroll
✅ 025_incorrect_100 → scroll
✅ 026_correct_100 → like
✅ 026_incorrect_100 → scroll
✅ 027_correct_100 → scroll
✅ 027_incorrect_100 → scroll
✅ 028_correct_100 → like
✅ 028_incorrect_100 → scroll
✅ 029_correct_100 → like
✅ 029_incorrect_100 → scroll
✅ 030_correct_100 → like
✅ 030_incorrect_100 → scroll
✅ 031_correct_100 → like
✅ 031_incorrect_100 → scroll
✅ 032_correct_100 → scroll
✅ 032_incorrect_100 → scroll
✅ 033_correct_100 → like
✅ 033_incorrect_100 → scroll
✅ 034_correct_100 → like
✅ 034_incorrect_100 → scroll
✅ 035_correct_100 → like
✅ 035_incorrect_100 → scroll
✅ 036_correct_100 → like
✅ 036_incorrect_100 → scroll
✅ 037_correct_100 → like
✅ 037_incorrect_100 → scroll
✅ 038_correct_100 → scroll
✅ 038_incorrect_100 → scroll
✅ 039_correct_100 → scroll
✅ 039_incorrect_100 → scroll
✅ 040_correct_100 → like
✅ 040_incorrect_100 → scroll
✅ 041_correct_100 → like
✅ 041_incorrect_100 → scroll
✅ 042_correct_100 → like
✅ 042_incorrect_100 → scroll
✅ 043_correct_100 → like
✅ 043_incorrect_100 → scroll
✅ 044_correct_100 → like
✅ 044_incorrect_100 → scroll
✅ 045_correct_100 → like
✅ 045_incorrect_100 → scroll
✅ 046_correct_100 → like
✅ 046_incorrect_100 → scroll
✅ 047_correct_100 → like
✅ 047_incorrect_100 → scroll
✅ 048_correct_100 → like
✅ 048_incorrect_100 → scroll
✅ 049_correct_100 → scroll
✅ 049_incorrect_100 → scroll
✅ 050_correct_100 → like
✅ 050_incorrect_100 → scroll
✅ 051_correct_100 → like
✅ 051_incorrect_100 → scroll
✅ 052_correct_100 → like
✅ 052_incorrect_100 → scroll
✅ 053_correct_100 → scroll
✅ 053_incorrect_100 → scroll
✅ 054_correct_100 → scroll
✅ 054_incorrect_100 → scroll
✅ 055_correct_100 → like
✅ 055_incorrect_100 → scroll
✅ 056_correct_100 → scroll
✅ 056_incorrect_100 → scroll
✅ 057_correct_100 → like
✅ 057_incorrect_100 → scroll
✅ 058_correct_100 → like
✅ 058_incorrect_100 → scroll
✅ 059_correct_100 → scroll
✅ 059_incorrect_100 → scroll
✅ 060_correct_100 → like
✅ 060_incorrect_100 → scroll
✅ 061_correct_100 → like
✅ 061_incorrect_100 → scroll
✅ 062_correct_100 → like
✅ 062_incorrect_100 → scroll
✅ 063_correct_100 → like
✅ 063_incorrect_100 → scroll
✅ 064_correct_100 → like
✅ 064_incorrect_100 → scroll
✅ 065_correct_100 → like
✅ 065_incorrect_100 → scroll
✅ 066_correct_100 → like
✅ 066_incorrect_100 → scroll
✅ 067_correct_100 → like
✅ 067_incorrect_100 → scroll
✅ 068_correct_100 → like
✅ 068_incorrect_100 → scroll
✅ 069_correct_100 → like
✅ 069_incorrect_100 → scroll
✅ 070_correct_100 → like
✅ 070_incorrect_100 → scroll
✅ 071_correct_100 → like
✅ 071_incorrect_100 → scroll
✅ 072_correct_100 → scroll
✅ 072_incorrect_100 → scroll
✅ 073_correct_100 → scroll
✅ 073_incorrect_100 → scroll
✅ 074_correct_100 → like
✅ 074_incorrect_100 → scroll
✅ 075_correct_100 → like
✅ 075_incorrect_100 → scroll
✅ 076_correct_100 → like
✅ 076_incorrect_100 → scroll
✅ 077_correct_100 → like
✅ 077_incorrect_100 → scroll
✅ 078_correct_100 → scroll
✅ 078_incorrect_100 → scroll
✅ 079_correct_100 → like
✅ 079_incorrect_100 → scroll
✅ 080_correct_100 → like
✅ 080_incorrect_100 → scroll
✅ 081_correct_100 → like
✅ 081_incorrect_100 → scroll
✅ 082_correct_100 → like
✅ 082_incorrect_100 → scroll
✅ 083_correct_100 → like
✅ 083_incorrect_100 → scroll
✅ 084_correct_100 → like
✅ 084_incorrect_100 → scroll
✅ 085_correct_100 → like
✅ 085_incorrect_100 → scroll
✅ 086_correct_100 → like
✅ 086_incorrect_100 → scroll
✅ 087_correct_100 → like
✅ 087_incorrect_100 → scroll
✅ 088_correct_100 → like
✅ 088_incorrect_100 → scroll
✅ 089_correct_100 → like
✅ 089_incorrect_100 → scroll
✅ 090_correct_100 → like
✅ 090_incorrect_100 → scroll
✅ 091_correct_100 → like
✅ 091_incorrect_100 → scroll
✅ 092_correct_100 → scroll
✅ 092_incorrect_100 → scroll
✅ 093_correct_100 → like
✅ 093_incorrect_100 → scroll
✅ 094_correct_100 → like
✅ 094_incorrect_100 → scroll
✅ 095_correct_100 → like
✅ 095_incorrect_100 → scroll
✅ 096_correct_100 → like
✅ 096_incorrect_100 → like
✅ 097_correct_100 → like
✅ 097_incorrect_100 → scroll
✅ 098_correct_100 → like
✅ 098_incorrect_100 → scroll
✅ 099_correct_100 → like
✅ 099_incorrect_100 → scroll
✅ 100_correct_100 → like
✅ 100_incorrect_100 → scroll
✅ 001_correct_1000 → scroll
✅ 001_incorrect_1000 → scroll
✅ 002_correct_1000 → scroll
✅ 002_incorrect_1000 → scroll
✅ 003_correct_1000 → like
✅ 003_incorrect_1000 → scroll
✅ 004_correct_1000 → like
✅ 004_incorrect_1000 → scroll
✅ 005_correct_1000 → like
✅ 005_incorrect_1000 → scroll
✅ 006_correct_1000 → like
✅ 006_incorrect_1000 → scroll
✅ 007_correct_1000 → like
✅ 007_incorrect_1000 → scroll
✅ 008_correct_1000 → like
✅ 008_incorrect_1000 → scroll
✅ 009_correct_1000 → like
✅ 009_incorrect_1000 → scroll
✅ 010_correct_1000 → like
✅ 010_incorrect_1000 → scroll
✅ 011_correct_1000 → like
✅ 011_incorrect_1000 → scroll
✅ 012_correct_1000 → like
✅ 012_incorrect_1000 → scroll
✅ 013_correct_1000 → like
✅ 013_incorrect_1000 → scroll
✅ 014_correct_1000 → like
✅ 014_incorrect_1000 → scroll
✅ 015_correct_1000 → scroll
✅ 015_incorrect_1000 → scroll
✅ 016_correct_1000 → scroll
✅ 016_incorrect_1000 → scroll
✅ 017_correct_1000 → like
✅ 017_incorrect_1000 → scroll
✅ 018_correct_1000 → like
✅ 018_incorrect_1000 → scroll
✅ 019_correct_1000 → like
✅ 019_incorrect_1000 → scroll
✅ 020_correct_1000 → like
✅ 020_incorrect_1000 → scroll
✅ 021_correct_1000 → scroll
✅ 021_incorrect_1000 → scroll
✅ 022_correct_1000 → like
✅ 022_incorrect_1000 → scroll
✅ 023_correct_1000 → scroll
✅ 023_incorrect_1000 → scroll
✅ 024_correct_1000 → like
✅ 024_incorrect_1000 → scroll
✅ 025_correct_1000 → like
✅ 025_incorrect_1000 → scroll
✅ 026_correct_1000 → like
✅ 026_incorrect_1000 → scroll
✅ 027_correct_1000 → scroll
✅ 027_incorrect_1000 → scroll
✅ 028_correct_1000 → like
✅ 028_incorrect_1000 → scroll
✅ 029_correct_1000 → like
✅ 029_incorrect_1000 → scroll
✅ 030_correct_1000 → like
✅ 030_incorrect_1000 → scroll
✅ 031_correct_1000 → like
✅ 031_incorrect_1000 → scroll
✅ 032_correct_1000 → like
✅ 032_incorrect_1000 → scroll
✅ 033_correct_1000 → like
✅ 033_incorrect_1000 → scroll
✅ 034_correct_1000 → like
✅ 034_incorrect_1000 → scroll
✅ 035_correct_1000 → like
✅ 035_incorrect_1000 → scroll
✅ 036_correct_1000 → like
✅ 036_incorrect_1000 → scroll
✅ 037_correct_1000 → like
✅ 037_incorrect_1000 → scroll
✅ 038_correct_1000 → scroll
✅ 038_incorrect_1000 → scroll
✅ 039_correct_1000 → like
✅ 039_incorrect_1000 → scroll
✅ 040_correct_1000 → like
✅ 040_incorrect_1000 → scroll
✅ 041_correct_1000 → like
✅ 041_incorrect_1000 → scroll
✅ 042_correct_1000 → like
✅ 042_incorrect_1000 → scroll
✅ 043_correct_1000 → scroll
✅ 043_incorrect_1000 → scroll
✅ 044_correct_1000 → like
✅ 044_incorrect_1000 → scroll
✅ 045_correct_1000 → like
✅ 045_incorrect_1000 → scroll
✅ 046_correct_1000 → like
✅ 046_incorrect_1000 → scroll
✅ 047_correct_1000 → scroll
✅ 047_incorrect_1000 → scroll
✅ 048_correct_1000 → like
✅ 048_incorrect_1000 → scroll
✅ 049_correct_1000 → scroll
✅ 049_incorrect_1000 → scroll
✅ 050_correct_1000 → like
✅ 050_incorrect_1000 → scroll
✅ 051_correct_1000 → like
✅ 051_incorrect_1000 → scroll
✅ 052_correct_1000 → like
✅ 052_incorrect_1000 → scroll
✅ 053_correct_1000 → like
✅ 053_incorrect_1000 → scroll
✅ 054_correct_1000 → scroll
✅ 054_incorrect_1000 → scroll
✅ 055_correct_1000 → like
✅ 055_incorrect_1000 → scroll
✅ 056_correct_1000 → scroll
✅ 056_incorrect_1000 → scroll
✅ 057_correct_1000 → scroll
✅ 057_incorrect_1000 → scroll
✅ 058_correct_1000 → like
✅ 058_incorrect_1000 → scroll
✅ 059_correct_1000 → scroll
✅ 059_incorrect_1000 → scroll
✅ 060_correct_1000 → like
✅ 060_incorrect_1000 → scroll
✅ 061_correct_1000 → like
✅ 061_incorrect_1000 → scroll
✅ 062_correct_1000 → like
✅ 062_incorrect_1000 → scroll
✅ 063_correct_1000 → like
✅ 063_incorrect_1000 → scroll
✅ 064_correct_1000 → like
✅ 064_incorrect_1000 → scroll
✅ 065_correct_1000 → like
✅ 065_incorrect_1000 → scroll
✅ 066_correct_1000 → like
✅ 066_incorrect_1000 → scroll
✅ 067_correct_1000 → like
✅ 067_incorrect_1000 → like
✅ 068_correct_1000 → like
✅ 068_incorrect_1000 → scroll
✅ 069_correct_1000 → like
✅ 069_incorrect_1000 → scroll
✅ 070_correct_1000 → like
✅ 070_incorrect_1000 → scroll
✅ 071_correct_1000 → like
✅ 071_incorrect_1000 → scroll
✅ 072_correct_1000 → scroll
✅ 072_incorrect_1000 → scroll
✅ 073_correct_1000 → scroll
✅ 073_incorrect_1000 → scroll
✅ 074_correct_1000 → like
✅ 074_incorrect_1000 → scroll
✅ 075_correct_1000 → like
✅ 075_incorrect_1000 → scroll
✅ 076_correct_1000 → like
✅ 076_incorrect_1000 → scroll
✅ 077_correct_1000 → like
✅ 077_incorrect_1000 → scroll
✅ 078_correct_1000 → like
✅ 078_incorrect_1000 → scroll
✅ 079_correct_1000 → like
✅ 079_incorrect_1000 → scroll
✅ 080_correct_1000 → like
✅ 080_incorrect_1000 → scroll
✅ 081_correct_1000 → like
✅ 081_incorrect_1000 → scroll
✅ 082_correct_1000 → like
✅ 082_incorrect_1000 → scroll
✅ 083_correct_1000 → scroll
✅ 083_incorrect_1000 → scroll
✅ 084_correct_1000 → like
✅ 084_incorrect_1000 → scroll
✅ 085_correct_1000 → like
✅ 085_incorrect_1000 → scroll
✅ 086_correct_1000 → like
✅ 086_incorrect_1000 → scroll
✅ 087_correct_1000 → like
✅ 087_incorrect_1000 → scroll
✅ 088_correct_1000 → like
✅ 088_incorrect_1000 → scroll
✅ 089_correct_1000 → like
✅ 089_incorrect_1000 → scroll
✅ 090_correct_1000 → like
✅ 090_incorrect_1000 → scroll
✅ 091_correct_1000 → like
✅ 091_incorrect_1000 → scroll
✅ 092_correct_1000 → scroll
✅ 092_incorrect_1000 → scroll
✅ 093_correct_1000 → like
✅ 093_incorrect_1000 → scroll
✅ 094_correct_1000 → like
✅ 094_incorrect_1000 → scroll
✅ 095_correct_1000 → like
✅ 095_incorrect_1000 → scroll
✅ 096_correct_1000 → like
✅ 096_incorrect_1000 → like
✅ 097_correct_1000 → like
✅ 097_incorrect_1000 → scroll
✅ 098_correct_1000 → like
✅ 098_incorrect_1000 → scroll
✅ 099_correct_1000 → like
✅ 099_incorrect_1000 → scroll
✅ 100_correct_1000 → like
✅ 100_incorrect_1000 → scroll
✅ 001_correct_10000 → like
✅ 001_incorrect_10000 → scroll
✅ 002_correct_10000 → scroll
✅ 002_incorrect_10000 → scroll
✅ 003_correct_10000 → like
✅ 003_incorrect_10000 → scroll
✅ 004_correct_10000 → like
✅ 004_incorrect_10000 → scroll
✅ 005_correct_10000 → like
✅ 005_incorrect_10000 → scroll
✅ 006_correct_10000 → like
✅ 006_incorrect_10000 → scroll
✅ 007_correct_10000 → like
✅ 007_incorrect_10000 → scroll
✅ 008_correct_10000 → like
✅ 008_incorrect_10000 → scroll
✅ 009_correct_10000 → like
✅ 009_incorrect_10000 → scroll
✅ 010_correct_10000 → like
✅ 010_incorrect_10000 → like
✅ 011_correct_10000 → like
✅ 011_incorrect_10000 → scroll
✅ 012_correct_10000 → like
✅ 012_incorrect_10000 → scroll
✅ 013_correct_10000 → like
✅ 013_incorrect_10000 → scroll
✅ 014_correct_10000 → like
✅ 014_incorrect_10000 → scroll
✅ 015_correct_10000 → like
✅ 015_incorrect_10000 → scroll
✅ 016_correct_10000 → scroll
✅ 016_incorrect_10000 → scroll
✅ 017_correct_10000 → like
✅ 017_incorrect_10000 → scroll
✅ 018_correct_10000 → like
✅ 018_incorrect_10000 → scroll
✅ 019_correct_10000 → like
✅ 019_incorrect_10000 → scroll
✅ 020_correct_10000 → like
✅ 020_incorrect_10000 → like
✅ 021_correct_10000 → scroll
✅ 021_incorrect_10000 → scroll
✅ 022_correct_10000 → like
✅ 022_incorrect_10000 → scroll
✅ 023_correct_10000 → like
✅ 023_incorrect_10000 → scroll
✅ 024_correct_10000 → like
✅ 024_incorrect_10000 → scroll
✅ 025_correct_10000 → like
✅ 025_incorrect_10000 → scroll
✅ 026_correct_10000 → like
✅ 026_incorrect_10000 → scroll
✅ 027_correct_10000 → scroll
✅ 027_incorrect_10000 → scroll
✅ 028_correct_10000 → like
✅ 028_incorrect_10000 → scroll
✅ 029_correct_10000 → like
✅ 029_incorrect_10000 → scroll
✅ 030_correct_10000 → like
✅ 030_incorrect_10000 → like
✅ 031_correct_10000 → like
✅ 031_incorrect_10000 → scroll
✅ 032_correct_10000 → like
✅ 032_incorrect_10000 → scroll
✅ 033_correct_10000 → scroll
✅ 033_incorrect_10000 → scroll
✅ 034_correct_10000 → like
✅ 034_incorrect_10000 → scroll
✅ 035_correct_10000 → like
✅ 035_incorrect_10000 → scroll
✅ 036_correct_10000 → like
✅ 036_incorrect_10000 → scroll
✅ 037_correct_10000 → like
✅ 037_incorrect_10000 → like
✅ 038_correct_10000 → like
✅ 038_incorrect_10000 → scroll
✅ 039_correct_10000 → like
✅ 039_incorrect_10000 → like
✅ 040_correct_10000 → like
✅ 040_incorrect_10000 → scroll
✅ 041_correct_10000 → like
✅ 041_incorrect_10000 → scroll
✅ 042_correct_10000 → like
✅ 042_incorrect_10000 → scroll
✅ 043_correct_10000 → like
✅ 043_incorrect_10000 → scroll
✅ 044_correct_10000 → like
✅ 044_incorrect_10000 → scroll
✅ 045_correct_10000 → like
✅ 045_incorrect_10000 → scroll
✅ 046_correct_10000 → like
✅ 046_incorrect_10000 → scroll
✅ 047_correct_10000 → like
✅ 047_incorrect_10000 → scroll
✅ 048_correct_10000 → like
✅ 048_incorrect_10000 → scroll
✅ 049_correct_10000 → like
✅ 049_incorrect_10000 → scroll
✅ 050_correct_10000 → like
✅ 050_incorrect_10000 → scroll
✅ 051_correct_10000 → like
✅ 051_incorrect_10000 → scroll
✅ 052_correct_10000 → like
✅ 052_incorrect_10000 → scroll
✅ 053_correct_10000 → like
✅ 053_incorrect_10000 → scroll
✅ 054_correct_10000 → like
✅ 054_incorrect_10000 → scroll
✅ 055_correct_10000 → like
✅ 055_incorrect_10000 → scroll
✅ 056_correct_10000 → like
✅ 056_incorrect_10000 → scroll
✅ 057_correct_10000 → like
✅ 057_incorrect_10000 → scroll
✅ 058_correct_10000 → like
✅ 058_incorrect_10000 → scroll
✅ 059_correct_10000 → like
✅ 059_incorrect_10000 → scroll
✅ 060_correct_10000 → like
✅ 060_incorrect_10000 → scroll
✅ 061_correct_10000 → like
✅ 061_incorrect_10000 → scroll
✅ 062_correct_10000 → like
✅ 062_incorrect_10000 → scroll
✅ 063_correct_10000 → like
✅ 063_incorrect_10000 → scroll

# Likes-only with noise A/B testing

In [33]:
"""
import os
os.chdir('/home/jovyan/conformity-llms-facebook-posts/benchmarking')
!unzip correct/remy-ashford/correct_likes_only_noise.zip -d correct/remy-ashford/metrics/likes_only_noise
!unzip incorrect/remy-ashford/incorrect_likes_only_noise.zip -d incorrect/remy-ashford/metrics/likes_only_noise
"""

"\nimport os\nos.chdir('/home/jovyan/conformity-llms-facebook-posts/benchmarking')\n!unzip correct/remy-ashford/correct_likes_only_noise.zip -d correct/remy-ashford/metrics/likes_only_noise\n!unzip incorrect/remy-ashford/incorrect_likes_only_noise.zip -d incorrect/remy-ashford/metrics/likes_only_noise\n"

In [34]:
import time
import importlib
import e1_utils.e1_optimized as e1
importlib.reload(e1)
from e1_utils.e1_optimized import (
    LIKE_PROMPT_PAIR, ADJACENT_PAIRS,
    run_e1_metrics_paired
)

start = time.time()

correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only_noise"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/likes_only_noise"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

run_e1_metrics_paired(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR, SEED,
                      prompt=LIKE_PROMPT_PAIR, output_filename="e1_results_likes_only_noise_paired.json", inference_fn=run_inference_qwen,
                      baseline_correct_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs",
                      baseline_incorrect_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/incorrect/PNGs")

end = time.time()
elapsed = end - start
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)
print(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")
print(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")

✅ 001_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 002_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 003_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 004_correct0_vs_incorrect0 → liked correct (answered B)
✅ 005_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 006_correct0_vs_incorrect0 → liked correct (answered B)
✅ 007_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 008_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 009_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 010_correct0_vs_incorrect0 → liked correct (answered B)
✅ 011_correct0_vs_incorrect0 → liked correct (answered B)
✅ 012_correct0_vs_incorrect0 → liked correct (answered B)
✅ 013_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 014_correct0_vs_incorrect0 → liked correct (answered B)
✅ 015_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 016_correct0_vs_incorrect0 → liked correct (answered B)
✅ 017_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 018_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 019_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 020_correct0_vs_incorrect0 → liked correct (answered B)
✅ 021_correct0_vs_incorrect0 → liked correct (answered A)
✅ 022_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 023_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 024_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 025_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 026_correct0_vs_incorrect0 → liked correct (answered B)
✅ 027_correct0_vs_incorrect0 → liked correct (answered B)
✅ 028_correct0_vs_incorrect0 → liked correct (answered B)
✅ 029_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 030_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 031_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 032_correct0_vs_incorrect0 → liked correct (answered B)
✅ 033_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 034_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 035_correct0_vs_incorrect0 → liked correct (answered B)
✅ 036_correct0_vs_incorrect0 → liked correct (answered B)
✅ 037_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 038_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 039_correct0_vs_incorrect0 → liked correct (answered B)
✅ 040_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 041_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 042_correct0_vs_incorrect0 → liked correct (answered B)
✅ 043_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 044_correct0_vs_incorrect0 → liked correct (answered B)
✅ 045_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 046_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 047_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 048_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 049_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 050_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 051_correct0_vs_incorrect0 → liked correct (answered B)
✅ 052_correct0_vs_incorrect0 → liked correct (answered B)
✅ 053_correct0_vs_incorrect0 → liked correct (answered B)
✅ 054_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 055_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 056_correct0_vs_incorrect0 → liked correct (answered A)
✅ 057_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 058_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 059_correct0_vs_incorrect0 → liked correct (answered B)
✅ 060_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 061_correct0_vs_incorrect0 → liked correct (answered B)
✅ 062_correct0_vs_incorrect0 → liked correct (answered B)
✅ 063_correct0_vs_incorrect0 → liked correct (answered B)
✅ 064_correct0_vs_incorrect0 → liked correct (answered B)
✅ 065_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 066_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 067_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 068_correct0_vs_incorrect0 → liked correct (answered B)
✅ 069_correct0_vs_incorrect0 → liked correct (answered B)
✅ 070_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 071_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 072_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 073_correct0_vs_incorrect0 → liked correct (answered B)
✅ 074_correct0_vs_incorrect0 → liked correct (answered B)
✅ 075_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 076_correct0_vs_incorrect0 → liked correct (answered B)
✅ 077_correct0_vs_incorrect0 → liked correct (answered B)
✅ 078_correct0_vs_incorrect0 → liked correct (answered B)
✅ 079_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 080_correct0_vs_incorrect0 → liked correct (answered B)
✅ 081_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 082_correct0_vs_incorrect0 → liked correct (answered B)
✅ 083_correct0_vs_incorrect0 → liked correct (answered B)
✅ 084_correct0_vs_incorrect0 → liked correct (answered B)
✅ 085_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 086_correct0_vs_incorrect0 → liked correct (answered B)
✅ 087_correct0_vs_incorrect0 → liked correct (answered B)
✅ 088_correct0_vs_incorrect0 → liked correct (answered B)
✅ 089_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 090_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 091_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 092_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 093_correct0_vs_incorrect0 → liked correct (answered B)
✅ 094_correct0_vs_incorrect0 → liked correct (answered B)
✅ 095_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 096_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 097_correct0_vs_incorrect0 → liked incorrect (answered B)
✅ 098_correct0_vs_incorrect0 → liked correct (answered B)
✅ 099_correct0_vs_incorrect0 → liked correct (answered B)
✅ 100_correct0_vs_incorrect0 → liked correct (answered B)
✅ 001_correct0_vs_incorrect10 → liked correct (answered B)
✅ 002_correct0_vs_incorrect10 → liked correct (answered B)
✅ 003_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 004_correct0_vs_incorrect10 → liked correct (answered B)
✅ 005_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 006_correct0_vs_incorrect10 → liked correct (answered B)
✅ 007_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 008_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 009_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 010_correct0_vs_incorrect10 → liked correct (answered B)
✅ 011_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 012_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 013_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 014_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 015_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 016_correct0_vs_incorrect10 → liked correct (answered B)
✅ 017_correct0_vs_incorrect10 → liked correct (answered B)
✅ 018_correct0_vs_incorrect10 → liked correct (answered B)
✅ 019_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 020_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 021_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 022_correct0_vs_incorrect10 → liked correct (answered B)
✅ 023_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 024_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 025_correct0_vs_incorrect10 → liked correct (answered B)
✅ 026_correct0_vs_incorrect10 → liked correct (answered B)
✅ 027_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 028_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 029_correct0_vs_incorrect10 → liked correct (answered B)
✅ 030_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 031_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 032_correct0_vs_incorrect10 → liked correct (answered B)
✅ 033_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 034_correct0_vs_incorrect10 → liked correct (answered B)
✅ 035_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 036_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 037_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 038_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 039_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 040_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 041_correct0_vs_incorrect10 → liked correct (answered B)
✅ 042_correct0_vs_incorrect10 → liked correct (answered B)
✅ 043_correct0_vs_incorrect10 → liked correct (answered B)
✅ 044_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 045_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 046_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 047_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 048_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 049_correct0_vs_incorrect10 → liked correct (answered B)
✅ 050_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 051_correct0_vs_incorrect10 → liked correct (answered B)
✅ 052_correct0_vs_incorrect10 → liked correct (answered B)
✅ 053_correct0_vs_incorrect10 → liked correct (answered B)
✅ 054_correct0_vs_incorrect10 → liked correct (answered B)
✅ 055_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 056_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 057_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 058_correct0_vs_incorrect10 → liked correct (answered B)
✅ 059_correct0_vs_incorrect10 → liked correct (answered B)
✅ 060_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 061_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 062_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 063_correct0_vs_incorrect10 → liked correct (answered B)
✅ 064_correct0_vs_incorrect10 → liked correct (answered B)
✅ 065_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 066_correct0_vs_incorrect10 → liked correct (answered B)
✅ 067_correct0_vs_incorrect10 → liked correct (answered B)
✅ 068_correct0_vs_incorrect10 → liked correct (answered B)
✅ 069_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 070_correct0_vs_incorrect10 → liked correct (answered B)
✅ 071_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 072_correct0_vs_incorrect10 → liked correct (answered B)
✅ 073_correct0_vs_incorrect10 → liked correct (answered B)
✅ 074_correct0_vs_incorrect10 → liked correct (answered B)
✅ 075_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 076_correct0_vs_incorrect10 → liked correct (answered B)
✅ 077_correct0_vs_incorrect10 → liked correct (answered B)
✅ 078_correct0_vs_incorrect10 → liked correct (answered B)
✅ 079_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 080_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 081_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 082_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 083_correct0_vs_incorrect10 → liked correct (answered B)
✅ 084_correct0_vs_incorrect10 → liked correct (answered B)
✅ 085_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 086_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 087_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 088_correct0_vs_incorrect10 → liked correct (answered B)
✅ 089_correct0_vs_incorrect10 → liked correct (answered B)
✅ 090_correct0_vs_incorrect10 → liked correct (answered B)
✅ 091_correct0_vs_incorrect10 → liked correct (answered B)
✅ 092_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 093_correct0_vs_incorrect10 → liked correct (answered B)
✅ 094_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 095_correct0_vs_incorrect10 → liked correct (answered B)
✅ 096_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 097_correct0_vs_incorrect10 → liked incorrect (answered B)
✅ 098_correct0_vs_incorrect10 → liked correct (answered B)
✅ 099_correct0_vs_incorrect10 → liked correct (answered B)
✅ 100_correct0_vs_incorrect10 → liked correct (answered B)
✅ 001_correct0_vs_incorrect100 → liked correct (answered B)
✅ 002_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 003_correct0_vs_incorrect100 → liked correct (answered B)
✅ 004_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 005_correct0_vs_incorrect100 → liked correct (answered B)
✅ 006_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 007_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 008_correct0_vs_incorrect100 → liked correct (answered B)
✅ 009_correct0_vs_incorrect100 → liked correct (answered B)
✅ 010_correct0_vs_incorrect100 → liked correct (answered B)
✅ 011_correct0_vs_incorrect100 → liked correct (answered B)
✅ 012_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 013_correct0_vs_incorrect100 → liked correct (answered B)
✅ 014_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 015_correct0_vs_incorrect100 → liked correct (answered B)
✅ 016_correct0_vs_incorrect100 → liked correct (answered B)
✅ 017_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 018_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 019_correct0_vs_incorrect100 → liked correct (answered B)
✅ 020_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 021_correct0_vs_incorrect100 → liked correct (answered B)
✅ 022_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 023_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 024_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 025_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 026_correct0_vs_incorrect100 → liked correct (answered B)
✅ 027_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 028_correct0_vs_incorrect100 → liked correct (answered B)
✅ 029_correct0_vs_incorrect100 → liked correct (answered B)
✅ 030_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 031_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 032_correct0_vs_incorrect100 → liked correct (answered B)
✅ 033_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 034_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 035_correct0_vs_incorrect100 → liked correct (answered B)
✅ 036_correct0_vs_incorrect100 → liked correct (answered B)
✅ 037_correct0_vs_incorrect100 → liked correct (answered B)
✅ 038_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 039_correct0_vs_incorrect100 → liked correct (answered B)
✅ 040_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 041_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 042_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 043_correct0_vs_incorrect100 → liked correct (answered B)
✅ 044_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 045_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 046_correct0_vs_incorrect100 → liked correct (answered B)
✅ 047_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 048_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 049_correct0_vs_incorrect100 → liked correct (answered B)
✅ 050_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 051_correct0_vs_incorrect100 → liked correct (answered B)
✅ 052_correct0_vs_incorrect100 → liked correct (answered B)
✅ 053_correct0_vs_incorrect100 → liked correct (answered B)
✅ 054_correct0_vs_incorrect100 → liked correct (answered B)
✅ 055_correct0_vs_incorrect100 → liked correct (answered B)
✅ 056_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 057_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 058_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 059_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 060_correct0_vs_incorrect100 → liked correct (answered B)
✅ 061_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 062_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 063_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 064_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 065_correct0_vs_incorrect100 → liked correct (answered B)
✅ 066_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 067_correct0_vs_incorrect100 → liked correct (answered B)
✅ 068_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 069_correct0_vs_incorrect100 → liked correct (answered B)
✅ 070_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 071_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 072_correct0_vs_incorrect100 → liked correct (answered B)
✅ 073_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 074_correct0_vs_incorrect100 → liked correct (answered B)
✅ 075_correct0_vs_incorrect100 → liked correct (answered B)
✅ 076_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 077_correct0_vs_incorrect100 → liked correct (answered B)
✅ 078_correct0_vs_incorrect100 → liked correct (answered B)
✅ 079_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 080_correct0_vs_incorrect100 → liked correct (answered B)
✅ 081_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 082_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 083_correct0_vs_incorrect100 → liked correct (answered B)
✅ 084_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 085_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 086_correct0_vs_incorrect100 → liked correct (answered B)
✅ 087_correct0_vs_incorrect100 → liked correct (answered B)
✅ 088_correct0_vs_incorrect100 → liked correct (answered B)
✅ 089_correct0_vs_incorrect100 → liked correct (answered B)
✅ 090_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 091_correct0_vs_incorrect100 → liked correct (answered B)
✅ 092_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 093_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 094_correct0_vs_incorrect100 → liked correct (answered B)
✅ 095_correct0_vs_incorrect100 → liked correct (answered B)
✅ 096_correct0_vs_incorrect100 → liked correct (answered B)
✅ 097_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 098_correct0_vs_incorrect100 → liked correct (answered B)
✅ 099_correct0_vs_incorrect100 → liked correct (answered B)
✅ 100_correct0_vs_incorrect100 → liked incorrect (answered B)
✅ 001_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 002_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 003_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 004_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 005_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 006_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 007_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 008_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 009_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 010_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 011_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 012_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 013_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 014_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 015_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 016_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 017_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 018_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 019_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 020_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 021_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 022_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 023_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 024_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 025_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 026_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 027_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 028_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 029_correct0_vs_incorrect1000 → liked incorrect (answered B)
✅ 030_correct0_vs_incorrect1000 → liked correct (answered B)
✅ 031_correct0_vs_incorrect1000 → liked incorrect (answered B)

In [35]:
end = time.time()
elapsed = end - start
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)
print(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")
print(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")

⏱ Total runtime: 0h 24m 42s
⏱ Average per pair: 0.30s

In [36]:
analyse_metrics_paired(OUTPUT_DIR, "e1_results_likes_only_noise_paired.json")

============================================================
Metrics paired A/B analysis: e1_results_likes_only_noise_paired
============================================================
=== Overall Summary ===

                      metric  value
0    overall_liked_correct_%  50.08
1  overall_liked_incorrect_%  49.92
2           invalid_answer_%   0.00

=== Liked Correct Rate per Scale Pair ===

/home/jovyan/conformity-llms-facebook-posts/experiments/e1/e1_utils/e1_analysis_optimized.py:163: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_pair = df.groupby("pair").apply(lambda g: pd.Series({

,pair,total_pairs,liked_correct_%,liked_incorrect_%,invalid_%
0,0_vs_0,100.0,46.0,54.0,0.0
1,0_vs_10,100.0,47.0,53.0,0.0
2,0_vs_100,100.0,49.0,51.0,0.0
3,0_vs_1000,100.0,41.0,59.0,0.0
4,0_vs_10000,100.0,44.0,56.0,0.0
5,0_vs_100000,100.0,54.0,46.0,0.0
6,0_vs_1000000,100.0,54.0,46.0,0.0
7,10_vs_0,100.0,50.0,50.0,0.0
8,10_vs_10,100.0,48.0,52.0,0.0
9,10_vs_100,100.0,15.0,85.0,0.0
10,10_vs_1000,100.0,9.0,91.0,0.0
11,10_vs_10000,100.0,13.0,87.0,0.0
12,10_vs_100000,100.0,0.0,100.0,0.0
13,10_vs_1000000,100.0,1.0,99.0,0.0
14,100_vs_0,100.0,56.0,44.0,0.0
15,100_vs_10,100.0,82.0,18.0,0.0
16,100_vs_100,100.0,50.0,50.0,0.0
17,100_vs_1000,100.0,9.0,91.0,0.0
18,100_vs_10000,100.0,6.0,94.0,0.0
19,100_vs_100000,100.0,15.0,85.0,0.0
20,100_vs_1000000,100.0,0.0,100.0,0.0
21,1000_vs_0,100.0,45.0,55.0,0.0
22,1000_vs_10,100.0,92.0,8.0,0.0
23,1000_vs_100,100.0,94.0,6.0,0.0
24,1000_vs_1000,100.0,49.0,51.0,0.0
25,1000_vs_10000,100.0,0.0,100.0,0.0
26,1000_vs_100000,100.0,0.0,100.0,0.0
27,1000_vs_1000000,100.0,3.0,97.0,0.0
28,10000_vs_0,100.0,47.0,53.0,0.0
29,10000_vs_10,100.0,85.0,15.0,0.0
30,10000_vs_100,100.0,96.0,4.0,0.0
31,10000_vs_1000,100.0,100.0,0.0,0.0
32,10000_vs_10000,100.0,52.0,48.0,0.0
33,10000_vs_100000,100.0,3.0,97.0,0.0
34,10000_vs_1000000,100.0,1.0,99.0,0.0
35,100000_vs_0,100.0,58.0,42.0,0.0
36,100000_vs_10,100.0,100.0,0.0,0.0
37,100000_vs_100,100.0,85.0,15.0,0.0
38,100000_vs_1000,100.0,100.0,0.0,0.0
39,100000_vs_10000,100.0,98.0,2.0,0.0
40,100000_vs_100000,100.0,51.0,49.0,0.0
41,100000_vs_1000000,100.0,10.0,90.0,0.0
42,1000000_vs_0,100.0,59.0,41.0,0.0
43,1000000_vs_10,100.0,100.0,0.0,0.0
44,1000000_vs_100,100.0,99.0,1.0,0.0
45,1000000_vs_1000,100.0,95.0,5.0,0.0
46,1000000_vs_10000,100.0,99.0,1.0,0.0
47,1000000_vs_100000,100.0,89.0,11.0,0.0
48,1000000_vs_1000000,100.0,55.0,45.0,0.0

=== Per Pair Results ===

,image,num,correct_scale,incorrect_scale,post_a_variant,post_b_variant,prompt,answer,liked_variant,pair
0,001_correct0_vs_incorrect0,001,0,0,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,0_vs_0
1,002_correct0_vs_incorrect0,002,0,0,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,0_vs_0
2,003_correct0_vs_incorrect0,003,0,0,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,0_vs_0
3,004_correct0_vs_incorrect0,004,0,0,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct,0_vs_0
4,005_correct0_vs_incorrect0,005,0,0,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,0_vs_0
...,...,...,...,...,...,...,...,...,...,...
4895,096_correct1000000_vs_incorrect1000000,096,1000000,1000000,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,1000000_vs_1000000
4896,097_correct1000000_vs_incorrect1000000,097,1000000,1000000,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct,1000000_vs_1000000
4897,098_correct1000000_vs_incorrect1000000,098,1000000,1000000,incorrect,correct,"You are shown two social media posts, Post A a...",B,correct,1000000_vs_1000000
4898,099_correct1000000_vs_incorrect1000000,099,1000000,1000000,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,1000000_vs_1000000
4899,100_correct1000000_vs_incorrect1000000,100,1000000,1000000,correct,incorrect,"You are shown two social media posts, Post A a...",B,incorrect,1000000_vs_1000000

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/experiments/e1_simple_plot_bigfont/qwen3-vl-8b/outputs/e1_analysis_likes_only_noise_paired.csv

# Likes-only with noise - correct vs. correct paired A/B

In [ ]:

import time
start = time.time()

from e1_utils.e1_optimized import run_e1_correct_vs_correct_paired

correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/likes_only_noise"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

# --- Correct vs. correct paired A/B (likes_only_noise) ---
run_e1_correct_vs_correct_paired(selected_numbers, correct_base, model, processor, device, OUTPUT_DIR, SEED,
                      prompt=LIKE_PROMPT_PAIR, output_filename="e1_results_likes_only_noise_correct_vs_correct_paired.json",
                      inference_fn=run_inference_qwen,
                      baseline_correct_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs")

end = time.time()
elapsed = end - start
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)
print(f"\n⏱ Total runtime: {hours}h {minutes}m {seconds}s")
print(f"⏱ Average per pair: {elapsed / (len(selected_numbers) * len(ADJACENT_PAIRS)):.2f}s")

✅ 001_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 002_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 003_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 004_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 005_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 006_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 007_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 008_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 009_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 010_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 011_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 012_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 013_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 014_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 015_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 016_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 017_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 018_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 019_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 020_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 021_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 022_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 023_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 024_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 025_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 026_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 027_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 028_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 029_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 030_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 031_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 032_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 033_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 034_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 035_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 036_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 037_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 038_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 039_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 040_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 041_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 042_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 043_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 044_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 045_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 046_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 047_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 048_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 049_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 050_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 051_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 052_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 053_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 054_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 055_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 056_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 057_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 058_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 059_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 060_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 061_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 062_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 063_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 064_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 065_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 066_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 067_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 068_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 069_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 070_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 071_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 072_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 073_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 074_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 075_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 076_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 077_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 078_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 079_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 080_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 081_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 082_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 083_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 084_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 085_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 086_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 087_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 088_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 089_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 090_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 091_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 092_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 093_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 094_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 095_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 096_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 097_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 098_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 099_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 100_correct0_vs_correct0 → liked scale 0 (answered A)
✅ 001_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 002_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 003_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 004_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 005_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 006_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 007_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 008_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 009_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 010_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 011_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 012_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 013_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 014_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 015_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 016_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 017_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 018_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 019_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 020_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 021_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 022_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 023_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 024_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 025_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 026_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 027_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 028_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 029_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 030_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 031_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 032_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 033_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 034_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 035_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 036_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 037_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 038_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 039_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 040_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 041_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 042_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 043_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 044_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 045_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 046_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 047_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 048_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 049_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 050_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 051_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 052_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 053_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 054_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 055_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 056_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 057_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 058_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 059_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 060_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 061_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 062_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 063_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 064_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 065_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 066_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 067_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 068_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 069_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 070_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 071_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 072_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 073_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 074_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 075_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 076_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 077_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 078_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 079_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 080_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 081_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 082_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 083_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 084_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 085_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 086_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 087_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 088_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 089_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 090_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 091_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 092_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 093_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 094_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 095_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 096_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 097_correct0_vs_correct10 → liked scale 10 (answered B)
✅ 098_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 099_correct0_vs_correct10 → liked scale 10 (answered A)
✅ 100_correct0_vs_correct10 → liked scale 0 (answered B)
✅ 001_correct0_vs_correct100 → liked scale 0 (answered B)
✅ 002_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 003_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 004_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 005_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 006_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 007_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 008_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 009_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 010_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 011_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 012_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 013_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 014_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 015_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 016_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 017_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 018_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 019_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 020_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 021_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 022_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 023_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 024_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 025_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 026_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 027_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 028_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 029_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 030_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 031_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 032_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 033_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 034_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 035_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 036_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 037_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 038_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 039_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 040_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 041_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 042_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 043_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 044_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 045_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 046_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 047_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 048_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 049_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 050_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 051_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 052_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 053_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 054_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 055_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 056_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 057_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 058_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 059_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 060_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 061_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 062_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 063_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 064_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 065_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 066_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 067_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 068_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 069_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 070_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 071_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 072_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 073_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 074_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 075_correct0_vs_correct100 → liked scale 0 (answered B)
✅ 076_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 077_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 078_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 079_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 080_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 081_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 082_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 083_correct0_vs_correct100 → liked scale 0 (answered B)
✅ 084_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 085_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 086_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 087_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 088_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 089_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 090_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 091_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 092_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 093_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 094_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 095_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 096_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 097_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 098_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 099_correct0_vs_correct100 → liked scale 100 (answered A)
✅ 100_correct0_vs_correct100 → liked scale 100 (answered B)
✅ 001_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 002_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 003_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 004_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 005_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 006_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 007_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 008_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 009_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 010_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 011_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 012_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 013_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 014_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 015_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 016_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 017_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 018_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 019_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 020_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 021_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 022_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 023_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 024_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 025_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 026_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 027_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 028_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 029_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 030_correct0_vs_correct1000 → liked scale 0 (answered B)
✅ 031_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 032_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 033_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 034_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 035_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 036_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 037_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 038_correct0_vs_correct1000 → liked scale 1000 (answered A)
✅ 039_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 040_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 041_correct0_vs_correct1000 → liked scale 1000 (answered B)
✅ 042_correct0_vs_correct1000 → liked scale 1000 (answered A)

In [ ]:

import e1_utils.e1_analysis_optimized as e1
importlib.reload(e1
                )
from e1_utils.e1_analysis_optimized import analyse_cc_paired

analyse_cc_paired(OUTPUT_DIR, "e1_results_likes_only_noise_correct_vs_correct_paired.json")

# Grids

Each grid square represents 100 individual A/B trials, where each trial corresponds to one of your 100 selected image numbers 

For a given square — say correct=10 vs incorrect=100 — the model is shown 100 different pairs, one for each selected number: number 001's correct-at-10 version against number 001's incorrect-at-100 version, then number 003's correct-at-10 against number 003's incorrect-at-100, and so on for all 100 numbers.

Each of those 100 trials produces one binary outcome — the model liked either the correct or the incorrect post. The percentage shown in the cell is simply how many of those 100 outcomes favoured the correct post, divided by 100.

In [ ]:
import e1_utils.e1_analysis_optimized as e1
importlib.reload(e1)

from e1_utils.e1_analysis_optimized import plot_ab_grid

# Likes only
#plot_ab_grid(OUTPUT_DIR, "e1_results_likes_only_paired.json",
#             title="A/B Like Decision — Likes Only (Correct % by Reaction Scale)")

plot_ab_grid(OUTPUT_DIR, "e1_results_likes_only_noise_paired.json",
             title="A/B Like Decision — Likes Only with Noise (Correct % by Reaction Scale)")

# Metrics
plot_ab_grid(OUTPUT_DIR, "e1_results_metrics_paired.json", 
             title="A/B Like Decision — Metrics (Correct % by Reaction Scale)")

In [ ]:
from e1_utils.e1_analysis_optimized import plot_ab_grid, plot_ab_diff_grid


# Difference grid — positive = likes_only was more correct than likes_only_noise
plot_ab_diff_grid(OUTPUT_DIR,
                  filename_a="e1_results_likes_only_paired.json",
                  filename_b="e1_results_likes_only_noise_paired.json",
                  title="Δ A/B Like Decision — Likes Only vs Likes Only with Noise")

**Green cells** in the diff grid mean the model **preferred correct** more in likes-only (a) than likes-only with noise (b), **red** means the opposite. 

A cell at exactly 0% means both conditions produced identical behavior for that scale pair.

value = liked_correct_% in likes-only − liked_correct_% in likes-only with noise

- Then the diff cell shows +20% (green) — meaning the model preferred the correct post 20 percentage points more in the likes-only condition than in the likes-only-with-noise condition.
  
- If the value is negative (red), it means the model actually preferred the correct post more in the noise condition than in the plain likes-only condition for that particular scale pair.
  
- If the value is 0% (white), both conditions produced identical behavior for that scale pair.

In [ ]:

import e1_utils.e1_analysis_optimized as e1
importlib.reload(e1)

from e1_utils.e1_analysis_optimized import plot_cc_grid

# Correct vs. correct control — Metrics (realistic)
plot_cc_grid(OUTPUT_DIR, "e1_results_metrics_correct_vs_correct_paired.json",
             title="Correct vs. Correct — Metrics (Chose Higher Engagement %)")

# Correct vs. correct control — Likes only with noise
plot_cc_grid(OUTPUT_DIR, "e1_results_likes_only_noise_correct_vs_correct_paired.json",
             title="Correct vs. Correct — Likes Only with Noise (Chose Higher Engagement %)")

## Two-step prompt pilot (supervisor item, 2026-08)

Tests whether making the model verify factual correctness explicitly *before* the popularity-influenced like/scroll decision improves the diagonal (competence, disparity=0). Two designs run head-to-head, diagonal cells only (7 scales x 100 images = 700 trials each, not the full 49-cell grid -- this is specifically about the diagonal, see `experiments/e1/e1_utils/e1_two_step.py` module docstring for the full rationale and why the grid is narrowed here). Compare each design's `e1_results_metrics_diagonal_twostep_*.json` diagonal accuracy against this notebook's existing single-step `e1_results_metrics_paired.json` diagonal accuracy (Section further up).

Currently pointed at the same `metrics_simple_plot_bigfont` images already used elsewhere in this notebook. If/when the font-size-adjusted ("bigfont") images are composited into full posts, swap `correct_base`/`incorrect_base` below for that directory instead.

In [ ]:
import time
from e1_utils.e1_two_step import run_e1_metrics_paired_twostep, DIAGONAL_PAIRS

correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/realistic"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/realistic"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

start = time.time()
run_e1_metrics_paired_twostep(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR, SEED,
                               design="paired_verdict", output_filename="e1_results_metrics_diagonal_twostep_paired_verdict.json",
                               inference_fn=run_inference_qwen,
                               baseline_correct_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs",
                               baseline_incorrect_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/incorrect/PNGs")
elapsed = time.time() - start
print(f"\n⏱ Total runtime: {elapsed/60:.1f} min ({elapsed / (len(selected_numbers) * len(DIAGONAL_PAIRS)):.2f}s/pair)")

In [ ]:
import time
from e1_utils.e1_two_step import run_e1_metrics_paired_twostep, DIAGONAL_PAIRS

correct_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/correct/PNGs/realistic"
incorrect_base = ROOT_DIR / "spotify_pie_plot/pie_plot_posts/metrics_simple_plot_bigfont/remy-ashford/incorrect/PNGs/realistic"
selected_numbers = [name.replace("_correct", "") for name, _ in all_images if "_correct" in name]

start = time.time()
run_e1_metrics_paired_twostep(selected_numbers, correct_base, incorrect_base, model, processor, device, OUTPUT_DIR, SEED,
                               design="isolated_verdict", output_filename="e1_results_metrics_diagonal_twostep_isolated_verdict.json",
                               inference_fn=run_inference_qwen,
                               baseline_correct_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/correct/PNGs",
                               baseline_incorrect_dir=ROOT_DIR / "spotify_pie_plot/pie_plot_posts/baselines_simple_plot_bigfont/incorrect/PNGs")
elapsed = time.time() - start
print(f"\n⏱ Total runtime: {elapsed/60:.1f} min ({elapsed / (len(selected_numbers) * len(DIAGONAL_PAIRS)):.2f}s/pair)")

In [ ]:
import json

def diagonal_accuracy(path, filter_diagonal=False):
    records = json.loads((OUTPUT_DIR / path).read_text())
    if filter_diagonal:
        records = [r for r in records if r["correct_scale"] == r["incorrect_scale"]]
    return 100 * sum(r["liked_variant"] == "correct" for r in records) / len(records), len(records)

single_pct, single_n = diagonal_accuracy("e1_results_metrics_paired.json", filter_diagonal=True)
paired_pct, paired_n = diagonal_accuracy("e1_results_metrics_diagonal_twostep_paired_verdict.json")
isolated_pct, isolated_n = diagonal_accuracy("e1_results_metrics_diagonal_twostep_isolated_verdict.json")

print(f"Single-step (existing, diagonal cells only): {single_pct:.1f}%  (n={single_n})")
print(f"Two-step, paired_verdict:                    {paired_pct:.1f}%  (n={paired_n})")
print(f"Two-step, isolated_verdict:                  {isolated_pct:.1f}%  (n={isolated_n})")