# Benchmarking findings - Original plot

# Qualitative

## Qualitative
Main question: does the model adress the discrepancy between text and visualisation in the incorrect post shown?

Original chart:
- Ministral3 14B: **yes**
- Qwen3 8B: **yes**
- Ministral3 8B: on
- Gemma4 E4B: no
- Gemma4 12B: no
- Qwen3 4B: no


Simple font:
- Gemma4 E4B: no
- Qwen3 8B: no


Bigfont:
- Gemma4 E4B: no
- Qwen3 8B: no

**Dr. Remy Ashford**
Original chart:
- Ministral3 14B: 
- Qwen3 8B: 
- Ministral3 8B:
- Gemma4 E4B: 
- Gemma4 12B: 
- Qwen3 4B: 


Simple font:
- Gemma4 E4B: 
- Qwen3 8B: 


Bigfont:
- Gemma4 E4B: 
- Qwen3 8B:

# Quantitative

In [4]:
from pathlib import Path
from utils.quanti_benchmarking_1_analysis import run_accuracy_analysis

BASE_DIR = Path().resolve()
# Updated to include "-news-" to match your folder structure
EXPERIMENT_NAME = "test-1-gn-news-extensive"

MODELS = [
    "gemma4-12b",
    "gemma-e4b",
    "ministral-3-14b",
    "ministral-3-8b",
    "qwen3-vl-4b",
    "qwen3-vl-8b"
]

for model_name in MODELS:
    print(f"\n" + "=" * 50)
    print(f" Running Accuracy Analysis for Model: {model_name} ")
    print("=" * 50)
    try:
        run_accuracy_analysis(BASE_DIR, EXPERIMENT_NAME, model_name)
    except Exception as e:
        print(f"Error processing {model_name}: {e}")

==================================================
 Running Accuracy Analysis for Model: gemma4-12b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: gemma-e4b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions         0.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  78.12
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions         0.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  78.12
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions         0.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  78.12
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions         0.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%   75.0
1  fully_correct_images_%    0.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions         0.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%   75.0
1  fully_correct_images_%    0.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions         0.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%   75.0
1  fully_correct_images_%    0.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: ministral-3-14b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  84.38
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  84.38
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  81.25
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  81.25
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  81.25
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  81.25
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: ministral-3-8b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count         0.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions        50.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,False,True,True,True,False,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,False,True,True,True,True,True,True,True,False,False,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%   75.0
1  fully_correct_images_%    0.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count         0.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions        50.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,False,True,True,True,False,True,True,True,False,False,True,True,True,True,True,True
1,001_remy_ashford_i,False,False,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%   75.0
1  fully_correct_images_%    0.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count         0.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions        50.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,False,True,True,True,False,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,False,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  71.88
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count         0.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions        50.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,False,True,True,True,False,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,False,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  71.88
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count         0.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions        50.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,False,True,True,True,False,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,False,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  71.88
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count         0.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions        50.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop         0.0
9   chart_percentages_latin         0.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,False,True,True,True,False,True,True,True,False,False,True,True,True,True,True,False
1,001_remy_ashford_i,False,False,True,True,True,True,True,True,True,False,False,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  71.88
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: qwen3-vl-4b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: qwen3-vl-8b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

============================================================
Prompt Version : v7_two_call
Prompt Text    : The chart shows Pop at 23.5% and Latin at 11.0%. The post text says 'Looks like Pop was more popular than Latin this year!'. Based only on these numbers, is the claim correct? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v7_two_call/accuracy_scores_v7_two_call.csv

============================================================
Prompt Version : v8_two_call
Prompt Text    : Pop: 23.5%. Latin: 11.0%. The post claims: 'Looks like Pop was more popular than Latin this year!'. Does the claim match which percentage is higher? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v8_two_call/accuracy_scores_v8_two_call.csv

============================================================
Prompt Version : v9_two_call
Prompt Text    : Given Pop = 23.5% and Latin = 11.0%, is the following statement true or false: 'Looks like Pop was more popular than Latin this year!'. Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v9_two_call/accuracy_scores_v9_two_call.csv

In [8]:
import pandas as pd
import numpy as np

for model in MODELS:
    question_scores = {}
    
    # 1. Collect true/false scores across v1 to v6
    for v in range(1, 7):
        file_name = f"accuracy_scores_v{v}.csv"
        file_path = (
            BASE_DIR 
            / "outputs" 
            / model 
            / "quantitative" 
            / EXPERIMENT_NAME 
            / f"v{v}" 
            / file_name
        )
        
        if file_path.exists():
            df = pd.read_csv(file_path) 
            
            # Find all the columns your script generated for individual questions
            correct_cols = [c for c in df.columns if c.endswith("_correct") and c != "all_correct"]
            
            for col in correct_cols:
                question_name = col.replace("_correct", "")
                
                # Convert boolean True/False to 100.0 / 0.0
                scores = df[col].astype(float) * 100.0
                
                if question_name not in question_scores:
                    question_scores[question_name] = []
                # Append all image scores for this version
                question_scores[question_name].extend(scores.tolist())

    # 2. Filter questions strictly below 100% average
    struggling_questions = []
    for question, scores in question_scores.items():
        if scores:  # ensure we actually found data
            avg_acc = np.mean(scores)
            if avg_acc < 100.0:
                struggling_questions.append({
                    "Question": question,
                    "Avg Accuracy (%)": round(avg_acc, 2),
                    "Total Evaluations": len(scores) # Shows total number of images x versions evaluated
                })

    # 3. Print the overview
    print(f"\n{'='*60}\n STRUGGLING QUESTIONS: {model}\n{'='*60}")
    if struggling_questions:
        summary_df = pd.DataFrame(struggling_questions).sort_values(by="Avg Accuracy (%)")
        print(summary_df.to_string(index=False))
    else:
        print("No questions under 100% accuracy found (or files missing).")

============================================================
 STRUGGLING QUESTIONS: gemma4-12b
============================================================
             Question  Avg Accuracy (%)  Total Evaluations
chart_percentages_pop               0.0                 12

============================================================
 STRUGGLING QUESTIONS: gemma-e4b
============================================================
               Question  Avg Accuracy (%)  Total Evaluations
          sad_reactions               0.0                 12
        angry_reactions               0.0                 12
chart_percentages_latin               0.0                 12
             post_claim              25.0                 12

============================================================
 STRUGGLING QUESTIONS: ministral-3-14b
============================================================
               Question  Avg Accuracy (%)  Total Evaluations
  chart_percentages_pop              0.00                 12
chart_percentages_latin              0.00                 12
             post_claim             16.67                 12

============================================================
 STRUGGLING QUESTIONS: ministral-3-8b
============================================================
               Question  Avg Accuracy (%)  Total Evaluations
            likes_count              0.00                 12
  chart_percentages_pop              0.00                 12
chart_percentages_latin              0.00                 12
             post_claim             16.67                 12
         haha_reactions             50.00                 12

============================================================
 STRUGGLING QUESTIONS: qwen3-vl-4b
============================================================
  Question  Avg Accuracy (%)  Total Evaluations
post_claim              75.0                 12

============================================================
 STRUGGLING QUESTIONS: qwen3-vl-8b
============================================================
  Question  Avg Accuracy (%)  Total Evaluations
post_claim             33.33                 12