# Benchmarking findings - Original plot

**Test 1 — test-1-gn-news-extensive (the extensive multi-question pilot)**
Asks 14 separate questions per image: profile name, profile verification, every individual engagement count (likes, comments, shares, and all 5 reaction types), the chart's two percentage values, chart colors, largest slice, and post_claim_correct (does the text match the chart). Run on only 4 images (1 gender-neutral profile + 1 "Dr." authority profile, × correct/incorrect), across 6 prompt wordings (v1–v6). Purpose: an extensive first pass to find the best-performing claim-verification wording, at the cost of a tiny sample.

**Test 2 — test-2-gn-claim-only (dedicated, zero-pressure claim check)**
Single question only: "does the post's text accurately describe the chart?" No engagement metrics shown — plain baseline images. 50 correct/50 incorrect pairs (100 images), gender-neutral profile only, same 6 wordings as Test 1, plus a two-call variant (v7–v9: extract the chart's values first, then verify the claim against them — the same two-call pattern later reused for the E1 two-step pilot). This is the true zero-social-pressure competence test.

**Test 3 — test-3-gn-percentages (perception check, not claim check)**
Reuses the exact same 50 image pairs as Test 2, but instead asks the model to read off the chart's two percentage values (Pop%, Latin%) directly — no claim judgment involved. Purpose, per the notebook's own rationale: direct comparability with Test 2 on identical images, so you can cross-reference per image ("read the percentages correctly but still got the claim wrong") — separating perception failure from reasoning failure.

**Test 4 — test-4-metrics-realistic-claim-only (claim check, with engagement now shown)**
Same single claim-verification question as Test 2, but now the post displays visible engagement metrics at 6 magnitude levels (10 → 1,000,000), with reactions distributed "realistically" (log-scaled across the 5 reaction types, approximating real engagement patterns) rather than split evenly. Purpose: does a single post's claim-verification accuracy shift once fake popularity is visible, isolated from the paired A/B framing used in the main E1 study. Worth noting for your methods section: an earlier "uniform reactions" version of this test (every reaction type set to the same count) was built and explicitly discarded as unrealistic before this log-scaled version replaced it (benchmarking/gemma4-12b-benchmarking.ipynb, cell 27, marked "old 4) ... will probably keep out because unrealistic").

# Qualitative

## Qualitative
Main question: does the model adress the discrepancy between text and visualisation in the incorrect post shown?

Original chart:
- Ministral3 14B: **yes**
- Qwen3 8B: **yes**
- Ministral3 8B: on
- Gemma4 E4B: no
- Gemma4 12B: no
- Qwen3 4B: no


Simple font:
- Gemma4 E4B: no
- Qwen3 8B: no


Bigfont:
- Gemma4 E4B: no
- Qwen3 8B: no

**Dr. Remy Ashford**
Original chart:
- Ministral3 14B: 
- Qwen3 8B: 
- Ministral3 8B:
- Gemma4 E4B: 
- Gemma4 12B: 
- Qwen3 4B: 


Simple font:
- Gemma4 E4B: 
- Qwen3 8B: 


Bigfont:
- Gemma4 E4B: 
- Qwen3 8B:

# Quantitative

## Test 1: extensive multi-question pilot

In [12]:
from pathlib import Path
from utils.quanti_benchmarking_1_analysis import run_accuracy_analysis

BASE_DIR = Path().resolve()
# Updated to include "-news-" to match your folder structure
EXPERIMENT_NAME = "test-1-gn-news-extensive"

MODELS = [
    "gemma4-12b",
    "gemma-e4b",
    "ministral-3-14b",
    "ministral-3-8b",
    "qwen3-vl-4b",
    "qwen3-vl-8b"
]

for model_name in MODELS:
    print(f"\n" + "=" * 50)
    print(f" Running Accuracy Analysis for Model: {model_name} ")
    print("=" * 50)
    try:
        run_accuracy_analysis(BASE_DIR, EXPERIMENT_NAME, model_name)
    except Exception as e:
        print(f"Error processing {model_name}: {e}")

==================================================
 Running Accuracy Analysis for Model: gemma4-12b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma4-12b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: gemma-e4b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions        50.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_c,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_i,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%   87.5
1  fully_correct_images_%    0.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions        50.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False
1,001_dr_remy_ashford_c,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_i,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%   87.5
1  fully_correct_images_%    0.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions        50.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False
2,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_c,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%   87.5
1  fully_correct_images_%    0.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions        50.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False
1,001_dr_remy_ashford_c,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False
2,001_dr_remy_ashford_i,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  84.38
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions        50.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False
2,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_i,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  84.38
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions         0.0
7           angry_reactions        50.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_c,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False
2,001_remy_ashford_i,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_i,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  84.38
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/gemma-e4b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: ministral-3-14b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-14b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: ministral-3-8b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        25.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  95.31
1  fully_correct_images_%  25.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/ministral-3-8b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: qwen3-vl-4b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        25.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  95.31
1  fully_correct_images_%  25.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-4b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

==================================================
 Running Accuracy Analysis for Model: qwen3-vl-8b
==================================================

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        50.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  96.88
1  fully_correct_images_%  50.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        75.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  98.44
1  fully_correct_images_%  75.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim        25.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  95.31
1  fully_correct_images_%  25.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim         0.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
1,001_dr_remy_ashford_c,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,001_dr_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
3,001_remy_ashford_i,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  93.75
1  fully_correct_images_%   0.00

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v6/accuracy_scores_v6.csv

============================================================
Prompt Version : v7_two_call
Prompt Text    : The chart shows Pop at 23.5% and Latin at 11.0%. The post text says 'Looks like Latin was more popular than Pop this year!'. Based only on these numbers, is the claim correct? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v7_two_call/accuracy_scores_v7_two_call.csv

============================================================
Prompt Version : v8_two_call
Prompt Text    : Pop: 23.5%. Latin: 11.0%. The post claims: 'Looks like Pop was more popular than Latin this year!'. Does the claim match which percentage is higher? Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v8_two_call/accuracy_scores_v8_two_call.csv

============================================================
Prompt Version : v9_two_call
Prompt Text    : Given Pop = 23.5% and Latin = 11.0%, is the following statement true or false: 'Looks like Latin was more popular than Pop this year!'. Reply with only 'correct' or 'incorrect'.
============================================================
=== Accuracy per question ===

                   question  accuracy_%
0               likes_count       100.0
1             comment_count       100.0
2              shares_count       100.0
3           heart_reactions       100.0
4            haha_reactions       100.0
5             wow_reactions       100.0
6             sad_reactions       100.0
7           angry_reactions       100.0
8     chart_percentages_pop       100.0
9   chart_percentages_latin       100.0
10             profile_name       100.0
11     profile_verification       100.0
12          chart_color_pop       100.0
13        chart_color_latin       100.0
14      chart_largest_slice       100.0
15               post_claim       100.0

=== Accuracy per image ===

,image,all,likes_count,comment_count,shares_count,heart_reactions,haha_reactions,wow_reactions,sad_reactions,angry_reactions,chart_percentages_pop,chart_percentages_latin,profile_name,profile_verification,chart_color_pop,chart_color_latin,chart_largest_slice,post_claim
0,001_dr_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,001_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,001_remy_ashford_i,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,001_dr_remy_ashford_c,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

=== Overall Summary ===

                   metric  value
0         mean_accuracy_%  100.0
1  fully_correct_images_%  100.0

✅ Saved to: /home/scc/miranda.barros-everett/conformity-llms-facebook-posts/benchmarking/outputs/qwen3-vl-8b/quantitative/test-1-gn-news-extensive/v9_two_call/accuracy_scores_v9_two_call.csv

In [3]:
import pandas as pd
import numpy as np

for model in MODELS:
    question_scores = {}
    
    # 1. Collect true/false scores across v1 to v6
    for v in range(1, 7):
        file_name = f"accuracy_scores_v{v}.csv"
        file_path = (
            BASE_DIR 
            / "outputs" 
            / model 
            / "quantitative" 
            / EXPERIMENT_NAME 
            / f"v{v}" 
            / file_name
        )
        
        if file_path.exists():
            df = pd.read_csv(file_path) 
            
            # Find all the columns your script generated for individual questions
            correct_cols = [c for c in df.columns if c.endswith("_correct") and c != "all_correct"]
            
            for col in correct_cols:
                question_name = col.replace("_correct", "")
                
                # Convert boolean True/False to 100.0 / 0.0
                scores = df[col].astype(float) * 100.0
                
                if question_name not in question_scores:
                    question_scores[question_name] = []
                # Append all image scores for this version
                question_scores[question_name].extend(scores.tolist())

    # 2. Filter questions strictly below 100% average
    struggling_questions = []
    for question, scores in question_scores.items():
        if scores:  # ensure we actually found data
            avg_acc = np.mean(scores)
            if avg_acc < 100.0:
                struggling_questions.append({
                    "Question": question,
                    "Avg Accuracy (%)": round(avg_acc, 2),
                    "Total Evaluations": len(scores) # Shows total number of images x versions evaluated
                })

    # 3. Print the overview
    print(f"\n{'='*60}\n STRUGGLING QUESTIONS: {model}\n{'='*60}")
    if struggling_questions:
        summary_df = pd.DataFrame(struggling_questions).sort_values(by="Avg Accuracy (%)")
        print(summary_df.to_string(index=False))
    else:
        print("No questions under 100% accuracy found (or files missing).")

============================================================
 STRUGGLING QUESTIONS: gemma4-12b
============================================================
No questions under 100% accuracy found (or files missing).

============================================================
 STRUGGLING QUESTIONS: gemma-e4b
============================================================
       Question  Avg Accuracy (%)  Total Evaluations
  sad_reactions               0.0                 24
     post_claim              25.0                 24
angry_reactions              50.0                 24

============================================================
 STRUGGLING QUESTIONS: ministral-3-14b
============================================================
  Question  Avg Accuracy (%)  Total Evaluations
post_claim             16.67                 24

============================================================
 STRUGGLING QUESTIONS: ministral-3-8b
============================================================
  Question  Avg Accuracy (%)  Total Evaluations
post_claim              12.5                 24

============================================================
 STRUGGLING QUESTIONS: qwen3-vl-4b
============================================================
  Question  Avg Accuracy (%)  Total Evaluations
post_claim             70.83                 24

============================================================
 STRUGGLING QUESTIONS: qwen3-vl-8b
============================================================
  Question  Avg Accuracy (%)  Total Evaluations
post_claim             41.67                 24

In [4]:
for model in MODELS:
    # find questions this model scored exactly 0.00% on
    question_scores = {}
    for v in range(1, 7):
        file_path = BASE_DIR / "outputs" / model / "quantitative" / EXPERIMENT_NAME / f"v{v}" / f"accuracy_scores_v{v}.csv"
        if not file_path.exists():
            continue
        df = pd.read_csv(file_path)
        correct_cols = [c for c in df.columns if c.endswith("_correct") and c != "all_correct"]
        for col in correct_cols:
            question_name = col.replace("_correct", "")
            scores = df[col].astype(float) * 100.0
            question_scores.setdefault(question_name, []).extend(scores.tolist())

    zero_questions = [q for q, scores in question_scores.items() if scores and sum(scores) == 0.0]

    print(f"\n{'='*70}\n RAW OUTPUTS FOR 0.00% CATEGORIES: {model}\n{'='*70}")
    if not zero_questions:
        print("  No categories scored exactly 0.00%.")
        continue

    for q in zero_questions:
        pred_col, true_col = f"{q}_pred", f"{q}_true"
        print(f"\n--- {q} ---")
        for v in range(1, 7):
            file_path = BASE_DIR / "outputs" / model / "quantitative" / EXPERIMENT_NAME / f"v{v}" / f"accuracy_scores_v{v}.csv"
            if not file_path.exists():
                continue
            df = pd.read_csv(file_path)
            if pred_col not in df.columns or true_col not in df.columns:
                continue
            for _, row in df.iterrows():
                print(f"  v{v} | {row['image']:22s} model said: {row[pred_col]!r:10}  ground truth: {row[true_col]!r}")

======================================================================
 RAW OUTPUTS FOR 0.00% CATEGORIES: gemma4-12b
======================================================================
  No categories scored exactly 0.00%.

======================================================================
 RAW OUTPUTS FOR 0.00% CATEGORIES: gemma-e4b
======================================================================

--- sad_reactions ---
  v1 | 001_remy_ashford_c     model said: 2           ground truth: 0
  v1 | 001_dr_remy_ashford_c  model said: 2           ground truth: 0
  v1 | 001_dr_remy_ashford_i  model said: 2           ground truth: 0
  v1 | 001_remy_ashford_i     model said: 2           ground truth: 0
  v2 | 001_remy_ashford_i     model said: 2           ground truth: 0
  v2 | 001_dr_remy_ashford_c  model said: 2           ground truth: 0
  v2 | 001_dr_remy_ashford_i  model said: 2           ground truth: 0
  v2 | 001_remy_ashford_c     model said: 2           ground truth: 0
  v3 | 001_dr_remy_ashford_i  model said: 2           ground truth: 0
  v3 | 001_remy_ashford_i     model said: 2           ground truth: 0
  v3 | 001_remy_ashford_c     model said: 2           ground truth: 0
  v3 | 001_dr_remy_ashford_c  model said: 2           ground truth: 0
  v4 | 001_remy_ashford_i     model said: 2           ground truth: 0
  v4 | 001_dr_remy_ashford_c  model said: 2           ground truth: 0
  v4 | 001_dr_remy_ashford_i  model said: 2           ground truth: 0
  v4 | 001_remy_ashford_c     model said: 2           ground truth: 0
  v5 | 001_dr_remy_ashford_c  model said: 2           ground truth: 0
  v5 | 001_remy_ashford_i     model said: 2           ground truth: 0
  v5 | 001_remy_ashford_c     model said: 2           ground truth: 0
  v5 | 001_dr_remy_ashford_i  model said: 2           ground truth: 0
  v6 | 001_dr_remy_ashford_c  model said: 2           ground truth: 0
  v6 | 001_remy_ashford_c     model said: 2           ground truth: 0
  v6 | 001_remy_ashford_i     model said: 2           ground truth: 0
  v6 | 001_dr_remy_ashford_i  model said: 2           ground truth: 0

======================================================================
 RAW OUTPUTS FOR 0.00% CATEGORIES: ministral-3-14b
======================================================================
  No categories scored exactly 0.00%.

======================================================================
 RAW OUTPUTS FOR 0.00% CATEGORIES: ministral-3-8b
======================================================================
  No categories scored exactly 0.00%.

======================================================================
 RAW OUTPUTS FOR 0.00% CATEGORIES: qwen3-vl-4b
======================================================================
  No categories scored exactly 0.00%.

======================================================================
 RAW OUTPUTS FOR 0.00% CATEGORIES: qwen3-vl-8b
======================================================================
  No categories scored exactly 0.00%.

In [5]:
import pandas as pd
import numpy as np

claim_accuracy_rows = []

for model in MODELS:
    variant_scores = {"correct": [], "incorrect": []}

    for v in range(1, 7):
        file_path = (
            BASE_DIR
            / "outputs"
            / model
            / "quantitative"
            / EXPERIMENT_NAME
            / f"v{v}"
            / f"accuracy_scores_v{v}.csv"
        )

        if not file_path.exists():
            continue

        df = pd.read_csv(file_path)
        if "post_claim_correct_correct" not in df.columns:
            continue

        for variant, group in df.groupby("variant"):
            scores = group["post_claim_correct_correct"].astype(float) * 100.0
            variant_scores.setdefault(variant, []).extend(scores.tolist())

    row = {"Model": model}
    for variant in ("correct", "incorrect"):
        scores = variant_scores.get(variant, [])
        row[f"{variant}_post_avg_accuracy_%"] = round(np.mean(scores), 2) if scores else np.nan
        row[f"{variant}_post_n"] = len(scores)
    if variant_scores.get("correct") and variant_scores.get("incorrect"):
        row["gap_incorrect_minus_correct_pts"] = round(
            row["incorrect_post_avg_accuracy_%"] - row["correct_post_avg_accuracy_%"], 2
        )
    claim_accuracy_rows.append(row)

claim_accuracy_df = pd.DataFrame(claim_accuracy_rows)
print(f"\n{'='*60}\n POST_CLAIM_CORRECT ACCURACY BY POST VARIANT\n{'='*60}")
print(claim_accuracy_df.to_string(index=False))

============================================================
 POST_CLAIM_CORRECT ACCURACY BY POST VARIANT
============================================================
          Model  correct_post_avg_accuracy_%  correct_post_n  incorrect_post_avg_accuracy_%  incorrect_post_n  gap_incorrect_minus_correct_pts
     gemma4-12b                       100.00              12                         100.00                12                             0.00
      gemma-e4b                        50.00              12                           0.00                12                           -50.00
ministral-3-14b                         0.00              12                          33.33                12                            33.33
 ministral-3-8b                         8.33              12                          16.67                12                             8.34
    qwen3-vl-4b                        91.67              12                          50.00                12                           -41.67
    qwen3-vl-8b                        16.67              12                          66.67                12                            50.00

**gap_incorrect_minus_correct_pts** : Positive means the model is more accurate on incorrect posts than correct ones, across all six models in one table.

 # Test 2: Zero-pressure claim verification

In [6]:
TEST2_NAME = "test-2-gn-claim-only"
TEST2_VERSIONS = range(1, 5)  # restricted to v1-v4 only, to match Test 4's wordings

test2_rows = []
for model in MODELS:
    variant_scores = {"correct": [], "incorrect": []}
    for v in TEST2_VERSIONS:
        file_path = BASE_DIR / "outputs" / model / "quantitative" / TEST2_NAME / f"v{v}" / f"accuracy_scores_v{v}.csv"
        if not file_path.exists():
            continue
        df = pd.read_csv(file_path)
        for variant, group in df.groupby("ground_truth"):
            variant_scores.setdefault(variant, []).extend((group["correct"].astype(bool) * 100.0).tolist())
    row = {"Model": model}
    for variant in ("correct", "incorrect"):
        scores = variant_scores.get(variant, [])
        row[f"{variant}_post_avg_accuracy_%"] = round(np.mean(scores), 2) if scores else np.nan
        row[f"{variant}_post_n"] = len(scores)
    all_scores = variant_scores["correct"] + variant_scores["incorrect"]
    row["pooled_avg_accuracy_%"] = round(np.mean(all_scores), 2) if all_scores else np.nan
    if variant_scores.get("correct") and variant_scores.get("incorrect"):
        row["gap_incorrect_minus_correct_pts"] = round(
            row["incorrect_post_avg_accuracy_%"] - row["correct_post_avg_accuracy_%"], 2
        )
    test2_rows.append(row)

test2_accuracy_df = pd.DataFrame(test2_rows)
print(f"\n{'='*70}\n TEST 2 — CLAIM VERIFICATION, NO ENGAGEMENT (v1-v4 only, matched to Test 4)\n{'='*70}")
print(test2_accuracy_df.to_string(index=False))

======================================================================
 TEST 2 — CLAIM VERIFICATION, NO ENGAGEMENT (v1-v4 only, matched to Test 4)
======================================================================
          Model  correct_post_avg_accuracy_%  correct_post_n  incorrect_post_avg_accuracy_%  incorrect_post_n  pooled_avg_accuracy_%  gap_incorrect_minus_correct_pts
     gemma4-12b                         91.0             200                           99.0               200                  95.00                              8.0
      gemma-e4b                         92.5             200                           30.0               200                  61.25                            -62.5
ministral-3-14b                         50.0             200                          100.0               200                  75.00                             50.0
 ministral-3-8b                         81.0             200                           76.5               200                  78.75                             -4.5
    qwen3-vl-4b                         86.0             200                           80.0               200                  83.00                             -6.0
    qwen3-vl-8b                         66.0             200                          100.0               200                  83.00                             34.0

# Test 3: Chart percentage-reading accuracy

In [7]:
TEST3_NAME = "test-3-gn-percentages"

test3_rows = []
for model in MODELS:
    f = BASE_DIR / "outputs" / model / "quantitative" / TEST3_NAME / f"accuracy_scores_{TEST3_NAME}.csv"
    if not f.exists():
        continue
    df = pd.read_csv(f)
    test3_rows.append({
        "Model": model,
        "pop_pct_accuracy_%": round(df["chart_percentages_pop_correct"].astype(bool).mean() * 100, 1),
        "latin_pct_accuracy_%": round(df["chart_percentages_latin_correct"].astype(bool).mean() * 100, 1),
        "both_correct_%": round((df["chart_percentages_pop_correct"].astype(bool) & df["chart_percentages_latin_correct"].astype(bool)).mean() * 100, 1),
        "n": len(df),
    })

test3_accuracy_df = pd.DataFrame(test3_rows)
print(f"\n{'='*60}\n TEST 3 — CHART PERCENTAGE-READING ACCURACY\n{'='*60}")
print(test3_accuracy_df.to_string(index=False))

============================================================
 TEST 3 — CHART PERCENTAGE-READING ACCURACY
============================================================
          Model  pop_pct_accuracy_%  latin_pct_accuracy_%  both_correct_%   n
     gemma4-12b               100.0                  96.0            96.0 100
      gemma-e4b               100.0                  96.0            96.0 100
ministral-3-14b               100.0                 100.0           100.0 100
 ministral-3-8b               100.0                 100.0           100.0 100
    qwen3-vl-4b               100.0                 100.0           100.0 100
    qwen3-vl-8b               100.0                 100.0           100.0 100

# Test 4: Claim verification with engagement shown

Same single claim-verification question as Test 2, but the post now displays visible engagement
metrics at 6 magnitude levels (10 to 1,000,000), realistic (log-scaled) reaction distribution.
n=600 per wording version (v1-v4 only -- no v5/v6 for this test), 2,400 trials per model pooled.
Used as the comparison point against Test 2: does introducing fake popularity change
claim-verification accuracy on the same underlying task?

In [8]:
TEST4_NAME = "test-4-metrics-realistic-claim-only"
TEST4_VERSIONS = range(1, 5)  # only v1-v4 exist for this test
SCALE_VALUES = [10, 100, 1000, 10000, 100000, 1000000]

test4_rows = []
test4_scale_rows = []
for model in MODELS:
    variant_scores = {"correct": [], "incorrect": []}
    scale_scores = {s: [] for s in SCALE_VALUES}
    for v in TEST4_VERSIONS:
        file_path = BASE_DIR / "outputs" / model / "quantitative" / TEST4_NAME / f"v{v}" / f"accuracy_scores_v{v}.csv"
        if not file_path.exists():
            continue
        df = pd.read_csv(file_path)
        for variant, group in df.groupby("ground_truth"):
            variant_scores.setdefault(variant, []).extend((group["correct"].astype(bool) * 100.0).tolist())
        for scale, group in df.groupby("scale_value"):
            if int(scale) in scale_scores:
                scale_scores[int(scale)].extend((group["correct"].astype(bool) * 100.0).tolist())

    row = {"Model": model}
    for variant in ("correct", "incorrect"):
        scores = variant_scores.get(variant, [])
        row[f"{variant}_post_avg_accuracy_%"] = round(np.mean(scores), 2) if scores else np.nan
        row[f"{variant}_post_n"] = len(scores)
    all_scores = variant_scores["correct"] + variant_scores["incorrect"]
    row["pooled_avg_accuracy_%"] = round(np.mean(all_scores), 2) if all_scores else np.nan
    if variant_scores.get("correct") and variant_scores.get("incorrect"):
        row["gap_incorrect_minus_correct_pts"] = round(
            row["incorrect_post_avg_accuracy_%"] - row["correct_post_avg_accuracy_%"], 2
        )
    test4_rows.append(row)

    scale_row = {"Model": model}
    for s in SCALE_VALUES:
        scores = scale_scores[s]
        scale_row[f"scale_{s}_%"] = round(np.mean(scores), 2) if scores else np.nan
    test4_scale_rows.append(scale_row)

test4_accuracy_df = pd.DataFrame(test4_rows)
test4_scale_df = pd.DataFrame(test4_scale_rows)

print(f"\n{'='*70}\n TEST 4 — CLAIM VERIFICATION WITH ENGAGEMENT SHOWN (pooled across all scales)\n{'='*70}")
print(test4_accuracy_df.to_string(index=False))

print(f"\n{'='*80}\n TEST 4 — ACCURACY BY ENGAGEMENT SCALE (does magnitude matter within Test 4?)\n{'='*80}")
print(test4_scale_df.to_string(index=False))

======================================================================
 TEST 4 — CLAIM VERIFICATION WITH ENGAGEMENT SHOWN (pooled across all scales)
======================================================================
          Model  correct_post_avg_accuracy_%  correct_post_n  incorrect_post_avg_accuracy_%  incorrect_post_n  pooled_avg_accuracy_%  gap_incorrect_minus_correct_pts
     gemma4-12b                        92.83            1200                          29.58              1200                  61.21                           -63.25
      gemma-e4b                        93.00            1200                          29.75              1200                  61.38                           -63.25
ministral-3-14b                        50.00            1200                         100.00              1200                  75.00                            50.00
 ministral-3-8b                        78.00            1200                          73.83              1200                  75.92                            -4.17
    qwen3-vl-4b                        73.58            1200                          78.75              1200                  76.17                             5.17
    qwen3-vl-8b                        63.17            1200                         100.00              1200                  81.58                            36.83

================================================================================
 TEST 4 — ACCURACY BY ENGAGEMENT SCALE (does magnitude matter within Test 4?)
================================================================================
          Model  scale_10_%  scale_100_%  scale_1000_%  scale_10000_%  scale_100000_%  scale_1000000_%
     gemma4-12b       61.00        61.75         61.25          60.50           61.50            61.25
      gemma-e4b       60.75        62.00         61.75          61.25           61.00            61.50
ministral-3-14b       75.00        75.00         75.00          75.00           75.00            75.00
 ministral-3-8b       78.75        77.50         76.75          76.00           74.25            72.25
    qwen3-vl-4b       79.75        76.00         77.75          76.00           75.75            71.75
    qwen3-vl-8b       82.75        81.75         82.00          82.75           81.50            78.75

# Test 2 vs. Test 4: does introducing engagement change claim-verification accuracy?

In [9]:
compare_df = test2_accuracy_df.merge(test4_accuracy_df, on="Model", suffixes=("_t2", "_t4"))
compare_df["correct_drop_pts"] = (
    compare_df["correct_post_avg_accuracy_%_t4"] - compare_df["correct_post_avg_accuracy_%_t2"]
).round(2)
compare_df["incorrect_drop_pts"] = (
    compare_df["incorrect_post_avg_accuracy_%_t4"] - compare_df["incorrect_post_avg_accuracy_%_t2"]
).round(2)
print(compare_df[["Model", "correct_post_avg_accuracy_%_t2", "correct_post_avg_accuracy_%_t4", "correct_drop_pts",
                   "incorrect_post_avg_accuracy_%_t2", "incorrect_post_avg_accuracy_%_t4", "incorrect_drop_pts"]]
      .to_string(index=False))

          Model  correct_post_avg_accuracy_%_t2  correct_post_avg_accuracy_%_t4  correct_drop_pts  incorrect_post_avg_accuracy_%_t2  incorrect_post_avg_accuracy_%_t4  incorrect_drop_pts
     gemma4-12b                            91.0                           92.83              1.83                              99.0                             29.58              -69.42
      gemma-e4b                            92.5                           93.00              0.50                              30.0                             29.75               -0.25
ministral-3-14b                            50.0                           50.00              0.00                             100.0                            100.00                0.00
 ministral-3-8b                            81.0                           78.00             -3.00                              76.5                             73.83               -2.67
    qwen3-vl-4b                            86.0                           73.58            -12.42                              80.0                             78.75               -1.25
    qwen3-vl-8b                            66.0                           63.17             -2.83                             100.0                            100.00                0.00