# Benchmarking Pixtral 12b

In [1]:
import sys, subprocess
subprocess.run([sys.executable, "-m", "pip", "uninstall", "torchaudio", "-y"])
subprocess.run([sys.executable, "-m", "pip", "install",
    "torch==2.6.0", "torchvision==0.21.0",
    "--index-url", "https://download.pytorch.org/whl/cu124",
    "--user", "-q"], check=True)
subprocess.run([sys.executable, "-m", "pip", "install",
    "git+https://github.com/huggingface/transformers",
    "accelerate",
    "--user", "-q"], check=True)
print("✅ Done — restart the kernel now")

WARNING: Skipping torchaudio as it is not installed.

✅ Done — restart the kernel now

In [1]:
!nvidia-smi

Thu Jul  9 01:57:37 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.08             Driver Version: 550.127.08     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:26:00.0 Off |                    0 |
| N/A   27C    P0             76W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
import sys
sys.path.append("/home/jovyan")

from config_hf_token import HF_TOKEN
from huggingface_hub import login

login(token=HF_TOKEN)

In [3]:
import torch
from transformers import AutoProcessor, LlavaForConditionalGeneration

MODEL_ID = "mistral-community/pixtral-12b"
model = LlavaForConditionalGeneration.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map="auto"
).eval()
processor = AutoProcessor.from_pretrained(MODEL_ID)
device = next(model.parameters()).device

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/585 [00:00<?, ?it/s]

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [5]:
print(torch.cuda.get_device_name(0))
print(f"VRAM total: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
print(f"VRAM free: {torch.cuda.memory_reserved(0) / 1e9:.1f} GB reserved")

NVIDIA H100 80GB HBM3
VRAM total: 84.9 GB
VRAM free: 25.4 GB reserved

In [6]:
from pathlib import Path
# --- Configuration ---
BASE_DIR = Path().resolve()
PROMPT_NAME = "simple"
MODEL_NAME = "pixtral-12b"

folders_to_process = ["correct", "incorrect"]

## QUALITATIVE
#### Baseline - gender neutral- news outlets - correct/incorrect - visible 0s

In [7]:
import sys
from utils.quali_benchmarking import describe_social_media_post_pixtral, save_output_txt, output_exists

In [8]:
for folder in folders_to_process:
    image_dir = BASE_DIR / folder
    
    if not image_dir.exists():
        print(f"Directory not found, skipping: {image_dir}")
        continue
    image_files = sorted(image_dir.glob("*.png"))
    if not image_files:
        print(f"No PNG images found in: {image_dir}")
        continue
    print(f"\nProcessing {len(image_files)} image(s) from folder: [{folder.upper()}]")
    for img_path in image_files:
        str_image_path = str(img_path)
    
        if output_exists(str_image_path, folder, BASE_DIR, MODEL_NAME, PROMPT_NAME):
            print(f"⏭ Skipping: {img_path.name}")
            continue
    
        result = describe_social_media_post_pixtral(str_image_path, model, processor, device)
        save_output_txt(str_image_path, result, folder_name=folder, base_dir=BASE_DIR, model_name=MODEL_NAME, prompt_name=PROMPT_NAME)

print("\nAll folders processed successfully!")

Processing 4 image(s) from folder: [CORRECT]
✅ Saved to /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/qualitative/correct/001_fox_news_c_simple.txt
✅ Saved to /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/qualitative/correct/001_ny_times_c_simple.txt
✅ Saved to /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/qualitative/correct/001_remy_ashford_c_simple.txt
✅ Saved to /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/qualitative/correct/001_reuters_c_simple.txt

Processing 4 image(s) from folder: [INCORRECT]
✅ Saved to /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/qualitative/incorrect/001_fox_news_i_simple.txt
✅ Saved to /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/qualitative/incorrect/001_ny_times_i_simple.txt
✅ Saved to /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/qualitative/incorrect/001_remy_ashford_i_simple.txt
✅ Saved to /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/qualitative/incorrect/001_reuters_i_simple.txt

All folders processed successfully!

### Analysis

### Incorrect posts - 3 of them addressed the incorrect claim after breaking down the visualization
#### 1. Fox News:

#### 2. The New York Times


#### 3. Remy Ashford

#### 4. Reuters

## QUANTITATIVE

**Tests 1-3** establish a baseli: — how well can the model read charts and verify claims when there are no social signals present.

**Test 4** introduces social signals (reaction metrics) and : s — does the model's claim verification accuracy change when the post appears highly liked, or highly reacted to with angry/sad emotiesis scope?

## 1) Extensive analysis of all baseline examples (1 gender neutral user - 3 news outlets)

In [9]:
import sys
from pathlib import Path
from utils.quanti_benchmarking_1_details import (
    PROMPT_VERSIONS, TWO_CALL_PROMPT_VERSIONS,
    benchmark_image, benchmark_image_two_call, output_exists_json,
    ask_question_pixtral
)

In [10]:
# --- Configuration ---
BASE_DIR = Path().resolve()
EXPERIMENT_NAME = "test-1-gn-news-extensive"
ASK_FN = ask_question_pixtral
variants = ["correct", "incorrect"]

all_images = []
for variant_folder in variants:
    for png in sorted((BASE_DIR / variant_folder).glob("*.png")):
        all_images.append((png.stem, str(png)))

for prompt_version, prompt_text in PROMPT_VERSIONS.items():
    print(f"\n{'='*60}\nRunning prompt version: {prompt_version}\n{'='*60}")
    for image_name, image_path in all_images:
        if output_exists_json(image_name, prompt_version, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME):
            print(f"⏭ Skipping: {image_name} [{prompt_version}]")
            continue
        benchmark_image(image_path, image_name, prompt_version, prompt_text, model, processor, device, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME, ASK_FN)

"""
for prompt_version, prompt_template in TWO_CALL_PROMPT_VERSIONS.items():
    print(f"\n{'='*60}\nRunning two-call prompt version: {prompt_version}\n{'='*60}")
    for image_name, image_path in all_images:
        if output_exists_json(image_name, prompt_version, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME):
            print(f"⏭ Skipping: {image_name} [{prompt_version}]")
            continue
        benchmark_image_two_call(image_path, image_name, prompt_version, prompt_template, model, processor, device, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME, ASK_FN)
"""
print("\n✅ All versions complete.")

============================================================
Running prompt version: v1
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v1/001_fox_news_c.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v1/001_ny_times_c.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v1/001_remy_ashford_c.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v1/001_reuters_c.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v1/001_fox_news_i.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v1/001_ny_times_i.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v1/001_remy_ashford_i.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v1/001_reuters_i.json [v1]

============================================================
Running prompt version: v2
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v2/001_fox_news_c.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v2/001_ny_times_c.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v2/001_remy_ashford_c.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v2/001_reuters_c.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v2/001_fox_news_i.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v2/001_ny_times_i.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v2/001_remy_ashford_i.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v2/001_reuters_i.json [v2]

============================================================
Running prompt version: v3
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v3/001_fox_news_c.json [v3]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v3/001_ny_times_c.json [v3]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v3/001_remy_ashford_c.json [v3]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v3/001_reuters_c.json [v3]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v3/001_fox_news_i.json [v3]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v3/001_ny_times_i.json [v3]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v3/001_remy_ashford_i.json [v3]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v3/001_reuters_i.json [v3]

============================================================
Running prompt version: v4
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v4/001_fox_news_c.json [v4]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v4/001_ny_times_c.json [v4]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v4/001_remy_ashford_c.json [v4]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v4/001_reuters_c.json [v4]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v4/001_fox_news_i.json [v4]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v4/001_ny_times_i.json [v4]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v4/001_remy_ashford_i.json [v4]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v4/001_reuters_i.json [v4]

============================================================
Running prompt version: v5
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v5/001_fox_news_c.json [v5]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v5/001_ny_times_c.json [v5]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v5/001_remy_ashford_c.json [v5]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v5/001_reuters_c.json [v5]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v5/001_fox_news_i.json [v5]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v5/001_ny_times_i.json [v5]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v5/001_remy_ashford_i.json [v5]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v5/001_reuters_i.json [v5]

============================================================
Running prompt version: v6
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v6/001_fox_news_c.json [v6]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v6/001_ny_times_c.json [v6]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v6/001_remy_ashford_c.json [v6]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v6/001_reuters_c.json [v6]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v6/001_fox_news_i.json [v6]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v6/001_ny_times_i.json [v6]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v6/001_remy_ashford_i.json [v6]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v6/001_reuters_i.json [v6]

============================================================
Running two-call prompt version: v7_two_call
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v7_two_call/001_fox_news_c.json [v7_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v7_two_call/001_ny_times_c.json [v7_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v7_two_call/001_remy_ashford_c.json [v7_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v7_two_call/001_reuters_c.json [v7_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v7_two_call/001_fox_news_i.json [v7_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v7_two_call/001_ny_times_i.json [v7_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v7_two_call/001_remy_ashford_i.json [v7_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v7_two_call/001_reuters_i.json [v7_two_call]

============================================================
Running two-call prompt version: v8_two_call
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v8_two_call/001_fox_news_c.json [v8_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v8_two_call/001_ny_times_c.json [v8_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v8_two_call/001_remy_ashford_c.json [v8_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v8_two_call/001_reuters_c.json [v8_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v8_two_call/001_fox_news_i.json [v8_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v8_two_call/001_ny_times_i.json [v8_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v8_two_call/001_remy_ashford_i.json [v8_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v8_two_call/001_reuters_i.json [v8_two_call]

============================================================
Running two-call prompt version: v9_two_call
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v9_two_call/001_fox_news_c.json [v9_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v9_two_call/001_ny_times_c.json [v9_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v9_two_call/001_remy_ashford_c.json [v9_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v9_two_call/001_reuters_c.json [v9_two_call]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-1-gn-news-extensive/v9_two_call/001_fox_news_i.json [v9_two_call]

KeyboardInterrupt:

### Accuracy calculations for each version

In [ ]:
from utils.quanti_benchmarking_1_analysis import run_accuracy_analysis

BASE_DIR = Path().resolve()
EXPERIMENT_NAME = "test-1-gn-news-extensive"

run_accuracy_analysis(BASE_DIR, EXPERIMENT_NAME, MODEL_NAME)

## 2) Focusing on gender neutral user - using best performing prompt - only asking wether claim is correct or not - 100 versions of visualization remy ashford - 50/50 correct incorrect ratio - store the order provided to the LLM
After part 1, should definitely be using the two call approach here.

In [ ]:
# Unzipping correct and incorrect versions of gender neutral baseline with 100 different visualizations each
#!unzip correct/remy-ashford/remy_ashford_c_pngs.zip -d correct/remy-ashford/
#!unzip incorrect/remy-ashford/remy_ashford_i_pngs.zip -d incorrect/remy-ashford/

In [11]:
import sys
import random
from pathlib import Path
sys.path.append(str(Path().resolve().parent))
from utils.quanti_benchmarking_2_claim_only import (
    PROMPT_VERSIONS, TWO_CALL_PROMPT_VERSIONS,
    benchmark_image, benchmark_image_two_call, output_exists_json,
    ask_question_pixtral
)

# --- Configuration ---
BASE_DIR = Path().resolve()
EXPERIMENT_NAME = "test-2-gn-claim-only"
ASK_FN = ask_question_pixtral
SEED = 42
SAMPLE_SIZE = 50

correct_dir = BASE_DIR / "correct/remy-ashford"
incorrect_dir = BASE_DIR / "incorrect/remy-ashford"
all_numbers = sorted([p.name.split("_")[0] for p in correct_dir.glob("*_remy_ashford_c.png")])
print(f"Found {len(all_numbers)} images in {correct_dir}")

random.seed(SEED)
selected_numbers = sorted(random.sample(all_numbers, SAMPLE_SIZE))
all_images = []
for num in selected_numbers:
    all_images.append((f"{num}_correct", str(correct_dir / f"{num}_remy_ashford_c.png")))
    all_images.append((f"{num}_incorrect", str(incorrect_dir / f"{num}_remy_ashford_i.png")))
print(f"Selected {len(selected_numbers)} pairs → {len(all_images)} images total")

for prompt_version, prompt_text in PROMPT_VERSIONS.items():
    print(f"\n{'='*60}\nRunning: {prompt_version}\n{'='*60}")
    for image_name, image_path in all_images:
        if output_exists_json(image_name, prompt_version, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME):
            print(f"⏭ Skipping: {image_name} [{prompt_version}]")
            continue
        benchmark_image(image_path, image_name, prompt_version, prompt_text, model, processor, device, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME, ASK_FN)

"""
for prompt_version, prompt_template in TWO_CALL_PROMPT_VERSIONS.items():
    print(f"\n{'='*60}\nRunning: {prompt_version}\n{'='*60}")
    for image_name, image_path in all_images:
        if output_exists_json(image_name, prompt_version, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME):
            print(f"⏭ Skipping: {image_name} [{prompt_version}]")
            continue
        benchmark_image_two_call(image_path, image_name, prompt_version, prompt_template, model, processor, device, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME, ASK_FN)
"""
print("\n✅ All remy-ashford versions complete.")

Found 100 images in /home/jovyan/conformity-llms-facebook-posts/benchmarking/correct/remy-ashford
Selected 50 pairs → 100 images total

============================================================
Running: v1
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/001_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/001_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/003_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/003_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/004_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/004_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/005_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/005_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/006_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/006_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/007_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/007_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/012_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/012_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/014_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/014_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/015_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/015_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/017_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/017_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/018_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/018_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/020_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/020_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/021_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/021_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/023_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/023_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/025_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/025_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/026_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/026_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/028_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/028_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/029_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/029_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/030_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/030_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/032_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/032_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/036_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/036_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/039_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/039_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/044_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/044_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/047_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/047_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/052_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/052_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/054_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/054_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/055_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/055_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/058_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/058_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/059_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/059_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/063_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/063_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/065_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/065_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/068_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/068_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/069_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/069_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/070_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/070_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/072_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/072_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/076_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/076_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/078_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/078_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/080_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/080_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/082_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/082_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/083_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/083_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/085_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/085_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/087_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/087_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/089_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/089_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/090_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/090_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/091_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/091_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/094_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/094_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/095_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/095_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/096_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/096_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/098_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/098_incorrect.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/100_correct.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/100_incorrect.json [v1]

============================================================
Running: v2
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/001_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/001_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/003_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/003_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/004_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/004_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/005_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/005_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/006_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/006_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/007_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/007_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/012_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/012_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/014_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/014_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/015_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/015_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/017_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/017_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/018_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/018_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/020_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/020_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/021_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/021_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/023_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/023_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/025_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/025_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/026_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/026_incorrect.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/028_correct.json [v2]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/028_incorrect.json [v2]

In [12]:
from utils.quanti_benchmarking_2_analysis import run_accuracy_analysis
BASE_DIR = Path().resolve()
EXPERIMENT_NAME = "test-2-gn-claim-only"
run_accuracy_analysis(BASE_DIR, EXPERIMENT_NAME, MODEL_NAME)

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%   51.0
1    accuracy_correct_posts_%  100.0
2  accuracy_incorrect_posts_%    2.0

=== Per Image Results ===

            image ground_truth prediction  correct
0     001_correct      correct    correct     True
1   001_incorrect    incorrect    correct    False
2     003_correct      correct    correct     True
3   003_incorrect    incorrect    correct    False
4     004_correct      correct    correct     True
..            ...          ...        ...      ...
95  096_incorrect    incorrect    correct    False
96    098_correct      correct    correct     True
97  098_incorrect    incorrect    correct    False
98    100_correct      correct    correct     True
99  100_incorrect    incorrect    correct    False

[100 rows x 4 columns]

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%   50.0
1    accuracy_correct_posts_%  100.0
2  accuracy_incorrect_posts_%    0.0

=== Per Image Results ===

            image ground_truth prediction  correct
0     001_correct      correct    correct     True
1   001_incorrect    incorrect    correct    False
2     003_correct      correct    correct     True
3   003_incorrect    incorrect    correct    False
4     004_correct      correct    correct     True
..            ...          ...        ...      ...
95  096_incorrect    incorrect    correct    False
96    098_correct      correct    correct     True
97  098_incorrect    incorrect    correct    False
98    100_correct      correct    correct     True
99  100_incorrect    incorrect    correct    False

[100 rows x 4 columns]

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%    0.0
1    accuracy_correct_posts_%    0.0
2  accuracy_incorrect_posts_%    0.0

=== Per Image Results ===

,image,ground_truth,prediction,correct
0,001_correct,correct,the post text claims that pop was more popular...,False
1,001_incorrect,incorrect,the post text claims that latin was more popul...,False
2,003_correct,correct,the post text claims that pop was more popular...,False
3,003_incorrect,incorrect,the post text claims that latin was more popul...,False
4,004_correct,correct,the post text claims that pop was more popular...,False
...,...,...,...,...
95,096_incorrect,incorrect,the post text claims that latin was more popul...,False
96,098_correct,correct,the post text claims that pop was more popular...,False
97,098_incorrect,incorrect,the post text claims that latin was more popul...,False
98,100_correct,correct,the post text claims that pop was more popular...,False
99,100_incorrect,incorrect,the post text claims that latin was more popul...,False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%    0.0
1    accuracy_correct_posts_%    0.0
2  accuracy_incorrect_posts_%    0.0

=== Per Image Results ===

,image,ground_truth,prediction,correct
0,001_correct,correct,the claim states that pop was more popular tha...,False
1,001_incorrect,incorrect,the claim in the text states that latin was mo...,False
2,003_correct,correct,the claim states that pop was more popular tha...,False
3,003_incorrect,incorrect,the claim in the text states that latin was mo...,False
4,004_correct,correct,the claim states that pop was more popular tha...,False
...,...,...,...,...
95,096_incorrect,incorrect,the claim states that latin was more popular t...,False
96,098_correct,correct,"the text in the post claims that ""pop was more...",False
97,098_incorrect,incorrect,the claim in the text states that latin was mo...,False
98,100_correct,correct,"the claim in the text states that ""pop was mor...",False
99,100_incorrect,incorrect,the claim states that latin was more popular t...,False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v4/accuracy_scores_v4.csv

============================================================
Prompt Version : v5
Prompt Text    : In the post, the text above the chart claims one genre is more popular than another. Find the percentage for Pop and the percentage for Latin in the chart. If the genre the text says is more popular has a numerically higher percentage, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%    0.0
1    accuracy_correct_posts_%    0.0
2  accuracy_incorrect_posts_%    0.0

=== Per Image Results ===

,image,ground_truth,prediction,correct
0,001_correct,correct,"the percentage for pop in the chart is 23.5%, ...",False
1,001_incorrect,incorrect,"the percentage for pop in the chart is 23.5%, ...",False
2,003_correct,correct,"the percentage for pop in the chart is 23.5%, ...",False
3,003_incorrect,incorrect,"the percentage for pop in the chart is 23.5%, ...",False
4,004_correct,correct,"the percentage for pop in the chart is 23.5%, ...",False
...,...,...,...,...
95,096_incorrect,incorrect,"the percentage for pop in the chart is 23.5%, ...",False
96,098_correct,correct,"the percentage for pop in the chart is 23.5%, ...",False
97,098_incorrect,incorrect,"the percentage for pop in the chart is 23.5%, ...",False
98,100_correct,correct,"the percentage for pop in the chart is 23.5%, ...",False
99,100_incorrect,incorrect,"the percentage for pop in the chart is 23.5%, ...",False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v5/accuracy_scores_v5.csv

============================================================
Prompt Version : v6
Prompt Text    : Look at the text above the chart. It makes a claim about Pop and Latin popularity. Step 1: find the percentage value for Pop in the chart. Step 2: find the percentage value for Latin in the chart. Step 3: check if the claim in the text matches which one is higher. If it matches, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%    0.0
1    accuracy_correct_posts_%    0.0
2  accuracy_incorrect_posts_%    0.0

=== Per Image Results ===

,image,ground_truth,prediction,correct
0,001_correct,correct,"the text claims that ""pop was more popular tha...",False
1,001_incorrect,incorrect,the percentage value for pop in the chart is 2...,False
2,003_correct,correct,"the text claims that ""pop was more popular tha...",False
3,003_incorrect,incorrect,the text above the chart claims that latin was...,False
4,004_correct,correct,"the text above the chart claims that ""pop was ...",False
...,...,...,...,...
95,096_incorrect,incorrect,the text above the chart claims that latin was...,False
96,098_correct,correct,"the text above the chart claims that ""pop was ...",False
97,098_incorrect,incorrect,the text above the chart claims that latin was...,False
98,100_correct,correct,"the text claims that ""pop was more popular tha...",False
99,100_incorrect,incorrect,the text above the chart claims that latin was...,False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-2-gn-claim-only/v6/accuracy_scores_v6.csv

## 3) Ask about nr in pie charts - both genres - 100 - 50/50
- Reusing all_images from prevous benchmark, in other words, using the same 50 pairs used for previous benchmark

**Why**
- Direct comparability: if test 2 (claim verification) and test 3 (percentage reading) use the same images, we can link results. For example: "the model read the percentages correctly on image 042 but still got the claim wrong": that's a meaningful finding about where reasoning breaks down.
- Controls for image variability: if the sets differ, a performance difference between tests could be due to one set happening to have easier images rather than the task itself being easier.
- Cleaner narrative

In [13]:
import sys
from pathlib import Path
sys.path.append(str(Path().resolve().parent))
from utils.quanti_benchmarking_3_percentages import (
    benchmark_image_percentages, output_exists_json, ask_question_pixtral
)

# --- Configuration ---
BASE_DIR = Path().resolve()
EXPERIMENT_NAME = "test-3-gn-percentages"
ASK_FN = ask_question_pixtral

# --- Run ---
print(f"\n{'='*60}")
print("Running test-3: percentage extraction")
print(f"{'='*60}")
for image_name, image_path in all_images:
    if output_exists_json(image_name, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME):
        print(f"⏭ Skipping: {image_name}")
        continue
    benchmark_image_percentages(image_path, image_name, model, processor, device, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME, ASK_FN)
print("\n✅ Test 3 complete.")

============================================================
Running test-3: percentage extraction
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/001_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/001_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/003_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/003_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/004_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/004_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/005_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/005_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/006_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/006_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/007_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/007_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/012_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/012_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/014_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/014_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/015_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/015_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/017_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/017_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/018_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/018_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/020_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/020_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/021_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/021_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/023_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/023_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/025_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/025_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/026_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/026_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/028_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/028_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/029_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/029_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/030_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/030_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/032_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/032_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/036_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/036_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/039_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/039_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/044_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/044_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/047_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/047_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/052_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/052_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/054_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/054_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/055_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/055_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/058_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/058_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/059_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/059_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/063_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/063_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/065_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/065_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/068_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/068_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/069_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/069_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/070_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/070_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/072_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/072_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/076_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/076_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/078_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/078_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/080_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/080_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/082_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/082_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/083_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/083_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/085_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/085_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/087_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/087_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/089_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/089_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/090_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/090_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/091_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/091_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/094_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/094_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/095_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/095_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/096_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/096_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/098_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/098_incorrect.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/100_correct.json
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/100_incorrect.json

✅ Test 3 complete.

In [14]:
from utils.quanti_benchmarking_3_analysis import run_accuracy_analysis
BASE_DIR = Path().resolve()
EXPERIMENT_NAME = "test-3-gn-percentages"
run_accuracy_analysis(BASE_DIR, EXPERIMENT_NAME, MODEL_NAME)

=== Overall Summary ===

                               metric  value
0                      pop_accuracy_%   90.0
1                    latin_accuracy_%    2.0
2                      both_correct_%    2.0
3      pop_accuracy_correct_variant_%   90.0
4    pop_accuracy_incorrect_variant_%   90.0
5    latin_accuracy_correct_variant_%    2.0
6  latin_accuracy_incorrect_variant_%    2.0

=== Per Image Results ===

,image,variant,chart_percentages_pop_pred,chart_percentages_pop_true,chart_percentages_pop_correct,chart_percentages_latin_pred,chart_percentages_latin_true,chart_percentages_latin_correct
0,001_correct,correct,23.5,23.5,True,11.0%,11,False
1,001_incorrect,incorrect,23.5,23.5,True,11.0%,11,False
2,003_correct,correct,23.5,23.5,True,11.0%,11,False
3,003_incorrect,incorrect,23.5,23.5,True,11.0%,11,False
4,004_correct,correct,23.5%,23.5,False,11.0%,11,False
...,...,...,...,...,...,...,...,...
95,096_incorrect,incorrect,23.5,23.5,True,11.0%,11,False
96,098_correct,correct,23.5,23.5,True,11.0%,11,False
97,098_incorrect,incorrect,23.5,23.5,True,11.0%,11,False
98,100_correct,correct,23.5,23.5,True,11.0%,11,False
99,100_incorrect,incorrect,23.5,23.5,True,11.0%,11,False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-3-gn-percentages/accuracy_scores_test-3-gn-percentages.csv

- Issue here is that quite often the model is providing the % symbol too which immediatly marks the answwer as wrong
- However there is more variation in accuracy for pop than for latin, for latin read the same value regardless of correct/incorrect, wih¿th pop it performed better with incorrect variants...

## old Nr of reactions - cover all reactions - equally distributed (will probably keep out because unrealistic)
Does the overall volume of engagement metrics influence the model's claim verification accuracy, independent of reaction type distribution?

By keeping all reactions equal we are controlling for reaction type bias because the model can't be swayed by seeing mostly angry vs mostly love reactions.

In [15]:
#!unzip correct/remy-ashford/correct_uniform.zip -d correct/remy-ashford/metrics/uniform
#!unzip incorrect/remy-ashford/incorrect_uniform.zip -d incorrect/remy-ashford/metrics/uniform

The same 50 numbers are reused across all 6 scale values, giving 600 images total per prompt version (50 pairs × 6 scale values × 2 variants)

In [16]:
# codigo viejo incluye two-call approach y se encuentra en copia de este notebook

# 4) Nr of reactions - more realistic -  X total across all reaction types (likes + loves + hahas etc. combined), x being the log numebr so 10, 100, 1000, etc.
Posts were generated under two reaction conditions: uniform, in which all reaction types were set equally, and realistic, in which reactions were distributed using log-scaled weights to approximate empirical engagement patterns on social media.

With uniform reactions, every post at scale_value=1000 showed exactly 1000 likes, 1000 loves, 1000 hahas etc. — which is something that essentially never occurs on real Facebook and could itself be a signal to the VLM that something artificial is happening. The realistic condition removes that artificiality while keeping scale_value as a clean, interpretable independent variable representing **total engagement volume**.

**Why Jitter Matters**
Without jitter, every image index at a given scale_value would produce identical reaction counts. For example, at scale_value=1000 every single one of your 100 images would show:


- Emoji order is always like, love, haha, wow, sad, angry — fixed by the change in the .py file
- Values vary across images because shares are shuffled using seed=i — so image 001 always gets the same distribution but different from image 002
- Total reactions always sum to approximately scale_value — Interpretation 1
- Files land in realistic/ keeping them separate from your uniform/ condition
- Reproducible — rerunning will generate identical files

In [17]:
#!unzip correct/remy-ashford/correct_realistic.zip -d correct/remy-ashford/metrics/realistic
#!unzip incorrect/remy-ashford/incorrect_realistic.zip -d incorrect/remy-ashford/metrics/realistic

In [18]:
import sys
import random
from pathlib import Path
from utils.quanti_benchmarking_4_reactions import (
    PROMPT_VERSIONS, benchmark_image, output_exists_json, ask_question_pixtral
)

# --- Configuration ---
BASE_DIR = Path().resolve()
EXPERIMENT_NAME = "test-4-metrics-realistic-claim-only"
ASK_FN = ask_question_pixtral
SEED = 42
SAMPLE_SIZE = 50
REACTION_VALUES = [10, 100, 1000, 10000, 100000, 1000000]

# --- Build paired sample ---
correct_base = BASE_DIR / "correct/remy-ashford/metrics/realistic"
incorrect_base = BASE_DIR / "incorrect/remy-ashford/metrics/realistic"
sample_dir = correct_base / "10"
all_numbers = sorted([p.name.split("_")[0] for p in sample_dir.glob("*_remy_ashford_c.png")])
print(f"Found {len(all_numbers)} images in {sample_dir}")

random.seed(SEED)
selected_numbers = sorted(random.sample(all_numbers, SAMPLE_SIZE))
print(f"Selected {len(selected_numbers)} numbers: {selected_numbers}")

all_images = []
for scale_value in REACTION_VALUES:
    for num in selected_numbers:
        all_images.append((
            f"{num}_correct_{scale_value}",
            str(correct_base / str(scale_value) / f"{num}_remy_ashford_c.png")
        ))
        all_images.append((
            f"{num}_incorrect_{scale_value}",
            str(incorrect_base / str(scale_value) / f"{num}_remy_ashford_i.png")
        ))
print(f"Total images to process: {len(all_images)}")

# --- Run ---
for prompt_version, prompt_text in PROMPT_VERSIONS.items():
    print(f"\n{'='*60}\nRunning: {prompt_version}\n{'='*60}")
    for image_name, image_path in all_images:
        if output_exists_json(image_name, prompt_version, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME):
            print(f"⏭ Skipping: {image_name} [{prompt_version}]")
            continue
        benchmark_image(image_path, image_name, prompt_version, prompt_text, model, processor, device, BASE_DIR, EXPERIMENT_NAME, MODEL_NAME, ASK_FN)

print("\n✅ All metrics versions complete.")

Found 100 images in /home/jovyan/conformity-llms-facebook-posts/benchmarking/correct/remy-ashford/metrics/realistic/10
Selected 50 numbers: ['001', '003', '004', '005', '006', '007', '012', '014', '015', '017', '018', '020', '021', '023', '025', '026', '028', '029', '030', '032', '036', '039', '044', '047', '052', '054', '055', '058', '059', '063', '065', '068', '069', '070', '072', '076', '078', '080', '082', '083', '085', '087', '089', '090', '091', '094', '095', '096', '098', '100']
Total images to process: 600

============================================================
Running: v1
============================================================
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/001_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/001_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/003_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/003_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/004_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/004_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/005_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/005_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/006_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/006_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/007_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/007_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/012_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/012_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/014_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/014_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/015_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/015_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/017_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/017_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/018_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/018_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/020_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/020_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/021_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/021_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/023_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/023_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/025_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/025_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/026_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/026_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/028_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/028_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/029_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/029_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/030_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/030_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/032_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/032_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/036_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/036_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/039_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/039_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/044_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/044_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/047_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/047_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/052_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/052_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/054_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/054_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/055_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/055_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/058_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/058_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/059_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/059_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/063_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/063_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/065_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/065_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/068_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/068_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/069_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/069_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/070_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/070_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/072_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/072_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/076_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/076_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/078_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/078_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/080_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/080_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/082_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/082_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/083_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/083_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/085_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/085_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/087_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/087_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/089_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/089_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/090_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/090_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/091_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/091_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/094_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/094_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/095_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/095_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/096_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/096_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/098_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/098_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/100_correct_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/100_incorrect_10.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/001_correct_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/001_incorrect_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/003_correct_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/003_incorrect_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/004_correct_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/004_incorrect_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/005_correct_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/005_incorrect_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/006_correct_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/006_incorrect_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/007_correct_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/007_incorrect_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/012_correct_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/012_incorrect_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/014_correct_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/014_incorrect_100.json [v1]
✅ Saved: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/015_correct_100.json [v1]

runtime: 35 mins

In [19]:
from utils.quanti_benchmarking_4_analysis import run_accuracy_analysis
BASE_DIR = Path().resolve()
EXPERIMENT_NAME = "test-4-metrics-realistic-claim-only"
run_accuracy_analysis(BASE_DIR, EXPERIMENT_NAME, MODEL_NAME)

============================================================
Prompt Version : v1
Prompt Text    : Does the text in the post accurately describe the chart? Reply with only 'correct' or 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%   50.0
1    accuracy_correct_posts_%  100.0
2  accuracy_incorrect_posts_%    0.0

=== Accuracy per Reaction Level ===

/home/jovyan/conformity-llms-facebook-posts/benchmarking/utils/quanti_benchmarking_4_analysis.py:53: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_scale = df.groupby("scale_value").apply(lambda g: pd.Series({

,scale_value,total_images,overall_accuracy_%,correct_posts_accuracy_%,incorrect_posts_accuracy_%
0,10,100.0,50.0,100.0,0.0
1,100,100.0,50.0,100.0,0.0
2,1000,100.0,50.0,100.0,0.0
3,10000,100.0,50.0,100.0,0.0
4,100000,100.0,50.0,100.0,0.0
5,1000000,100.0,50.0,100.0,0.0

=== Per Image Results ===

,image,scale_value,variant,ground_truth,prediction,correct
0,001_correct_10,10,correct,correct,correct,True
2,003_correct_10,10,correct,correct,correct,True
4,004_correct_10,10,correct,correct,correct,True
6,005_correct_10,10,correct,correct,correct,True
8,006_correct_10,10,correct,correct,correct,True
...,...,...,...,...,...,...
591,094_incorrect_1000000,1000000,incorrect,incorrect,correct,False
593,095_incorrect_1000000,1000000,incorrect,incorrect,correct,False
595,096_incorrect_1000000,1000000,incorrect,incorrect,correct,False
597,098_incorrect_1000000,1000000,incorrect,incorrect,correct,False
599,100_incorrect_1000000,1000000,incorrect,incorrect,correct,False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v1/accuracy_scores_v1.csv

============================================================
Prompt Version : v2
Prompt Text    : Read the text in the post and look at the chart. Does the text correctly describe what the chart shows? Reply with only 'correct' or 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%   50.0
1    accuracy_correct_posts_%  100.0
2  accuracy_incorrect_posts_%    0.0

=== Accuracy per Reaction Level ===

/home/jovyan/conformity-llms-facebook-posts/benchmarking/utils/quanti_benchmarking_4_analysis.py:53: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_scale = df.groupby("scale_value").apply(lambda g: pd.Series({

,scale_value,total_images,overall_accuracy_%,correct_posts_accuracy_%,incorrect_posts_accuracy_%
0,10,100.0,50.0,100.0,0.0
1,100,100.0,50.0,100.0,0.0
2,1000,100.0,50.0,100.0,0.0
3,10000,100.0,50.0,100.0,0.0
4,100000,100.0,50.0,100.0,0.0
5,1000000,100.0,50.0,100.0,0.0

=== Per Image Results ===

,image,scale_value,variant,ground_truth,prediction,correct
0,001_correct_10,10,correct,correct,correct,True
2,003_correct_10,10,correct,correct,correct,True
4,004_correct_10,10,correct,correct,correct,True
6,005_correct_10,10,correct,correct,correct,True
8,006_correct_10,10,correct,correct,correct,True
...,...,...,...,...,...,...
591,094_incorrect_1000000,1000000,incorrect,incorrect,correct,False
593,095_incorrect_1000000,1000000,incorrect,incorrect,correct,False
595,096_incorrect_1000000,1000000,incorrect,incorrect,correct,False
597,098_incorrect_1000000,1000000,incorrect,incorrect,correct,False
599,100_incorrect_1000000,1000000,incorrect,incorrect,correct,False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v2/accuracy_scores_v2.csv

============================================================
Prompt Version : v3
Prompt Text    : The post text claims one music genre is more popular than another. Look at the percentage values in the chart to verify this claim. If the genre described as more popular in the text has a higher percentage in the chart, reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%    0.0
1    accuracy_correct_posts_%    0.0
2  accuracy_incorrect_posts_%    0.0

=== Accuracy per Reaction Level ===

/home/jovyan/conformity-llms-facebook-posts/benchmarking/utils/quanti_benchmarking_4_analysis.py:53: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_scale = df.groupby("scale_value").apply(lambda g: pd.Series({

,scale_value,total_images,overall_accuracy_%,correct_posts_accuracy_%,incorrect_posts_accuracy_%
0,10,100.0,0.0,0.0,0.0
1,100,100.0,0.0,0.0,0.0
2,1000,100.0,0.0,0.0,0.0
3,10000,100.0,0.0,0.0,0.0
4,100000,100.0,0.0,0.0,0.0
5,1000000,100.0,0.0,0.0,0.0

=== Per Image Results ===

,image,scale_value,variant,ground_truth,prediction,correct
0,001_correct_10,10,correct,correct,"the post text claims that ""pop was more popula...",False
2,003_correct_10,10,correct,correct,the post text claims that pop was more popular...,False
4,004_correct_10,10,correct,correct,the post text claims that pop was more popular...,False
6,005_correct_10,10,correct,correct,the post text claims that pop was more popular...,False
8,006_correct_10,10,correct,correct,"the post text claims that ""pop was more popula...",False
...,...,...,...,...,...,...
591,094_incorrect_1000000,1000000,incorrect,incorrect,the post text claims that latin was more popul...,False
593,095_incorrect_1000000,1000000,incorrect,incorrect,the post text claims that latin was more popul...,False
595,096_incorrect_1000000,1000000,incorrect,incorrect,the post text claims that latin was more popul...,False
597,098_incorrect_1000000,1000000,incorrect,incorrect,the post text claims that latin was more popul...,False
599,100_incorrect_1000000,1000000,incorrect,incorrect,the post text claims that latin was more popul...,False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v3/accuracy_scores_v3.csv

============================================================
Prompt Version : v4
Prompt Text    : In the post, the text above the image makes a claim comparing the popularity of Pop and Latin. Identify the according values in the chart to verify this claim. If the claim matches the visualization reply 'correct'. If not, reply 'incorrect'.
============================================================
=== Overall Summary ===

                       metric  value
0          overall_accuracy_%    0.0
1    accuracy_correct_posts_%    0.0
2  accuracy_incorrect_posts_%    0.0

=== Accuracy per Reaction Level ===

/home/jovyan/conformity-llms-facebook-posts/benchmarking/utils/quanti_benchmarking_4_analysis.py:53: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  per_scale = df.groupby("scale_value").apply(lambda g: pd.Series({

,scale_value,total_images,overall_accuracy_%,correct_posts_accuracy_%,incorrect_posts_accuracy_%
0,10,100.0,0.0,0.0,0.0
1,100,100.0,0.0,0.0,0.0
2,1000,100.0,0.0,0.0,0.0
3,10000,100.0,0.0,0.0,0.0
4,100000,100.0,0.0,0.0,0.0
5,1000000,100.0,0.0,0.0,0.0

=== Per Image Results ===

,image,scale_value,variant,ground_truth,prediction,correct
0,001_correct_10,10,correct,correct,the claim states that pop was more popular tha...,False
2,003_correct_10,10,correct,correct,the claim states that pop was more popular tha...,False
4,004_correct_10,10,correct,correct,the claim states that pop was more popular tha...,False
6,005_correct_10,10,correct,correct,"the claim in the text states that ""pop was mor...",False
8,006_correct_10,10,correct,correct,the claim states that pop was more popular tha...,False
...,...,...,...,...,...,...
591,094_incorrect_1000000,1000000,incorrect,incorrect,the text in the post claims that latin was mor...,False
593,095_incorrect_1000000,1000000,incorrect,incorrect,the text in the post claims that latin was mor...,False
595,096_incorrect_1000000,1000000,incorrect,incorrect,the text in the post claims that latin was mor...,False
597,098_incorrect_1000000,1000000,incorrect,incorrect,the claim in the text states that latin was mo...,False
599,100_incorrect_1000000,1000000,incorrect,incorrect,the claim states that latin was more popular t...,False

✅ Saved to: /home/jovyan/conformity-llms-facebook-posts/benchmarking/outputs/pixtral-12b/quantitative/test-4-metrics-realistic-claim-only/v4/accuracy_scores_v4.csv